Repository knative/pkg, pull requests merged in 2018-09, with the labels that each got.

#61 Update test-infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#62 Dont call flag.parse in pkg/test
  test/e2e_flags.go
Labels: approved, lgtm, size/XS

#63 The test logger will now log the correct caller
  logging/config.go
  test/logging/logging.go
Labels: approved, lgtm, size/S

#67 Create a kmeta package for libraries acting on ObjectMeta.
  kmeta/OWNERS
  kmeta/doc.go
  kmeta/labels.go
  kmeta/labels_test.go
Labels: approved, lgtm, size/L

#68 Switch kmeta/labels to use metav1.ObjectMetaAccessor
  kmeta/labels.go
  kmeta/labels_test.go
Labels: approved, lgtm, size/S

#69 Introduce an OwnerRefable interface
  kmeta/owner_references.go
Labels: approved, lgtm, size/M

#70 Rename kmeta.NewOwnerReference to NewControllerRef
  kmeta/owner_references.go
  kmeta/owner_references_test.go
Labels: approved, lgtm, size/M

#55 Adding ViaIndex, ViaKey, ViaFieldIndex, ViaFieldKey to FieldErrors
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, lgtm, size/L

#71 Define a package with which to support duck typed definitions.
  Gopkg.lock
  apis/duck/OWNERS
  apis/duck/doc.go
  apis/duck/register.go
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/doc.go
  apis/duck/v1alpha1/init_test.go
  apis/duck/v1alpha1/register.go
  apis/duck/v1alpha1/subscribable_types.go
  apis/duck/v1alpha1/targettable_types.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
  apis/duck/verify.go
  apis/duck/verify_test.go
  client/clientset/versioned/clientset.go
  client/clientset/versioned/fake/clientset_generated.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/register.go
  client/clientset/versioned/typed/duck/v1alpha1/doc.go
  client/clientset/versioned/typed/duck/v1alpha1/duck_client.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/doc.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_duck_client.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_kresource.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_target.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_topic.go
  client/clientset/versioned/typed/duck/v1alpha1/generated_expansion.go
  client/clientset/versioned/typed/duck/v1alpha1/kresource.go
  client/clientset/versioned/typed/duck/v1alpha1/target.go
  client/clientset/versioned/typed/duck/v1alpha1/topic.go
  client/informers/externalversions/duck/interface.go
  client/informers/externalversions/duck/v1alpha1/interface.go
  client/informers/externalversions/duck/v1alpha1/kresource.go
  client/informers/externalversions/duck/v1alpha1/target.go
  client/informers/externalversions/duck/v1alpha1/topic.go
  client/informers/externalversions/factory.go
  client/informers/externalversions/generic.go
  client/listers/duck/v1alpha1/expansion_generated.go
  client/listers/duck/v1alpha1/kresource.go
  client/listers/duck/v1alpha1/target.go
  client/listers/duck/v1alpha1/topic.go
  hack/update-codegen.sh
Labels: approved, lgtm, size/XXL

#66 Adding common condition status.
  apis/duck/v1alpha1/condition_set.go
  apis/duck/v1alpha1/condition_set_impl_test.go
  apis/duck/v1alpha1/condition_set_test.go
  apis/duck/v1alpha1/condition_type_test.go
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#73 Rename Targettable to Targetable
  apis/duck/v1alpha1/targettable_types.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#82 Don't generate clients for apis/duck
  client/clientset/versioned/clientset.go
  client/clientset/versioned/fake/clientset_generated.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/register.go
  client/clientset/versioned/typed/duck/v1alpha1/doc.go
  client/clientset/versioned/typed/duck/v1alpha1/duck_client.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/doc.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_duck_client.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_generational.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_kresource.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_target.go
  client/clientset/versioned/typed/duck/v1alpha1/fake/fake_topic.go
  client/clientset/versioned/typed/duck/v1alpha1/generated_expansion.go
  client/clientset/versioned/typed/duck/v1alpha1/generational.go
  client/clientset/versioned/typed/duck/v1alpha1/kresource.go
  client/clientset/versioned/typed/duck/v1alpha1/target.go
  client/clientset/versioned/typed/duck/v1alpha1/topic.go
  client/informers/externalversions/duck/interface.go
  client/informers/externalversions/duck/v1alpha1/generational.go
  client/informers/externalversions/duck/v1alpha1/interface.go
  client/informers/externalversions/duck/v1alpha1/kresource.go
  client/informers/externalversions/duck/v1alpha1/target.go
  client/informers/externalversions/duck/v1alpha1/topic.go
  client/informers/externalversions/factory.go
  client/informers/externalversions/generic.go
  client/listers/duck/v1alpha1/expansion_generated.go
  client/listers/duck/v1alpha1/generational.go
  client/listers/duck/v1alpha1/kresource.go
  client/listers/duck/v1alpha1/target.go
  client/listers/duck/v1alpha1/topic.go
  hack/update-codegen.sh
Labels: approved, lgtm, size/XXL

#83 Adding also always to return nil for nil errors
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, lgtm, size/M

#79 Add Sinkable and Channelable types. Fix Subscribable types.
  Gopkg.lock
  apis/duck/unstructured.go
  apis/duck/unstructured_test.go
  apis/duck/v1alpha1/channelable_types.go
  apis/duck/v1alpha1/legacy_targetable_types.go
  apis/duck/v1alpha1/sinkable_types.go
  apis/duck/v1alpha1/subscribable_types.go
  apis/duck/v1alpha1/targetable_types.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#84 Create a common way for turning GVK into GVR.
  apis/kind2resource.go
  apis/kind2resource_test.go
Labels: approved, lgtm, size/L

#85 Define an interface for interacting with Listable objects.
  apis/duck/v1alpha1/channelable_types.go
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/generational_types.go
  apis/duck/v1alpha1/legacy_targetable_types.go
  apis/duck/v1alpha1/register.go
  apis/duck/v1alpha1/sinkable_types.go
  apis/duck/v1alpha1/subscribable_types.go
  apis/duck/v1alpha1/targetable_types.go
  apis/interfaces.go
  testing/resource.go
  testing/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#88 Bump the sleep in the controller testing.
  controller/controller_test.go
Labels: approved, lgtm, size/XS

#87 Create a helper for synthesizing patches.
  apis/duck/patch.go
  apis/duck/patch_test.go
  webhook/webhook.go
Labels: approved, lgtm, size/L

#90 Sort keys and paths for FieldError.
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, lgtm, size/M

#92 Access Conditions on KResourceStatus
  apis/duck/v1alpha1/conditions_types.go
Labels: approved, lgtm, size/S

#93 Add an example / test that we can Duck type Core K8s resources.
  apis/duck/podspec_test.go
Labels: approved, lgtm, size/M

#80 Use legitimate methods to enable get and set conditions.
  Gopkg.lock
  apis/duck/v1alpha1/condition_set.go
  apis/duck/v1alpha1/condition_set_impl_test.go
Labels: approved, lgtm, size/XL

#89 Use zaptest logger for our TestLogger
  Gopkg.lock
  Gopkg.toml
  apis/duck/unstructured_test.go
  logging/testing/util.go
  vendor/go.uber.org/zap/internal/ztest/doc.go
  vendor/go.uber.org/zap/internal/ztest/timeout.go
  vendor/go.uber.org/zap/internal/ztest/writer.go
  vendor/go.uber.org/zap/zapcore/memory_encoder.go
  vendor/go.uber.org/zap/zaptest/doc.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/go.uber.org/zap/zaptest/testingt.go
  vendor/go.uber.org/zap/zaptest/timeout.go
  vendor/go.uber.org/zap/zaptest/writer.go
  webhook/certs_test.go
  webhook/helper_test.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/XL

#95 This change implements a more generalized form of the BuildTracker.
  tracker/doc.go
  tracker/enqueue.go
  tracker/enqueue_test.go
  tracker/interface.go
Labels: approved, cla: yes, lgtm, size/L

#98 Move the use of `VerifyType` in tests
  apis/duck/podspec_test.go
  apis/duck/v1alpha1/channelable_types.go
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/generational_types.go
  apis/duck/v1alpha1/implements_test.go
  apis/duck/v1alpha1/legacy_targetable_types.go
  apis/duck/v1alpha1/sinkable_types.go
  apis/duck/v1alpha1/subscribable_types.go
  apis/duck/v1alpha1/targetable_types.go
  apis/duck/verify.go
  apis/duck/verify_test.go
  testing/resource.go
  testing/resource_test.go
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/L

#101 exclude /test/... for code coverage calculation & report
  .gitattributes
Labels: approved, cla: yes, lgtm, size/XS

#100 Add n3wscott to OWNERS in pkg/api
  apis/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#105 Link to the doc on duck typing, which I missed adding before.
  apis/duck/doc.go
Labels: approved, cla: yes, lgtm, size/XS

#106 Add logic to convert the watch.Interface.
  apis/duck/proxy.go
  apis/duck/typed.go
  apis/duck/typed_test.go
Labels: approved, cla: yes, lgtm, size/L
