Repository knative/pkg, pull requests merged in 2018-08, with the labels that each got.

#33 Move our base controller infrastructure into knative/pkg.
  Gopkg.lock
  controller/OWNERS
  controller/controller.go
  controller/controller_test.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/k8s.io/client-go/util/workqueue/default_rate_limiters.go
  vendor/k8s.io/client-go/util/workqueue/delaying_queue.go
  vendor/k8s.io/client-go/util/workqueue/doc.go
  vendor/k8s.io/client-go/util/workqueue/metrics.go
  vendor/k8s.io/client-go/util/workqueue/parallelizer.go
  vendor/k8s.io/client-go/util/workqueue/queue.go
  vendor/k8s.io/client-go/util/workqueue/rate_limitting_queue.go
Labels: approved, lgtm, size/XXL

#34 Adding more field errors.
  .gitignore
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, lgtm, size/M

#36 flipped the error text around. fixed.
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, lgtm, size/XS

#35 Add Istio client from knative/serving
  .gitattributes
  Gopkg.lock
  Gopkg.toml
  apis/istio/OWNERS
  apis/istio/register.go
  apis/istio/v1alpha3/README.md
  apis/istio/v1alpha3/doc.go
  apis/istio/v1alpha3/gateway_types.go
  apis/istio/v1alpha3/register.go
  apis/istio/v1alpha3/virtualservice_types.go
  apis/istio/v1alpha3/zz_generated.deepcopy.go
  client/clientset/versioned/clientset.go
  client/clientset/versioned/doc.go
  client/clientset/versioned/fake/clientset_generated.go
  client/clientset/versioned/fake/doc.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/doc.go
  client/clientset/versioned/scheme/register.go
  client/clientset/versioned/typed/istio/v1alpha3/doc.go
  client/clientset/versioned/typed/istio/v1alpha3/fake/doc.go
  client/clientset/versioned/typed/istio/v1alpha3/fake/fake_gateway.go
  client/clientset/versioned/typed/istio/v1alpha3/fake/fake_istio_client.go
  client/clientset/versioned/typed/istio/v1alpha3/fake/fake_virtualservice.go
  client/clientset/versioned/typed/istio/v1alpha3/gateway.go
  client/clientset/versioned/typed/istio/v1alpha3/generated_expansion.go
  client/clientset/versioned/typed/istio/v1alpha3/istio_client.go
  client/clientset/versioned/typed/istio/v1alpha3/virtualservice.go
  client/informers/externalversions/factory.go
  client/informers/externalversions/generic.go
  client/informers/externalversions/internalinterfaces/factory_interfaces.go
  client/informers/externalversions/istio/interface.go
  client/informers/externalversions/istio/v1alpha3/gateway.go
  client/informers/externalversions/istio/v1alpha3/interface.go
  client/informers/externalversions/istio/v1alpha3/virtualservice.go
  client/listers/istio/v1alpha3/expansion_generated.go
  client/listers/istio/v1alpha3/gateway.go
  client/listers/istio/v1alpha3/virtualservice.go
  hack/update-codegen.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
  vendor/k8s.io/apimachinery/pkg/apimachinery/doc.go
  vendor/k8s.io/apimachinery/pkg/apimachinery/registered/registered.go
  vendor/k8s.io/apimachinery/pkg/apimachinery/types.go
  vendor/k8s.io/apimachinery/pkg/util/sets/types/types.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
Labels: approved, lgtm, size/XXL

#40 Move VolatileTime into knative/pkg
  Gopkg.lock
  apis/volatile_time.go
  apis/volatile_time_test.go
  vendor/k8s.io/apimachinery/pkg/api/equality/semantic.go
Labels: approved, lgtm, size/L

#41 Support multiple group/kind contexts in shared webhook.
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/L

#42 Add deepcopy-gen for VolatileTime.
  apis/doc.go
  apis/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#39 Add the common test e2e files
  Gopkg.lock
  test/cleanup.go
  test/e2e_flags.go
  test/kube_checks.go
  test/logging.go
  test/request.go
  test/spoof/spoof.go
  vendor/go.opencensus.io/AUTHORS
  vendor/go.opencensus.io/LICENSE
  vendor/go.opencensus.io/internal/internal.go
  vendor/go.opencensus.io/internal/sanitize.go
  vendor/go.opencensus.io/internal/tagencoding/tagencoding.go
  vendor/go.opencensus.io/internal/traceinternals.go
  vendor/go.opencensus.io/opencensus.go
  vendor/go.opencensus.io/stats/doc.go
  vendor/go.opencensus.io/stats/internal/record.go
  vendor/go.opencensus.io/stats/internal/validation.go
  vendor/go.opencensus.io/stats/measure.go
  vendor/go.opencensus.io/stats/measure_float64.go
  vendor/go.opencensus.io/stats/measure_int64.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/units.go
  vendor/go.opencensus.io/stats/view/aggregation.go
  vendor/go.opencensus.io/stats/view/aggregation_data.go
  vendor/go.opencensus.io/stats/view/collector.go
  vendor/go.opencensus.io/stats/view/doc.go
  vendor/go.opencensus.io/stats/view/export.go
  vendor/go.opencensus.io/stats/view/view.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/tag/context.go
  vendor/go.opencensus.io/tag/doc.go
  vendor/go.opencensus.io/tag/key.go
  vendor/go.opencensus.io/tag/map.go
  vendor/go.opencensus.io/tag/map_codec.go
  vendor/go.opencensus.io/tag/profile_19.go
  vendor/go.opencensus.io/tag/profile_not19.go
  vendor/go.opencensus.io/tag/validate.go
  vendor/go.opencensus.io/trace/basetypes.go
  vendor/go.opencensus.io/trace/config.go
  vendor/go.opencensus.io/trace/doc.go
  vendor/go.opencensus.io/trace/export.go
  vendor/go.opencensus.io/trace/internal/internal.go
  vendor/go.opencensus.io/trace/sampling.go
  vendor/go.opencensus.io/trace/spanbucket.go
  vendor/go.opencensus.io/trace/spanstore.go
  vendor/go.opencensus.io/trace/status_codes.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/go.opencensus.io/trace/trace_go11.go
  vendor/go.opencensus.io/trace/trace_nongo11.go
Labels: approved, lgtm, size/XXL

#44 Remove strict name metadata check to be shareable in eventing
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/M

#45 Add common test logging module
  test/e2e_flags.go
  test/logging/logging.go
Labels: approved, lgtm, size/M

#46 Add a common test clients file
  Gopkg.lock
  test/clients.go
  vendor/github.com/imdario/mergo/LICENSE
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/k8s.io/client-go/tools/auth/clientauth.go
  vendor/k8s.io/client-go/tools/clientcmd/api/latest/latest.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/doc.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/register.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/types.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/tools/clientcmd/auth_loaders.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/config.go
  vendor/k8s.io/client-go/tools/clientcmd/doc.go
  vendor/k8s.io/client-go/tools/clientcmd/flag.go
  vendor/k8s.io/client-go/tools/clientcmd/helpers.go
  vendor/k8s.io/client-go/tools/clientcmd/loader.go
  vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go
  vendor/k8s.io/client-go/tools/clientcmd/overrides.go
  vendor/k8s.io/client-go/tools/clientcmd/validation.go
  vendor/k8s.io/client-go/util/homedir/homedir.go
Labels: approved, lgtm, size/XXL

#49 Add a logkey for the reconcile key.
  controller/controller.go
  logging/logkey/constants.go
Labels: approved, lgtm, size/S

#50 Update knative/pkg/test with recent changes
  test/clients.go
  test/request.go
  test/spoof/spoof.go
Labels: approved, lgtm, size/M

#51 Update WaitForEndpointState to return response
  test/request.go
Labels: approved, lgtm, size/XS

#52 Vendor the test-infra scripts
  Gopkg.lock
  Gopkg.toml
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#53 Remove docker repo from e2e flags
  test/e2e_flags.go
Labels: approved, lgtm, size/XS

#54 Make verify-codegen.sh compatible with OS X
  hack/verify-codegen.sh
Labels: approved, lgtm, size/XS

#57 Move interfaces into single file.
  apis/field_error.go
  apis/interfaces.go
Labels: approved, lgtm, size/M

#58 Make kube_checks generic so that it can be used in serving
  test/cleanup.go
  test/clients.go
  test/kube_checks.go
Labels: approved, lgtm, size/S
