Repository knative/pkg, pull requests merged in 2018-11, with the labels that each got.

#151 Reject ObjectReferences missing key elements.
  tracker/enqueue.go
  tracker/enqueue_test.go
Labels: approved, cla: yes, lgtm, size/M

#156 Add additional validation for ObjectReferences
  tracker/enqueue.go
  tracker/enqueue_test.go
Labels: approved, cla: yes, lgtm, size/L

#155 Move the `getObject` method into `kmeta`
  controller/controller.go
  kmeta/accessor.go
  kmeta/accessor_test.go
Labels: approved, cla: yes, lgtm, size/L

#154 Adding cloudevents lib to pkg
  Gopkg.lock
  cloudevents/doc.go
  cloudevents/encoding_binary.go
  cloudevents/encoding_structured.go
  cloudevents/event.go
  cloudevents/event_test.go
  cloudevents/handler.go
  cloudevents/handler_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#153 Clean up eventing duck types
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/channelable_types.go
  apis/duck/v1alpha1/implements_test.go
  apis/duck/v1alpha1/legacy_targetable_types.go
  apis/duck/v1alpha1/register.go
  apis/duck/v1alpha1/retired_targetable_types.go
  apis/duck/v1alpha1/sinkable_types.go
  apis/duck/v1alpha1/subscribable_types.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XL

#160 Update OnChanged in tracker to support deletion events
  controller/helper.go
  controller/helper_test.go
  kmeta/accessor.go
  kmeta/accessor_test.go
  tracker/enqueue.go
  tracker/enqueue_test.go
Labels: approved, cla: yes, lgtm, size/L

#158 Add the commit ID key as constant for log label
  changeset/commit.go
  changeset/commit_test.go
  changeset/doc.go
  changeset/testdata/HEAD
  changeset/testdata/noncommitted/HEAD
  logging/config.go
  logging/logkey/constants.go
Labels: approved, cla: yes, lgtm, size/L

#163 Fix the wrong id
  metrics/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#161 Update the ConditionSet to support non-terminal conditions.
  apis/duck/v1alpha1/condition_set.go
  apis/duck/v1alpha1/condition_set_impl_test.go
  apis/duck/v1alpha1/condition_set_test.go
  apis/duck/v1alpha1/conditions_types.go
Labels: approved, cla: yes, lgtm, size/L

#164 Removing eventTime for required attrs.
  cloudevents/event.go
Labels: approved, cla: yes, lgtm, size/XS

#167 Add ErrOutOfBoundsValue for value boundary validation
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, cla: yes, lgtm, size/S

#166 Update EnqueueLabelOf to handle resources in same namespace
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#168 add metrics constants for resource type and labels
  metrics/doc.go
  metrics/metricskey/constants.go
Labels: approved, cla: yes, lgtm, size/M

#171 Run gofmt
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/generational_types.go
  apis/duck/v1alpha1/legacy_targetable_types.go
  apis/duck/v1alpha1/retired_targetable_types.go
  apis/istio/authentication/v1alpha1/policy_types.go
  apis/istio/common/v1alpha1/string.go
  apis/istio/v1alpha3/destinationrule_types.go
  apis/istio/v1alpha3/virtualservice_types.go
  changeset/commit_test.go
  controller/controller.go
  controller/controller_test.go
  controller/testing/fake_stats_reporter_test.go
  metrics/metricskey/constants.go
  test/spoof/spoof.go
  test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/L

#169 Quieting controller log
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#174 Fix spelling errors
  apis/istio/authentication/v1alpha1/policy_types.go
  apis/istio/v1alpha3/destinationrule_types.go
Labels: approved, cla: yes, lgtm, size/S

#170 update gateway
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/S

#180 Make verify-codegen.sh also check /vendor
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS
