Repository knative/pkg, pull requests merged in 2018-12, with the labels that each got.

#179 Update test-infra: keep only test-infra/scripts
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/test-infra/.github/pull-request-template.md
  vendor/github.com/knative/test-infra/CONTRIBUTING.md
  vendor/github.com/knative/test-infra/Gopkg.lock
  vendor/github.com/knative/test-infra/Gopkg.toml
  vendor/github.com/knative/test-infra/OWNERS
  vendor/github.com/knative/test-infra/README.md
  vendor/github.com/knative/test-infra/WORKSPACE
  vendor/github.com/knative/test-infra/ci/README.md
  vendor/github.com/knative/test-infra/ci/gubernator/Makefile
  vendor/github.com/knative/test-infra/ci/gubernator/README.md
  vendor/github.com/knative/test-infra/ci/gubernator/config.yaml
  vendor/github.com/knative/test-infra/ci/gubernator/redir_github.py
  vendor/github.com/knative/test-infra/ci/prow/Makefile
  vendor/github.com/knative/test-infra/ci/prow/README.md
  vendor/github.com/knative/test-infra/ci/prow/boskos/README.md
  vendor/github.com/knative/test-infra/ci/prow/boskos/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/boskos/config_start.yaml
  vendor/github.com/knative/test-infra/ci/prow/boskos/resources.yaml
  vendor/github.com/knative/test-infra/ci/prow/cluster.yaml
  vendor/github.com/knative/test-infra/ci/prow/config.yaml
  vendor/github.com/knative/test-infra/ci/prow/config_start.yaml
  vendor/github.com/knative/test-infra/ci/prow/plugins.yaml
  vendor/github.com/knative/test-infra/ci/prow/prow_setup.md
  vendor/github.com/knative/test-infra/ci/testgrid/Makefile
  vendor/github.com/knative/test-infra/ci/testgrid/README.md
  vendor/github.com/knative/test-infra/ci/testgrid/config.yaml
  vendor/github.com/knative/test-infra/dummy.go
  vendor/github.com/knative/test-infra/images/README.md
  vendor/github.com/knative/test-infra/images/apicoverage/Dockerfile
  vendor/github.com/knative/test-infra/images/apicoverage/Makefile
  vendor/github.com/knative/test-infra/images/apicoverage/README.md
  vendor/github.com/knative/test-infra/images/prow-tests/Dockerfile
  vendor/github.com/knative/test-infra/images/prow-tests/Makefile
  vendor/github.com/knative/test-infra/images/prow-tests/README.md
  vendor/github.com/knative/test-infra/test/e2e-tests.sh
  vendor/github.com/knative/test-infra/test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/test/unit/e2e-custom-flag-tests.sh
  vendor/github.com/knative/test-infra/test/unit/library-tests.sh
  vendor/github.com/knative/test-infra/test/unit/presubmit-full-custom-integration-tests.sh
  vendor/github.com/knative/test-infra/test/unit/presubmit-integration-tests-common.sh
  vendor/github.com/knative/test-infra/test/unit/presubmit-partial-custom-integration-tests.sh
  vendor/github.com/knative/test-infra/test/unit/release-tests.sh
  vendor/github.com/knative/test-infra/tools/README.md
  vendor/github.com/knative/test-infra/tools/apicoverage/README.md
  vendor/github.com/knative/test-infra/tools/apicoverage/apicoverage.go
  vendor/github.com/knative/test-infra/tools/gcs/gcs.go
  vendor/github.com/knative/test-infra/tools/githubhelper/Makefile
  vendor/github.com/knative/test-infra/tools/githubhelper/README.md
  vendor/github.com/knative/test-infra/tools/githubhelper/githubhelper.go
  vendor/github.com/knative/test-infra/tools/testgrid/testgrid.go
Labels: approved, cla: yes, lgtm, size/XXL

#183 Format markdown
  .github/issue-template.md
  DEVELOPMENT.md
  apis/istio/v1alpha3/README.md
  code-of-conduct.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#184 Simplify the core controller logic.
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#189 Format markdown
  DEVELOPMENT.md
  README.md
  apis/istio/v1alpha3/README.md
  code-of-conduct.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#182 Use different reporting periods based on the metrics backend
  controller/controller.go
  controller/stats_reporter.go
  controller/stats_reporter_test.go
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  metrics/exporter_test.go
Labels: approved, cla: yes, lgtm, size/L

#187 Clean up controller code
  controller/controller.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#191 This exempts defaulting from the rules governing field immutability.
  apis/duck/patch.go
  apis/duck/patch_test.go
  testing/resource.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#192 Undo the patch sorting.
  apis/duck/patch.go
  apis/duck/patch_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#194 Some clean ups in the FieldError code and its tests.
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, cla: yes, lgtm, size/M

#197 Add kmp, a safe wrapper for google/go-cmp
  kmp/diff.go
  kmp/diff_test.go
  kmp/doc.go
Labels: approved, cla: yes, lgtm, size/L

#196 Fix some comments about code comments left from the previous PR.
  apis/field_error.go
Labels: approved, cla: yes, lgtm, size/XS

#202 Enable 'GetServiceEndpoint' to search through all given ingress names.
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/M

#205 Add support for returning a cloudevents.EventContext from a function.
  Gopkg.lock
  cloudevents/encoding_binary.go
  cloudevents/handler.go
  cloudevents/handler_test.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
Labels: approved, cla: yes, lgtm, size/XXL

#204 Check out shell scripts with unix line endings, even on windows.
  .gitattributes
Labels: approved, cla: yes, lgtm, size/XS

#206 Add durable websocket client from serving.
  Gopkg.lock
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/client_clone.go
  vendor/github.com/gorilla/websocket/client_clone_legacy.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/json.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/mask_safe.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/trace.go
  vendor/github.com/gorilla/websocket/trace_17.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  websocket/connection.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/XXL
