Repository knative/pkg, pull requests merged in 2018-07, with the labels that each got.

#19 Add "godoc" and "go report" badges
  README.md
Labels: approved, lgtm, size/XS

#20 Add comments to exported error helpers.
  apis/field_error.go
Labels: approved, lgtm, size/XS

#18 Initial set of files for //test
  test/OWNERS
  test/README.md
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#22 Drop the fixed list of `knative/serving` components from logging.
  logging/config.go
  logging/config_test.go
Labels: approved, lgtm, size/S

#23 Pull the webhook from `knative/serving` into `knative/pkg`.
  Gopkg.lock
  hack/update-codegen.sh
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go17.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go18.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/mattbaird/jsonpatch/LICENSE
  vendor/github.com/mattbaird/jsonpatch/jsonpatch.go
  vendor/k8s.io/api/admission/v1beta1/doc.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admission/v1beta1/register.go
  vendor/k8s.io/api/admission/v1beta1/types.go
  vendor/k8s.io/api/admission/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1beta1/zz_generated.deepcopy.go
  webhook/OWNERS
  webhook/certs.go
  webhook/certs_test.go
  webhook/helper_test.go
  webhook/testing/doc.go
  webhook/testing/resource.go
  webhook/testing/zz_generated.deepcopy.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/XXL

#25 Copy pkg/signals verbatim from Serving.
  signals/signal.go
  signals/signal_posix.go
  signals/signal_windows.go
Labels: approved, lgtm, size/M

#28 Set up issue and PR templates for pkg.
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, lgtm, size/M

#29 Add yanweiguo as owner of logging directory
  logging/OWNERS
Labels: approved, lgtm, size/XS

#31 Verbose error msg for config test
  logging/config_test.go
Labels: approved, lgtm, size/XS

#32 Move the test resource out of `./webhook`.
  hack/update-codegen.sh
  testing/doc.go
  testing/resource.go
  testing/zz_generated.deepcopy.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/XS
