Repository knative/pkg, pull requests merged in 2018-10, with the labels that each got.

#109 Update knative/test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#110 Tracker: delete objRef's keyset when it is no longer needed
  tracker/enqueue.go
  tracker/enqueue_test.go
Labels: approved, cla: yes, lgtm, size/M

#107 Use `/usr/bin/env bash` instead of `/bin/bash`
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#102 Move docs from knative/serving to knative/pkg
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#111 Updating to k8s.1.11.2
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
Labels: approved, cla: yes, lgtm, size/XXL

#112 Add a test that shows modeling /scale as a duck for core K8s types.
  apis/duck/scale_test.go
Labels: approved, cla: yes, lgtm, size/M

#117 Add Generation variants of kmeta/labels.go
  kmeta/labels.go
  kmeta/labels_test.go
Labels: approved, cla: yes, lgtm, size/L

#120 Update k8s to 1.11.3
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta2/generated.pb.go
  vendor/k8s.io/api/authentication/v1/generated.pb.go
  vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
  vendor/k8s.io/api/authorization/v1/generated.pb.go
  vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1beta1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/events/v1beta1/generated.pb.go
  vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
  vendor/k8s.io/api/networking/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
  vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
  vendor/k8s.io/api/settings/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1/generated.pb.go
  vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/api/resource/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/labels/selector.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.pb.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/code-generator/Godeps/Godeps.json
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/namer.go
Labels: approved, cla: yes, lgtm, size/XXL

#121 Add timestamps to the e2e logs
  test/logging/logging.go
Labels: approved, cla: yes, lgtm, size/XS

#113 Move timeout as an arg for WaitForDeploymentState
  test/kube_checks.go
Labels: approved, cla: yes, lgtm, size/XS

#118 Support 'hostname' and 'ip' when communicating with ingressgateway.
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/S

#122 Add timeKey so time is actually logged in e2e tests.
  test/logging/logging.go
Labels: approved, cla: yes, lgtm, size/S

#132 Prepare for global resync on ConfigMap changes
  configmap/filter.go
  configmap/filter_test.go
  configmap/store.go
  configmap/store_test.go
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/XL

#127 Add reconciler metrics
  Gopkg.lock
  controller/controller.go
  controller/controller_test.go
  controller/stats_reporter.go
  controller/stats_reporter_test.go
  controller/testing/fake_stats_reporter.go
  controller/testing/fake_stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#133 fix bug of generating plural in webhook
  Gopkg.lock
  vendor/github.com/gobuffalo/envy/LICENSE.txt
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/github.com/markbates/inflect/LICENCE
  vendor/github.com/markbates/inflect/helpers.go
  vendor/github.com/markbates/inflect/inflect.go
  vendor/github.com/markbates/inflect/name.go
  vendor/github.com/markbates/inflect/version.go
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#131 Exit when bootstrap http server of webhook error
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#125 Make clientAuth of webhook server into a configuration option
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#138 Fix flaky test for metrics exporter.
  metrics/exporter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#134 Make Channelable match the definition in https://github.com/knative/eventing/pull/482.
  apis/duck/v1alpha1/channelable_types.go
Labels: approved, cla: yes, lgtm, size/S

#142 Check error condition when setting default kubeconfig
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#145 Add support for StrategicMergePatch to duck
  Gopkg.lock
  Gopkg.toml
  apis/duck/patch.go
  apis/duck/patch_test.go
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
Labels: approved, cla: yes, lgtm, size/XXL

#140 Add webhook svc name to DNSNames of cert
  webhook/certs.go
  webhook/certs_test.go
Labels: approved, cla: yes, lgtm, size/XS

#99 Simplify FieldError merging.
  apis/field_error.go
  apis/field_error_test.go
  apis/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#146 update EnqueueControllerOf to properly handle Delete
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#148 Export method to get service endpoint from spoof client
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/M

#147 Relax the requirement for stackdriver project id for metrics exporter.
  metrics/config.go
  metrics/config_test.go
Labels: approved, cla: yes, lgtm, size/L

#119 Adding Zipkin tracing support for SpoofingClient
  test/spoof/spoof.go
  test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/L

#149 requeue keys on error in controller
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M
