Repository knative/pkg, pull requests merged in 2019-11, with the labels that each got.

#840 Assorted linting fixes.
  Gopkg.lock
  apis/duck/cached_test.go
  cloudevents/event_v01.go
  cloudevents/handler_test.go
  codegen/cmd/injection-gen/generators/fakeinformer.go
  controller/stats_reporter.go
  injection/informers_test.go
  kmp/reporters_test.go
  logging/config.go
  test/ghutil/fakeghutil/fakeghutil.go
  test/gke/client.go
  test/gke/wait.go
  test/helpers/dryrun.go
  test/junit/junit_test.go
  test/mako/alerter/github/issue.go
  test/webhook-apicoverage/resourcetree/test_util.go
  testutils/clustermanager/e2e-tests/gke.go
  webhook/resourcesemantics/resourcesemantics_test.go
  webhook/testing/testing.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#824 Restrict metric pkg Stackdriver Secret to controlled name & namespace
  metrics/config.go
  metrics/config_test.go
  metrics/exporter_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/L

#812 Start moving Stackdriver and Prometheus-specific code to a strategy pattern
  metrics/config.go
  metrics/config_test.go
  metrics/exporter_test.go
  metrics/metricstest/metricstest.go
  metrics/record.go
  metrics/record_test.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/L

#841 add EnqueueSentinel to pkg/controller
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#844 Remove cloudevents in favor of the upstream SDK.
  OWNERS_ALIASES
  cloudevents/OWNERS
  cloudevents/README.md
  cloudevents/builder.go
  cloudevents/builder_context_test.go
  cloudevents/builder_test.go
  cloudevents/client.go
  cloudevents/client_test.go
  cloudevents/doc.go
  cloudevents/encoding_binary.go
  cloudevents/encoding_structured.go
  cloudevents/event.go
  cloudevents/event_test.go
  cloudevents/event_v01.go
  cloudevents/event_v02.go
  cloudevents/handler.go
  cloudevents/handler_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#845 adding note about undoing release staging.
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/S

#849 remove vaikas-google since was replaced with vaikas
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#775 Remove openapi-gen annotations
  apis/condition_types.go
  apis/duck/v1/status_types.go
  apis/duck/v1beta1/status_types.go
  apis/volatile_time.go
Labels: approved, cla: yes, lgtm, size/XS

#850 Add fake functions for GCP metadata and Stackdriver back
  metrics/exporter_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/M

#846 Eventing StackDriver internal metrics
  metrics/config_test.go
  metrics/exporter_test.go
  metrics/metricskey/constants_eventing.go
  metrics/monitored_resources_eventing.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/M

#851 Move Destination under knative.dev/pkg/apis/duck/v1[beta1].
  apis/duck/v1/destination.go
  apis/duck/v1/destination_test.go
  apis/duck/v1/source_types.go
  apis/duck/v1/zz_generated.deepcopy.go
  apis/duck/v1beta1/destination.go
  apis/duck/v1beta1/destination_test.go
  apis/duck/v1beta1/source_types.go
  apis/duck/v1beta1/zz_generated.deepcopy.go
  apis/v1alpha1/doc.go
  apis/v1alpha1/zz_generated.deepcopy.go
  hack/update-codegen.sh
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#852 Made ReadProfilingKey method public and more generic
  profiling/server.go
Labels: approved, cla: yes, lgtm, size/XS

#854 Backport Eventing StackDriver metrics to release-0.10 (#846)
  metrics/config_test.go
  metrics/exporter_test.go
  metrics/metricskey/constants_eventing.go
  metrics/monitored_resources_eventing.go
  metrics/record_test.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/M

#857 Add Namespace index to listers in tests.
  reconciler/testing/sorter.go
Labels: approved, cla: yes, lgtm, size/XS

#858 Fix the race in the webhook test.
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/S

#860 Expand the tracker interface to include a variant with its own type.
  reconciler/testing/tracker.go
  tracker/enqueue.go
  tracker/enqueue_test.go
  tracker/interface.go
  tracker/interface_test.go
Labels: approved, cla: yes, lgtm, size/L

#861 Add support for Selector in tracker.Reference.
  hack/update-codegen.sh
  tracker/doc.go
  tracker/enqueue.go
  tracker/enqueue_test.go
  tracker/interface.go
  tracker/interface_test.go
  tracker/zz_generated.deepcopy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#864 Allow passing options to NewSDKClient()
  test/gke/client.go
  test/gke/client_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#786 move metrics config to pkg
  hack/update-codegen.sh
  hack/verify-codegen.sh
  metrics/config.go
  metrics/config_observability.go
  metrics/config_observability_test.go
  metrics/zz_generated.deepcopy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#875 Format markdown
  webhook/README.md
Labels: approved, cla: yes, lgtm, size/M

#872 Skip watching the ConfigMaps if they are missing
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#876 golang format tools
  metrics/config.go
  metrics/config_test.go
  metrics/record_test.go
  test/gke/client_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#877 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#878 Remove ugly constant string being printed in every log.
  logging/config.go
Labels: approved, cla: yes, lgtm, size/XS

#879 golang format tools
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/XS

#870 Address serving#5949 by putting flag initialization into pkg.
  test/e2e_flags.go
  test/e2e_flags_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#848 Split the resource semantic webhooks into separate AdmissionControllers
  apis/interfaces.go
  testing/resource.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/defaulting/user_info.go
  webhook/resourcesemantics/defaulting/user_info_test.go
  webhook/resourcesemantics/interface.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/table_test.go
  webhook/resourcesemantics/validation/validation.go
  webhook/resourcesemantics/validation/validation_deprecated_test.go
  webhook/resourcesemantics/validation/validation_test.go
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#881 Allow glog to coexist with klog
  Gopkg.lock
  test/e2e_flags.go
  test/e2e_flags_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#884 Make PodSpeccable a real thing
  apis/duck/v1/implements_test.go
  apis/duck/v1/podspec_types.go
  apis/duck/v1/register.go
  apis/duck/v1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#836 Fixed knative activator handshake timeout issue
  websocket/connection.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#892 golang format tools
  test/cmd/command.go
  test/cmd/command_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#893 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#868 Mako stub improvements
  test/mako/config/benchmark.go
  test/mako/sidecar.go
  test/mako/stub-sidecar/main.go
  test/mako/stub-sidecar/read_results.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#896 Reduce the boilerplate for setting up duck.InformerFactory's.
  apis/duck/patch_test.go
  apis/duck/scale_test.go
  apis/duck/v1/addressable_types.go
  apis/duck/v1/podspec_types.go
  apis/duck/v1/source_types.go
  apis/duck/v1/status_types.go
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/legacy_targetable_types.go
  apis/duck/v1alpha1/retired_targetable_types.go
  apis/duck/v1beta1/addressable_types.go
  apis/duck/v1beta1/source_types.go
  apis/duck/v1beta1/status_types.go
  apis/duck/verify.go
  apis/duck/verify_test.go
  client/injection/ducks/duck/v1/addressable/addressable.go
  client/injection/ducks/duck/v1/addressable/fake/fake.go
  client/injection/ducks/duck/v1/conditions/conditions.go
  client/injection/ducks/duck/v1/conditions/fake/fake.go
  client/injection/ducks/duck/v1/podspecable/fake/fake.go
  client/injection/ducks/duck/v1/podspecable/podspecable.go
  client/injection/ducks/duck/v1/source/fake/fake.go
  client/injection/ducks/duck/v1/source/source.go
  client/injection/ducks/duck/v1alpha1/addressable/addressable.go
  client/injection/ducks/duck/v1alpha1/addressable/fake/fake.go
  client/injection/ducks/duck/v1alpha1/conditions/conditions.go
  client/injection/ducks/duck/v1alpha1/conditions/fake/fake.go
  client/injection/ducks/duck/v1alpha1/legacytargetable/fake/fake.go
  client/injection/ducks/duck/v1alpha1/legacytargetable/legacytargetable.go
  client/injection/ducks/duck/v1alpha1/targetable/fake/fake.go
  client/injection/ducks/duck/v1alpha1/targetable/targetable.go
  client/injection/ducks/duck/v1beta1/addressable/addressable.go
  client/injection/ducks/duck/v1beta1/addressable/fake/fake.go
  client/injection/ducks/duck/v1beta1/conditions/conditions.go
  client/injection/ducks/duck/v1beta1/conditions/fake/fake.go
  client/injection/ducks/duck/v1beta1/source/fake/fake.go
  client/injection/ducks/duck/v1beta1/source/source.go
  codegen/cmd/injection-gen/generators/duck.go
  codegen/cmd/injection-gen/generators/fakeduck.go
  codegen/cmd/injection-gen/generators/packages.go
  hack/update-codegen.sh
  injection/ducks.go
  injection/informers.go
  injection/interface.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#898 This adds a duck type representing the common shape for Bindings.
  apis/duck/README.md
  apis/duck/v1alpha1/binding_types.go
  apis/duck/v1alpha1/implements_test.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
  client/injection/ducks/duck/v1alpha1/binding/binding.go
  client/injection/ducks/duck/v1alpha1/binding/fake/fake.go
Labels: approved, cla: yes, lgtm, size/L

#899 Fix the serialized name of the spec field (oops)
  apis/duck/v1alpha1/binding_types.go
Labels: approved, cla: yes, lgtm, size/XS

#903 Add an -imagetemplate option to allow for more flexible test image locations.
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#900 Add a simple ToUnstructured method for converting our types to unstructured.
  apis/duck/unstructured.go
  apis/duck/unstructured_test.go
  testing/resource.go
Labels: approved, cla: yes, lgtm, size/L

#904 Format markdown
  apis/duck/README.md
Labels: approved, cla: yes, lgtm, size/XS

#905 Resolvev1destination
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/L

#880 Add check in informer to make controllers work when process invalid resources
  apis/duck/typed.go
  apis/duck/typed_test.go
Labels: approved, cla: yes, lgtm, size/M

#906 Remove panics from the test and use t.Fatalf instead
  webhook/configmaps/configmaps_test.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/resourcesemantics/validation/validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#902 Added test utilities methods
  test/kube_checks.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#908 Auto-update dependencies
  Gopkg.lock
  client/injection/client/client.go
  client/injection/client/fake/fake.go
  client/injection/informers/factory/factory.go
  client/injection/informers/factory/fake/fake.go
Labels: approved, cla: yes, lgtm, size/XS

#909 Change URIFromDestinationV1 to return apis.URL instead of string
  apis/url.go
  apis/url_test.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/L

#911 This has three small table testing changes.
  reconciler/testing/table.go
  webhook/testing/listers.go
Labels: approved, cla: yes, lgtm, size/S

#914 Some cleanups in the URI tests
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/M

#912 fix comment, followup to 911
  webhook/testing/listers.go
Labels: approved, cla: yes, lgtm, size/XS
