Repository knative/pkg, pull requests merged in 2019-10, with the labels that each got.

#732 fix typo
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/XS

#731 Make Logf public for SpoofingClient struct
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#707 Increase maxRecvMsgSize in grpc server of mako-stub
  test/mako/stub-sidecar/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#734 Clustermanager lib: don't expose initialize, calling it internally only, also allow skip cluster creation and force cleanup options
  testutils/clustermanager/client.go
  testutils/clustermanager/example_test.go
  testutils/clustermanager/gke.go
  testutils/clustermanager/gke_test.go
Labels: approved, cla: yes, lgtm, size/L

#739 make the NullTracker a fake to capture Track calls
  reconciler/testing/tracker.go
Labels: approved, cla: yes, lgtm, size/M

#740 Clustermanager lib supports zonal cluster
  testutils/clustermanager/gke.go
  testutils/clustermanager/gke_test.go
  testutils/clustermanager/util.go
  testutils/clustermanager/util_test.go
Labels: approved, cla: yes, lgtm, size/L

#738 allow for custom assertions to be made in TableTests
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/XS

#742 Make repository optional in config-mako
  test/mako/alerter/alerter.go
  test/mako/alerter/github/issue.go
  test/mako/config/configmap.go
  test/mako/config/environment.go
  test/mako/sidecar.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#745 Fix the token path for perf tests
  test/mako/sidecar.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#737 Move GKE basic operations to a separate package
  testutils/clustermanager/example_test.go
  testutils/clustermanager/gke.go
  testutils/clustermanager/gke_test.go
  testutils/clustermanager/util.go
  testutils/clustermanager/util_test.go
  testutils/gke/addon.go
  testutils/gke/client.go
  testutils/gke/fake/client.go
  testutils/gke/location.go
  testutils/gke/location_test.go
  testutils/gke/request.go
  testutils/gke/request_test.go
  testutils/gke/wait.go
Labels: approved, cla: yes, lgtm, size/XXL

#746 Handle and retry 'connection reset by peer' errors
  test/spoof/error_checks.go
  test/spoof/error_checks_test.go
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#747 Allow passing benchmark ids to mako setup
  test/mako/sidecar.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#751 Spoof.New should fail when ResolveEndpoint fails
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#748 Improve Github alerter for Mako
  test/mako/alerter/alerter.go
  test/mako/alerter/github/issue.go
  test/mako/alerter/github/issue_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#752 Support listing all clusters under a project'
  testutils/gke/client.go
  testutils/gke/fake/client.go
Labels: approved, cla: yes, lgtm, size/M

#753 Clean up websocket code a bit.
  websocket/connection.go
Labels: approved, cla: yes, lgtm, size/S

#754 Add OWNERS to the websocket which was missing before.
  OWNERS_ALIASES
  websocket/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#755 Modify cluster manager lib to make it work better with Prow
  testutils/clustermanager/example_test.go
  testutils/clustermanager/gke.go
  testutils/clustermanager/gke_test.go
  testutils/gke/fake/client.go
Labels: approved, cla: yes, lgtm, size/XL

#758 Add RunInformers function
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#759 Optimizations for Mako alerter
  test/mako/alerter/alerter.go
  test/mako/alerter/github/issue.go
  test/mako/alerter/slack/message.go
  test/mako/alerter/slack/message_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#761 Add comment for full metric name construct
  metrics/config.go
Labels: approved, cla: yes, lgtm, size/XS

#720 Adding common sourceLabels func
  OWNERS_ALIASES
  source/OWNERS
  source/doc.go
  source/source_labels.go
  source/source_labels_test.go
Labels: approved, cla: yes, lgtm, size/M

#760 jsonTrace errors are retried until the timeout.
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#764 Add support for new addons for GKE cluster
  testutils/gke/addon.go
  testutils/gke/request_test.go
Labels: approved, cla: yes, lgtm, size/M

#763 Some refactors of the pkg/test code
  test/gke/addon.go
  test/gke/client.go
  test/gke/fake/client.go
  test/gke/location.go
  test/gke/location_test.go
  test/gke/request.go
  test/gke/request_test.go
  test/gke/wait.go
  test/helpers/data.go
  test/helpers/dryrun.go
  test/helpers/name.go
  test/helpers/name_test.go
  testutils/clustermanager/e2e-tests/boskos/boskos.go
  testutils/clustermanager/e2e-tests/boskos/boskos_test.go
  testutils/clustermanager/e2e-tests/boskos/fake/fake.go
  testutils/clustermanager/e2e-tests/client.go
  testutils/clustermanager/e2e-tests/common/common.go
  testutils/clustermanager/e2e-tests/common/common_test.go
  testutils/clustermanager/e2e-tests/doc.go
  testutils/clustermanager/e2e-tests/example_test.go
  testutils/clustermanager/e2e-tests/gke.go
  testutils/clustermanager/e2e-tests/gke_test.go
  testutils/clustermanager/e2e-tests/util.go
  testutils/clustermanager/e2e-tests/util_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#770 Name the parameters of functions in GKE SDK interface
  test/gke/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#771 Modify GKE fake client to make the operations thread-safe
  test/gke/fake/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#769 Fix race condition when updating Stackdriver exporter
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/L

#776 Add perf test cluster manager
  testutils/clustermanager/perf-tests/main.go
  testutils/clustermanager/perf-tests/pkg/benchmark.go
  testutils/clustermanager/perf-tests/pkg/benchmark_test.go
  testutils/clustermanager/perf-tests/pkg/cluster.go
  testutils/clustermanager/perf-tests/pkg/cluster_test.go
  testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark1/cluster.yaml
  testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark2/cluster.yaml
  testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark3/cluster.yaml
  testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark4/noop.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#780 Do not override log level if component is undefined in logging config
  logging/config.go
  logging/config_test.go
Labels: approved, cla: yes, kind/bug, lgtm, size/L

#765 Bump YAML library to latest release
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
Labels: approved, cla: yes, lgtm, size/M

#784 Add aggregate chart link in the performance issue
  test/mako/alerter/alerter.go
  test/mako/sidecar.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#778 Enable coverage for test code
  .gitattributes
Labels: approved, cla: yes, lgtm, size/XS

#767 Remove glog from test/logging
  Gopkg.lock
  test/logging/logging.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#750 Move prow and gcs package from test-infra to pkg
  Gopkg.lock
  test/gcs/gcs.go
  test/gcs/gcs_test.go
  test/prow/prow.go
  test/prow/prow_test.go
  vendor/cloud.google.com/go/iam/iam.go
  vendor/cloud.google.com/go/internal/annotate.go
  vendor/cloud.google.com/go/internal/optional/optional.go
  vendor/cloud.google.com/go/internal/retry.go
  vendor/cloud.google.com/go/internal/trace/trace.go
  vendor/cloud.google.com/go/storage/acl.go
  vendor/cloud.google.com/go/storage/bucket.go
  vendor/cloud.google.com/go/storage/copy.go
  vendor/cloud.google.com/go/storage/doc.go
  vendor/cloud.google.com/go/storage/go110.go
  vendor/cloud.google.com/go/storage/iam.go
  vendor/cloud.google.com/go/storage/invoke.go
  vendor/cloud.google.com/go/storage/not_go110.go
  vendor/cloud.google.com/go/storage/notifications.go
  vendor/cloud.google.com/go/storage/reader.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/cloud.google.com/go/storage/writer.go
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/genproto/googleapis/iam/v1/iam_policy.pb.go
  vendor/google.golang.org/genproto/googleapis/iam/v1/options.pb.go
  vendor/google.golang.org/genproto/googleapis/iam/v1/policy.pb.go
  vendor/google.golang.org/genproto/googleapis/rpc/code/code.pb.go
  vendor/google.golang.org/genproto/googleapis/type/expr/expr.pb.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#774 change Destination api and addressable resolver, fixed unit tests and…
  apis/v1alpha1/destination.go
  apis/v1alpha1/destination_test.go
  apis/v1alpha1/zz_generated.deepcopy.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/L

#785 Add utility methods for api.URL
  apis/url.go
  apis/url_test.go
Labels: approved, cla: yes, lgtm, size/L

#773 Add metahelper for reading/writing metadata in Prow
  testutils/metahelper/client/client.go
  testutils/metahelper/client/client_test.go
  testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/L

#788 Add prow-cluster-operation package
  testutils/clustermanager/prow-cluster-operation/README.md
  testutils/clustermanager/prow-cluster-operation/actions/create.go
  testutils/clustermanager/prow-cluster-operation/actions/delete.go
  testutils/clustermanager/prow-cluster-operation/actions/get.go
  testutils/clustermanager/prow-cluster-operation/main.go
  testutils/clustermanager/prow-cluster-operation/options/options.go
Labels: approved, cla: yes, lgtm, size/L

#791 golang format tools
  apis/url_test.go
  apis/v1alpha1/destination.go
  apis/v1alpha1/destination_test.go
  resolver/addressable_resolver_test.go
  test/zipkin/util.go
  testutils/clustermanager/e2e-tests/gke_test.go
  testutils/clustermanager/perf-tests/pkg/cluster_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#792 Format markdown
  testutils/clustermanager/prow-cluster-operation/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#793 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#795 Change built-in metrics to use internal ones for activator and revision
  metrics/config_test.go
  metrics/metricskey/constants_serving.go
  metrics/record_test.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/S

#798 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#797 Add metrics tags length verification
  metrics/metricstest/metricstest.go
Labels: approved, cla: yes, lgtm, size/S

#790 add DeprecatedObjectReference in Destination to support backwards compatibility
  apis/v1alpha1/destination.go
  apis/v1alpha1/destination_test.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/L

#800 add method to Destination validation that disallows Deprecated* fields
  apis/v1alpha1/destination.go
  apis/v1alpha1/destination_test.go
Labels: approved, cla: yes, lgtm, size/L

#801 Add Destination.GetRef() to abstract out the ref vs deprecated ref.
  apis/v1alpha1/destination.go
  apis/v1alpha1/destination_test.go
Labels: approved, cla: yes, lgtm, size/L

#804 golang format tools
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#796 Small fixes of Mako alerter on Github
  test/mako/alerter/github/issue.go
  test/mako/alerter/github/issue_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#805 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#794 Add field to metrics config for configuring Stackdriver exporter client
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  metrics/exporter_test.go
  metrics/gcp_metadata.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#808 duckument the ducktypes.
  apis/duck/README.md
Labels: approved, cla: yes, lgtm, size/M

#802 Stop using OwnerRefs for webhook config lifecycle
  webhook/config_validation_controller.go
  webhook/config_validation_controller_test.go
  webhook/resource_admission_controller.go
  webhook/resource_admission_controller_test.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#811 Fix name of kntive-gcp, remove build.
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/XS

#806 Log type instead of <nil> in injection panic message
  injection/clients/dynamicclient/dynamicclient.go
Labels: approved, cla: yes, lgtm, size/XS

#803 Update outdated package paths in injection usage doc
  injection/README.md
Labels: approved, cla: yes, lgtm, size/XS

#813 Add admissionregistration to our injection codegen
  Gopkg.lock
  client/injection/kube/informers/admissionregistration/v1beta1/mutatingwebhookconfiguration/fake/fake.go
  client/injection/kube/informers/admissionregistration/v1beta1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  client/injection/kube/informers/admissionregistration/v1beta1/validatingwebhookconfiguration/fake/fake.go
  client/injection/kube/informers/admissionregistration/v1beta1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#815 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#816 Add FilterByName for cluster-scoped resources.
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#817 Eliminate the Namespace config option in favor of system.Namespace.
  webhook/helper_test.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/S

#818 Move hook-specific configuration options out of shared options.
  webhook/config_validation_controller.go
  webhook/config_validation_controller_test.go
  webhook/resource_admission_controller.go
  webhook/resource_admission_controller_deprecated_test.go
  webhook/resource_admission_controller_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#819 Accept a list of AdmissionControllers instead of a map
  webhook/config_validation_controller.go
  webhook/resource_admission_controller.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#820 Move WithContext into the resource admission controller.
  webhook/resource_admission_controller.go
  webhook/resource_admission_controller_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#821 Streamline webhook.New
  webhook/context.go
  webhook/helper_test.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#822 Remove options to specify ClientAuth.
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#823 Switch to using GetCertificate in tls.Config
  webhook/helper_test.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#814 Slack MessageHistory only returns messages sent by the current user
  test/mako/alerter/slack/message.go
  test/mako/alerter/slack/message_test.go
  test/mako/sidecar.go
  test/slackutil/message_read.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#826 Avoid registering webhook metrics with init()
  webhook/stats_reporter.go
  webhook/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#827 Remove vestigial createDeployment
  webhook/config_validation_controller_test.go
  webhook/resource_admission_controller_test.go
  webhook/webhook_integration_test.go
Labels: approved, cla: yes, lgtm, size/S

#825 Drive GetCertificate from the lister cache of a secret informer.
  Gopkg.lock
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#828 Expand sharedmain to support launching our webhook.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/M

#829 Factor out test helpers to prepare for webhook package split.
  webhook/config_validation_controller_test.go
  webhook/helper_test.go
  webhook/resource_admission_controller_deprecated_test.go
  webhook/resource_admission_controller_test.go
  webhook/testing/testing.go
  webhook/user_info_test.go
  webhook/webhook_integration_test.go
Labels: approved, cla: yes, lgtm, size/L

#830 Split secret creation into our reconciler resources style.
  test/webhook-apicoverage/webhook/webhook.go
  webhook/certificates/resources/certs.go
  webhook/certificates/resources/certs_test.go
  webhook/certificates/resources/secret.go
  webhook/certificates/resources/secret_test.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#834 Moved junit from test-infra to pkg
  test/junit/junit.go
  test/junit/junit_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#833 This refactors our core webhook logic to be reconciler-based.
  Gopkg.lock
  test/webhook-apicoverage/webhook/apicoverage_recorder.go
  test/webhook-apicoverage/webhook/webhook.go
  webhook/README.md
  webhook/configmaps/configmaps.go
  webhook/configmaps/configmaps_test.go
  webhook/configmaps/controller.go
  webhook/configmaps/table_test.go
  webhook/helper_test.go
  webhook/resourcesemantics/controller.go
  webhook/resourcesemantics/resourcesemantics.go
  webhook/resourcesemantics/resourcesemantics_deprecated_test.go
  webhook/resourcesemantics/resourcesemantics_test.go
  webhook/resourcesemantics/table_test.go
  webhook/resourcesemantics/user_info.go
  webhook/resourcesemantics/user_info_test.go
  webhook/testing/listers.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL
