Repository knative/pkg, pull requests merged in 2019-03, with the labels that each got.

#300 Fix the sugared logger usage
  controller/controller.go
  logging/config.go
  metrics/config.go
  metrics/prometheus_exporter.go
  metrics/stackdriver_exporter.go
  webhook/certs.go
Labels: approved, cla: yes, lgtm, size/M

#301 Format markdown
  test/README.md
Labels: approved, cla: yes, lgtm, size/XS

#302 Separate common monitoring methods into monitoring package
  test/monitoring/doc.go
  test/monitoring/monitoring.go
  test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/L

#305 Updates istio HTTPMatchRequest api
  apis/istio/v1alpha3/virtualservice_types.go
  apis/istio/v1alpha3/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#308 Add support for URLs vs. simple domains to WaitForEndpointState*
  test/request.go
Labels: approved, cla: yes, lgtm, size/S

#304 golang format tools
  test/monitoring/monitoring.go
Labels: approved, cla: yes, lgtm, size/XS

#292 Decide whether to record metrics according to current metrics config
  controller/stats_reporter.go
  controller/stats_reporter_test.go
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  metrics/exporter_test.go
  metrics/metricskey/constants.go
  metrics/record.go
  metrics/record_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#311 Use a fake exporter in unit tests
  metrics/exporter_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/S

#313 Consistently log the full response on errors in tests.
  test/request.go
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/S

#268 Fix VirtualService tcp and tls definitions
  apis/istio/v1alpha3/virtualservice_types.go
  apis/istio/v1alpha3/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#294 Add missing CORS Policy to Istio HTTP route
  apis/istio/v1alpha3/virtualservice_types.go
  apis/istio/v1alpha3/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XS

#312 Remove 'MatchesAny'.
  test/request.go
Labels: approved, cla: yes, lgtm, size/XS

#315 Record metrics if config is nil
  controller/stats_reporter_test.go
  metrics/record.go
  metrics/record_test.go
Labels: approved, cla: yes, lgtm, size/M

#316 Dont use istio-system namespace as default for monitoring components
  test/monitoring/monitoring.go
  test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/S

#323 Modify the webhook to allow the use of duck types.
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/S

#324 Expand the Conditions duck type to also encompass ObservedGeneration.
  apis/duck/v1alpha1/condition_set_test.go
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#321 Add some more common test componets in pkg/test/
  test/clients.go
  test/crd.go
  test/e2e_flags.go
  test/kube_checks.go
Labels: approved, cla: yes, lgtm, size/L

#325 Add back KResourceStatus so eventing master can build serving 0.4
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#328 Need to use patch merge for conditions.
  apis/duck/v1alpha1/conditions_types.go
Labels: approved, cla: yes, lgtm, size/XS

#329 Retry the connection refused errors.
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/S

#330 Delete pkg/cloudevents, use cloudevents/sdk-go instead.
  Gopkg.lock
  cloudevents/OWNERS
  cloudevents/README.md
  cloudevents/builder.go
  cloudevents/builder_context_test.go
  cloudevents/builder_test.go
  cloudevents/client.go
  cloudevents/client_test.go
  cloudevents/doc.go
  cloudevents/encoding_binary.go
  cloudevents/encoding_structured.go
  cloudevents/event.go
  cloudevents/event_test.go
  cloudevents/event_v01.go
  cloudevents/event_v02.go
  cloudevents/handler.go
  cloudevents/handler_test.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
Labels: approved, cla: yes, lgtm, size/XXL

#331 Use latest tag as default to get test images
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#332 This threads a context.Context through the webhook interfaces we expose.
  apis/interfaces.go
  testing/inner_default_resource.go
  testing/inner_default_resource_test.go
  testing/resource.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#334 Factor out common logic on obtaining the ingress' endpoint.
  test/ingress/ingress.go
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/L

#335 Add some helpers to reduce boilerplate in controller binaries.
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#336 Add a GetCondition method to Status
  apis/duck/v1alpha1/condition_type_test.go
  apis/duck/v1alpha1/conditions_types.go
Labels: approved, cla: yes, lgtm, size/M

#337 Add a way to check the status of the websocket.
  websocket/connection.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/S

#338 Allow webhook implementations to optionally disallow unknown fields.
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#342 This creates a way for clients of the webhook to decorate the request context.
  testing/resource.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#345 Use apps.Deployment instead of extensions.Deployment
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/S

#346 Fix v1beta1 deployment to v1 in test
  apis/field_error.go
  test/kube_checks.go
Labels: approved, cla: yes, lgtm, size/S

#343 Retry DNS errors in spoof client.
  test/spoof/error_checks.go
  test/spoof/error_checks_test.go
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/L

#348 Refactor zipkin to add ability to get trace from traceId
  test/spoof/spoof.go
  test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/M

#350 Run ./hack/update-deps.sh
  Gopkg.lock
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#352 Fix lint error: Address struct field naming
  apis/istio/authentication/v1alpha1/policy_types.go
  apis/istio/authentication/v1alpha1/zz_generated.deepcopy.go
  apis/istio/v1alpha3/destinationrule_types.go
  apis/istio/v1alpha3/gateway_types.go
  apis/istio/v1alpha3/virtualservice_types.go
  apis/istio/v1alpha3/zz_generated.deepcopy.go
  testing/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#356 Revert delete of cloudevents.
  Gopkg.lock
  cloudevents/OWNERS
  cloudevents/README.md
  cloudevents/builder.go
  cloudevents/builder_context_test.go
  cloudevents/builder_test.go
  cloudevents/client.go
  cloudevents/client_test.go
  cloudevents/doc.go
  cloudevents/encoding_binary.go
  cloudevents/encoding_structured.go
  cloudevents/event.go
  cloudevents/event_test.go
  cloudevents/event_v01.go
  cloudevents/event_v02.go
  cloudevents/handler.go
  cloudevents/handler_test.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
Labels: approved, cla: yes, lgtm, size/XXL

#347 Expose UpdateExporter function to accept map as parameter
  metrics/config.go
  metrics/config_test.go
  metrics/exporter_test.go
  metrics/metricskey/constants.go
  metrics/prometheus_exporter.go
  metrics/prometheus_exporter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#355 Define package ingress for ingress.go
  test/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS
