Repository knative/pkg, pull requests merged in 2019-06, with the labels that each got.

#432 Remove OWNERS/tests under /vendor in update-deps.sh
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#438 Reconciler Injection, now with code-gen!
  Gopkg.lock
  client/injection/client/client.go
  client/injection/client/fake/fake.go
  client/injection/informers/authentication/factory/authenticationfactory.go
  client/injection/informers/authentication/factory/fake/fake.go
  client/injection/informers/authentication/v1alpha1/policy/fake/fake.go
  client/injection/informers/authentication/v1alpha1/policy/policy.go
  client/injection/informers/istio/factory/fake/fake.go
  client/injection/informers/istio/factory/istiofactory.go
  client/injection/informers/istio/v1alpha3/destinationrule/destinationrule.go
  client/injection/informers/istio/v1alpha3/destinationrule/fake/fake.go
  client/injection/informers/istio/v1alpha3/gateway/fake/fake.go
  client/injection/informers/istio/v1alpha3/gateway/gateway.go
  client/injection/informers/istio/v1alpha3/virtualservice/fake/fake.go
  client/injection/informers/istio/v1alpha3/virtualservice/virtualservice.go
  codegen/cmd/injection-gen/args/args.go
  codegen/cmd/injection-gen/generators/client.go
  codegen/cmd/injection-gen/generators/factory.go
  codegen/cmd/injection-gen/generators/fakeclient.go
  codegen/cmd/injection-gen/generators/fakefactory.go
  codegen/cmd/injection-gen/generators/fakeinformer.go
  codegen/cmd/injection-gen/generators/informer.go
  codegen/cmd/injection-gen/generators/namesystems.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/main.go
  hack/generate-knative.sh
  hack/update-codegen.sh
  injection/README.md
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#439 Access a logger and Fatalf when Get would return nil.
  client/injection/client/client.go
  client/injection/client/fake/fake.go
  client/injection/informers/authentication/factory/authenticationfactory.go
  client/injection/informers/authentication/v1alpha1/policy/policy.go
  client/injection/informers/istio/factory/istiofactory.go
  client/injection/informers/istio/v1alpha3/destinationrule/destinationrule.go
  client/injection/informers/istio/v1alpha3/gateway/gateway.go
  client/injection/informers/istio/v1alpha3/virtualservice/virtualservice.go
  codegen/cmd/injection-gen/generators/client.go
  codegen/cmd/injection-gen/generators/factory.go
  codegen/cmd/injection-gen/generators/fakeclient.go
  codegen/cmd/injection-gen/generators/informer.go
Labels: approved, cla: yes, lgtm, size/S

#442 Incorporate the sub-resource context into the context state populated…
  apis/contexts.go
  apis/contexts_test.go
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/M

#443 Push the event recorder stuff into knative/pkg.
  controller/controller.go
  controller/controller_test.go
  reconciler/testing/context.go
Labels: approved, cla: yes, lgtm, size/M

#445 Format markdown
  injection/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#444 golang format tools
  codegen/cmd/injection-gen/generators/client.go
  codegen/cmd/injection-gen/generators/factory.go
  codegen/cmd/injection-gen/generators/fakeclient.go
  codegen/cmd/injection-gen/generators/fakefactory.go
  codegen/cmd/injection-gen/generators/fakeinformer.go
  codegen/cmd/injection-gen/generators/informer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#447 Eliminate controller registration in favor of passing a list to the shared main.
  injection/README.md
  injection/controllers.go
  injection/controllers_test.go
  injection/doc.go
  injection/interface.go
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/L

#448 Format markdown
  injection/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#451 Add a pod informer
  injection/informers/kubeinformers/corev1/pod/fake/fake.go
  injection/informers/kubeinformers/corev1/pod/fake/fake_test.go
  injection/informers/kubeinformers/corev1/pod/pod.go
  injection/informers/kubeinformers/corev1/pod/pod_test.go
Labels: approved, cla: yes, lgtm, size/L

#452 Adding namespaces to injection, eventing uses this.
  injection/informers/kubeinformers/corev1/namespace/fake/fake.go
  injection/informers/kubeinformers/corev1/namespace/fake/fake_test.go
  injection/informers/kubeinformers/corev1/namespace/namespace.go
  injection/informers/kubeinformers/corev1/namespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/L

#454 golang format tools
  injection/informers/apiextinformers/factory/factory.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#453 Add injection for ServiceAccount and RoleBinding
  Gopkg.lock
  injection/informers/kubeinformers/corev1/serviceaccount/fake/fake.go
  injection/informers/kubeinformers/corev1/serviceaccount/fake/fake_test.go
  injection/informers/kubeinformers/corev1/serviceaccount/service.go
  injection/informers/kubeinformers/corev1/serviceaccount/service_test.go
  injection/informers/kubeinformers/rbacv1/rolebinding/fake/fake.go
  injection/informers/kubeinformers/rbacv1/rolebinding/fake/fake_test.go
  injection/informers/kubeinformers/rbacv1/rolebinding/rolebinding.go
  injection/informers/kubeinformers/rbacv1/rolebinding/rolebinding_test.go
Labels: approved, cla: yes, lgtm, size/L

#455 Remove GCP default auth.
  Gopkg.lock
  injection/sharedmain/main.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
Labels: approved, cla: yes, lgtm, size/XXL

#458 Better for loop for iterating over the channel
  apis/duck/typed.go
Labels: approved, cla: yes, lgtm, size/M

#459 Adding Batch v1 Job to injection client.
  Gopkg.lock
  injection/informers/kubeinformers/batchv1/job/fake/fake.go
  injection/informers/kubeinformers/batchv1/job/fake/fake_test.go
  injection/informers/kubeinformers/batchv1/job/job.go
  injection/informers/kubeinformers/batchv1/job/job_test.go
Labels: approved, cla: yes, lgtm, size/L

#461 Add fancier PR templates to knative/pkg
  .github/PULL_REQUEST_TEMPLATE/breaking-change.md
  .github/PULL_REQUEST_TEMPLATE/bug-fix.md
  .github/PULL_REQUEST_TEMPLATE/normal-change.md
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/M

#465 Make a small adjustment to hack/update-deps.sh
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#466 Update github.com/knative/test-infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json
  vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#468 Update github.com/knative/test-infra dependency
  Gopkg.lock
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#469 Allow endpoint polling to take request options
  test/request.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#470 Update github.com/knative/test-infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#471 Add the ChildName to pkg
  kmeta/names.go
  kmeta/names_test.go
Labels: approved, cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#472 Upstream the logstream package from knative/serving.
  test/helpers/name.go
  test/logstream/doc.go
  test/logstream/interface.go
  test/logstream/kubelogs.go
  test/logstream/null.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#478 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#479 Add injection for rbacv1.role
  injection/informers/kubeinformers/rbacv1/role/fake/fake.go
  injection/informers/kubeinformers/rbacv1/role/fake/fake_test.go
  injection/informers/kubeinformers/rbacv1/role/role.go
  injection/informers/kubeinformers/rbacv1/role/role_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#477 Use cluster-location GCP metadata as the location value
  metrics/gcp_metadata.go
Labels: approved, cla: yes, lgtm

#481 Move ExampleKey constant to 'official' package.
  configmap/store.go
  configmap/testing/configmap.go
Labels: approved, cla: yes, lgtm, size/S

#480 Enrich the logs streamed in tests with useful information.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#482 Stabilize the controller unit tests.
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#483 Refactor the tracker testing.
  tracker/enqueue_test.go
Labels: approved, cla: yes, lgtm, size/M

#485 Sprinkle more ClearAll around to enabled -count=N
  configmap/store_test.go
  metrics/config_test.go
  webhook/webhook_deprecated_test.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/S

#486 Let the stats reporter tests run with -count=N
  controller/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/S

#487 Add 'error' field to extracted logs, if available.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#488 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#467 #457 Duck type user annotation logic
  apis/interfaces.go
  testing/resource.go
  webhook/helper_test.go
  webhook/user_info.go
  webhook/user_info_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#464 Add a doc on releasing knative/pkg.
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/M

#490 golang format tools
  webhook/user_info.go
  webhook/user_info_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#491 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json
  vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#493 Format markdown
  RELEASING.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#492 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#494 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#495 update readme with knative.dev/pkg
  RELEASING.md
  cloudevents/README.md
  injection/README.md
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#496 Format markdown
  DEVELOPMENT.md
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#498 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#497 golang format tools
  apis/duck/v1alpha1/condition_set.go
  apis/duck/v1alpha1/condition_set_impl_test.go
  apis/duck/v1alpha1/condition_type_test.go
  apis/duck/v1alpha1/register.go
  apis/duck/v1beta1/register.go
  apis/duck/v1beta1/status_types_test.go
  apis/istio/authentication/v1alpha1/policy_types.go
  apis/istio/authentication/v1alpha1/register.go
  apis/istio/v1alpha3/register.go
  apis/istio/v1alpha3/virtualservice_types.go
  apis/testing/conditions.go
  cloudevents/client_test.go
  codegen/cmd/injection-gen/main.go
  configmap/testing/configmap.go
  controller/stats_reporter.go
  injection/sharedmain/main.go
  metrics/record.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
  reconciler/testing/table.go
  test/clients.go
  test/kube_checks.go
  test/logging/logging.go
  test/monitoring/monitoring.go
  test/spoof/spoof.go
  test/zipkin/util.go
  testing/inner_default_resource.go
  testing/resource.go
  tracing/http_test.go
  tracing/opencensus.go
  tracing/opencensus_test.go
  webhook/user_info_test.go
  webhook/webhook_deprecated_test.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M
