Repository knative/pkg, pull requests merged in 2019-05, with the labels that each got.

#398 Enable fields validation on delete actions
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/XS

#399 Update test-infra: some fixes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#400 Add support for a structured URL type.
  apis/url.go
  apis/url_test.go
  apis/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#402 Expose the EnqueueKeyAfter function on the controller
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/S

#407 Move serving/pkg/tracing to pkg/tracing, so that eventing can start using it
  Gopkg.lock
  metrics/exporter_test.go
  tracing/config/doc.go
  tracing/config/tracing.go
  tracing/config/tracing_test.go
  tracing/config/zz_generated.deepcopy.go
  tracing/http.go
  tracing/http_test.go
  tracing/opencensus.go
  tracing/opencensus_test.go
  tracing/zipkin.go
  tracing/zipkin_test.go
  vendor/github.com/openzipkin/zipkin-go/LICENSE
  vendor/github.com/openzipkin/zipkin-go/context.go
  vendor/github.com/openzipkin/zipkin-go/doc.go
  vendor/github.com/openzipkin/zipkin-go/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/idgenerator/idgenerator.go
  vendor/github.com/openzipkin/zipkin-go/model/annotation.go
  vendor/github.com/openzipkin/zipkin-go/model/doc.go
  vendor/github.com/openzipkin/zipkin-go/model/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/model/kind.go
  vendor/github.com/openzipkin/zipkin-go/model/span.go
  vendor/github.com/openzipkin/zipkin-go/model/span_id.go
  vendor/github.com/openzipkin/zipkin-go/model/traceid.go
  vendor/github.com/openzipkin/zipkin-go/noop.go
  vendor/github.com/openzipkin/zipkin-go/propagation/propagation.go
  vendor/github.com/openzipkin/zipkin-go/reporter/http/http.go
  vendor/github.com/openzipkin/zipkin-go/reporter/recorder/recorder.go
  vendor/github.com/openzipkin/zipkin-go/reporter/reporter.go
  vendor/github.com/openzipkin/zipkin-go/reporter/serializer.go
  vendor/github.com/openzipkin/zipkin-go/sample.go
  vendor/github.com/openzipkin/zipkin-go/span.go
  vendor/github.com/openzipkin/zipkin-go/span_implementation.go
  vendor/github.com/openzipkin/zipkin-go/span_options.go
  vendor/github.com/openzipkin/zipkin-go/tags.go
  vendor/github.com/openzipkin/zipkin-go/tracer.go
  vendor/github.com/openzipkin/zipkin-go/tracer_options.go
  vendor/go.opencensus.io/exporter/zipkin/zipkin.go
Labels: approved, cla: yes, lgtm, size/XXL

#408 add addafter method that permits enqueueing the objects themselves
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#410 Int32 is cool too
  ptr/ptr.go
  ptr/ptr_test.go
Labels: approved, cla: yes, lgtm, size/S

#414 Add Filter function by name/namespace
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#416 Update test-infra: handle stockout to work with new error string
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#415 Defaulting watcher
  configmap/informed_watcher.go
  configmap/informed_watcher_test.go
  configmap/manual_watcher.go
  configmap/manual_watcher_test.go
  configmap/static_watcher_test.go
  configmap/store.go
  configmap/watcher.go
Labels: approved, cla: yes, lgtm, size/L

#405 add trace id
  controller/controller.go
  logging/logkey/constants.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#421 Update test-infra: get rid of Unbound variable running update-deps wa…
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#419 golang format tools
  configmap/informed_watcher_test.go
  controller/controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#420 Add a new method to wrap the signal channel in a context.
  signals/signal.go
Labels: approved, cla: yes, lgtm, size/M

#426 Add methods for attaching resync duration to context.
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#425 Share the configmap name logic for Logging and Metrics.
  logging/config.go
  metrics/config.go
Labels: approved, cla: yes, lgtm, size/M

#428 This upstreams a useful helper from serving.
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/S

#429 Add a testing package to setup metrics.Domain()
  metrics/config.go
  metrics/testing/config.go
Labels: approved, cla: yes, lgtm, size/M

#424 Move common helper functions to pkg test
  test/helpers/data.go
  test/helpers/data_test.go
Labels: approved, cla: yes, lgtm, size/M

#427 Simplify the default controller.Impl constructor.
  controller/controller.go
  controller/controller_test.go
  controller/stats_reporter.go
Labels: approved, cla: yes, lgtm, size/M

#433 change metav1.Object to runtime.Object so we can test moar objects
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/XS

#434 Add a GetURL helper for consuming Addressable.
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/addressable_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#436 Logging config parses all components, rather than just a list passed in.
  logging/config.go
  logging/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#437 golang format tools
  logging/config_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
