Repository knative/pkg, pull requests merged in 2019-08, with the labels that each got.

#553 Read the logging configmap via API, not from the file system.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/M

#547 Move vegeta steadyUpPacer to pkg and add combinedPacer
  Gopkg.lock
  test/vegeta/pacers/combined_pacer.go
  test/vegeta/pacers/combined_pacer_test.go
  test/vegeta/pacers/steady_up_pacer.go
  test/vegeta/pacers/steady_up_pacer_test.go
  vendor/github.com/influxdata/tdigest/LICENSE
  vendor/github.com/influxdata/tdigest/centroid.go
  vendor/github.com/influxdata/tdigest/tdigest.go
  vendor/github.com/mailru/easyjson/LICENSE
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr_nounsafe.go
  vendor/github.com/mailru/easyjson/jlexer/error.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/github.com/tsenart/vegeta/LICENSE
  vendor/github.com/tsenart/vegeta/lib/attack.go
  vendor/github.com/tsenart/vegeta/lib/histogram.go
  vendor/github.com/tsenart/vegeta/lib/metrics.go
  vendor/github.com/tsenart/vegeta/lib/pacer.go
  vendor/github.com/tsenart/vegeta/lib/reporters.go
  vendor/github.com/tsenart/vegeta/lib/results.go
  vendor/github.com/tsenart/vegeta/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/lib/targets.go
  vendor/github.com/tsenart/vegeta/lib/targets_easyjson.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#556 Fix the panics in the naming functions.
  kmeta/names.go
  kmeta/names_test.go
Labels: approved, cla: yes, lgtm, size/M

#555 Move webhook apicoverage to knative/pkg
  Gopkg.lock
  test/webhook-apicoverage/coveragecalculator/README.md
  test/webhook-apicoverage/coveragecalculator/calculator.go
  test/webhook-apicoverage/coveragecalculator/coveragedata.go
  test/webhook-apicoverage/coveragecalculator/ignorefields.go
  test/webhook-apicoverage/resourcetree/README.md
  test/webhook-apicoverage/resourcetree/arraykindnode.go
  test/webhook-apicoverage/resourcetree/basictypekindnode.go
  test/webhook-apicoverage/resourcetree/buildChildNodes_test.go
  test/webhook-apicoverage/resourcetree/node.go
  test/webhook-apicoverage/resourcetree/otherkindnode.go
  test/webhook-apicoverage/resourcetree/ptrkindnode.go
  test/webhook-apicoverage/resourcetree/resourceforest.go
  test/webhook-apicoverage/resourcetree/resourcetree.go
  test/webhook-apicoverage/resourcetree/rule.go
  test/webhook-apicoverage/resourcetree/structkindnode.go
  test/webhook-apicoverage/resourcetree/test_util.go
  test/webhook-apicoverage/resourcetree/timetypenode.go
  test/webhook-apicoverage/resourcetree/updateCoverage_test.go
  test/webhook-apicoverage/tools/README.md
  test/webhook-apicoverage/tools/tools.go
  test/webhook-apicoverage/view/README.md
  test/webhook-apicoverage/view/html_display.go
  test/webhook-apicoverage/view/rule.go
  test/webhook-apicoverage/webhook/README.md
  test/webhook-apicoverage/webhook/apicoverage_recorder.go
  test/webhook-apicoverage/webhook/webhook.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#559 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#558 Fixing ##557
  test/request.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#560 Webhook apicoverage unittest uses Table driven test
  test/webhook-apicoverage/resourcetree/updateCoverage_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#563 golang format tools
  test/webhook-apicoverage/webhook/apicoverage_recorder.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#561 Adding apis/v1alpha1/Destination; future sink and subscriber object.
  apis/v1alpha1/destination.go
  apis/v1alpha1/destination_test.go
  apis/v1alpha1/doc.go
Labels: approved, cla: yes, lgtm, size/L

#565 golang format tools
  apis/v1alpha1/destination.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#567 Missed the deepcopy gen for Destination. Fixed.
  apis/v1alpha1/zz_generated.deepcopy.go
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#568 Test Infra 2.0: Add cluster management lib skeleton
  testutils/OWNERS
  testutils/README.md
  testutils/clustermanager/boskos/boskos.go
  testutils/clustermanager/client.go
  testutils/clustermanager/doc.go
  testutils/clustermanager/gke.go
  testutils/common/common.go
Labels: approved, cla: yes, lgtm, size/L

#566 Adding Source ducktype.
  apis/duck/v1beta1/source_types.go
  apis/duck/v1beta1/zz_generated.deepcopy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#570 Format markdown
  testutils/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#571 Document ParseURL non-conformance with the net/url.Parse api
  apis/url.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#572 Add Destination constructors
  apis/v1alpha1/destination.go
  apis/v1alpha1/destination_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#573 clustermanager: move common helpers and add more helpers
  testutils/clustermanager/gke.go
  testutils/clustermanager/gke_test.go
  testutils/clustermanager/util.go
  testutils/clustermanager/util_test.go
  testutils/common/common.go
  testutils/common/common_test.go
Labels: approved, cla: yes, lgtm, size/L

#576 Add support for resolving refs, when linked.
  changeset/commit.go
  changeset/commit_test.go
  changeset/testdata/garbage/HEAD
  changeset/testdata/with-refs/HEAD
  changeset/testdata/with-refs/refs/heads/branch-name
Labels: approved, cla: yes, lgtm, size/M

#577 Some cleanups to the changeset code
  changeset/commit.go
Labels: approved, cla: yes, lgtm, size/S

#575 Add boskos related helpers for cluster management lib
  Gopkg.lock
  Gopkg.toml
  testutils/clustermanager/boskos/boskos.go
  testutils/clustermanager/boskos/boskos_test.go
  testutils/clustermanager/gke.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/k8s.io/test-infra/LICENSE
  vendor/k8s.io/test-infra/boskos/boskos.go
  vendor/k8s.io/test-infra/boskos/client/client.go
  vendor/k8s.io/test-infra/boskos/common/common.go
  vendor/k8s.io/test-infra/boskos/common/config.go
  vendor/k8s.io/test-infra/boskos/common/mason_config.go
  vendor/k8s.io/test-infra/boskos/crds/client.go
  vendor/k8s.io/test-infra/boskos/crds/crd_storage.go
  vendor/k8s.io/test-infra/boskos/crds/drlc_crd.go
  vendor/k8s.io/test-infra/boskos/crds/resource_crd.go
  vendor/k8s.io/test-infra/boskos/ranch/priority.go
  vendor/k8s.io/test-infra/boskos/ranch/ranch.go
  vendor/k8s.io/test-infra/boskos/ranch/storage.go
  vendor/k8s.io/test-infra/boskos/storage/storage.go
  vendor/k8s.io/test-infra/gubernator/github/secrets.py
  vendor/k8s.io/test-infra/gubernator/static/octicons/LICENSE
  vendor/k8s.io/test-infra/prow/cmd/tide/pr-authors.md
  vendor/k8s.io/test-infra/prow/crier/README.md
  vendor/k8s.io/test-infra/prow/plank/README.md
  vendor/k8s.io/test-infra/prow/tide/README.md
  vendor/sigs.k8s.io/yaml/LICENSE
  vendor/sigs.k8s.io/yaml/fields.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: approved, cla: yes, lgtm, size/XXL

#580 Fix licence to have spaces and comment to match the function
  configmap/testing/configmap.go
Labels: approved, cla: yes, lgtm, size/XS

#581 Shuffle knative.dev/pkg/tracing code a bit
  tracing/opencensus.go
  tracing/zipkin.go
Labels: approved, cla: yes, lgtm, size/M

#583 Remove reflection from generic store code.
  configmap/store.go
  configmap/store_test.go
Labels: approved, cla: yes, lgtm, size/M

#582 Expand the tracing package to support stackdriver.
  tracing/config/tracing.go
  tracing/config/tracing_test.go
  tracing/http_test.go
  tracing/opencensus.go
  tracing/opencensus_test.go
  tracing/sampler_test.go
  tracing/testing/zipkin.go
  tracing/zipkin.go
  tracing/zipkin_test.go
Labels: approved, cla: yes, lgtm, size/XL

#585 Revert "Remove reflection from generic store code."
  configmap/store.go
  configmap/store_test.go
Labels: approved, cla: yes, lgtm, size/M

#587 Add dprotaso to the configmap-approvers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#588 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#590 Move mako code to pkg
  Gopkg.lock
  test/mako/README.md
  test/mako/analyzer.go
  test/mako/benchmark.go
  test/mako/config.go
  test/mako/config_test.go
  test/mako/environment.go
  test/mako/sidecar.go
  test/mako/testdata/config-mako.yaml
  test/mako/time.go
  vendor/github.com/google/mako/LICENSE
  vendor/github.com/google/mako/clients/proto/analyzers/threshold_analyzer_go_proto/threshold_analyzer.pb.go
  vendor/github.com/google/mako/clients/proto/analyzers/utest_analyzer_go_proto/utest_analyzer.pb.go
  vendor/github.com/google/mako/clients/proto/analyzers/window_deviation_go_proto/window_deviation.pb.go
  vendor/github.com/google/mako/helpers/go/quickstore/quickstore.go
  vendor/github.com/google/mako/helpers/proto/quickstore/quickstore_go_proto/quickstore.pb.go
  vendor/github.com/google/mako/internal/go/common/common_deps.go
  vendor/github.com/google/mako/internal/quickstore_microservice/proto/quickstore_go_proto/quickstore.pb.go
  vendor/github.com/google/mako/spec/proto/mako_go_proto/mako.pb.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#579 Add cluster creation logic with using GKE SDK
  Gopkg.lock
  Gopkg.toml
  testutils/clustermanager/gke.go
  testutils/clustermanager/gke_test.go
  testutils/clustermanager/util.go
  vendor/google.golang.org/api/container/v1/container-gen.go
  vendor/google.golang.org/api/gensupport/backoff.go
  vendor/google.golang.org/api/gensupport/buffer.go
  vendor/google.golang.org/api/gensupport/doc.go
  vendor/google.golang.org/api/gensupport/header.go
  vendor/google.golang.org/api/gensupport/json.go
  vendor/google.golang.org/api/gensupport/jsonfloat.go
  vendor/google.golang.org/api/gensupport/media.go
  vendor/google.golang.org/api/gensupport/params.go
  vendor/google.golang.org/api/gensupport/resumable.go
  vendor/google.golang.org/api/gensupport/retry.go
  vendor/google.golang.org/api/gensupport/send.go
  vendor/google.golang.org/api/googleapi/googleapi.go
  vendor/google.golang.org/api/googleapi/internal/uritemplates/uritemplates.go
  vendor/google.golang.org/api/googleapi/internal/uritemplates/utils.go
  vendor/google.golang.org/api/googleapi/types.go
  vendor/k8s.io/test-infra/boskos/boskos.go
  vendor/k8s.io/test-infra/boskos/crds/client.go
  vendor/k8s.io/test-infra/boskos/crds/crd_storage.go
  vendor/k8s.io/test-infra/boskos/crds/drlc_crd.go
  vendor/k8s.io/test-infra/boskos/crds/resource_crd.go
  vendor/k8s.io/test-infra/boskos/ranch/priority.go
  vendor/k8s.io/test-infra/boskos/ranch/ranch.go
  vendor/k8s.io/test-infra/boskos/ranch/storage.go
Labels: approved, cla: yes, lgtm, size/XXL

#592 Format markdown
  test/mako/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#593 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#594 Correct a unmarshal error for non pointer members of apis.URL if empty string.
  apis/url.go
  apis/url_test.go
Labels: approved, cla: yes, lgtm, size/L

#562 Profiling support
  configmap/informed_watcher.go
  configmap/manual_watcher.go
  configmap/static_watcher.go
  configmap/store_test.go
  configmap/watcher.go
  injection/sharedmain/main.go
  profiling/server.go
  profiling/server_test.go
Labels: approved, cla: yes, lgtm, size/L

#578 Resolver package for resolving addressables to URI
  Gopkg.lock
  network/OWNERS
  network/doc.go
  network/domain.go
  network/domain_test.go
  resolver/OWNERS
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
  resolver/doc.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#597 Rework how we GlobalResync.
  controller/controller.go
  controller/controller_test.go
  controller/helper.go
  controller/helper_test.go
Labels: approved, cla: yes, lgtm, size/M

#609 Add a Mako stub sidecar
  Gopkg.lock
  test/mako/stub-sidecar/main.go
  third_party/mako/LICENSE
  third_party/mako/README.md
  third_party/mako/proto/quickstore.proto
  third_party/mako/proto/quickstore_go_proto/quickstore.pb.go
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#614 update newendpoint with host for hostport
  tracing/opencensus.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#599 Define ProfilingPort and make profiling server use it
  profiling/server.go
Labels: approved, cla: yes, lgtm, size/S

#618 Format markdown
  third_party/mako/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#619 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#607 Replace string pointer with plain string
  test/ingress/ingress.go
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#612 Eventing Stackdriver integration
  metrics/config_test.go
  metrics/exporter_test.go
  metrics/gcp_metadata.go
  metrics/metricskey/constants.go
  metrics/metricskey/constants_eventing.go
  metrics/metricskey/constants_serving.go
  metrics/monitored_resources.go
  metrics/monitored_resources_eventing.go
  metrics/monitored_resources_serving.go
  metrics/record.go
  metrics/record_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#625 Extend reconciler and controller owners with engineers mostly working on the reconcilers
  OWNERS_ALIASES
  reconciler/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#624 Improve the logging situation in table tests
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/S

#623 Add CronJob informer
  Gopkg.lock
  injection/informers/kubeinformers/batchv1beta1/cronjob/cronjob.go
  injection/informers/kubeinformers/batchv1beta1/cronjob/cronjob_test.go
  injection/informers/kubeinformers/batchv1beta1/cronjob/fake/fake.go
  injection/informers/kubeinformers/batchv1beta1/cronjob/fake/fake_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L
