Repository knative/pkg, pull requests merged in 2019-02, with the labels that each got.

#259 Wait for work to complete before returning from Run.
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#261 Use the k8s sets for the code that is actually set of strings
  apis/duck/v1alpha1/condition_set.go
  cloudevents/client_test.go
  metrics/exporter.go
  metrics/metricskey/constants.go
Labels: approved, cla: yes, lgtm, size/M

#243 Webhook creates a patch for all fields generated by Go
  testing/inner_default_resource.go
  testing/inner_default_resource_test.go
  testing/zz_generated.deepcopy.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#263 golang format tools
  apis/field_error_test.go
  cloudevents/client_test.go
  cloudevents/handler.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#262 Hardening the websocket client.
  websocket/connection.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/L

#260 allow overriding spoofed gateway name/namespace
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/S

#265 Update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#143 Add static endpoint override to test/spoof
  test/README.md
  test/clients.go
  test/e2e_flags.go
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/M

#270 golang format tools
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#271 remove the redundant receiver
  apis/duck/typed_test.go
Labels: approved, cla: yes, lgtm, size/XS

#269 Add ping message verification to the websocket connection.
  websocket/connection.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/L

#272 Cleanup the webhook code.
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#256 test/helpers module to store AppendRandomString helper fn
  test/helpers/data.go
Labels: approved, cla: yes, lgtm, size/M

#275 Initial commit for the webhook to set the annotations about mutator.
  Gopkg.lock
  Gopkg.toml
  apis/interfaces.go
  testing/inner_default_resource.go
  testing/resource.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/XL

#276 golang format tools
  test/helpers/data.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#277 Don't close the http.Request body
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XS

#234 Drop spec.generation support
  apis/duck/typed_test.go
  apis/duck/v1alpha1/generational_types.go
  apis/duck/v1alpha1/implements_test.go
  apis/duck/v1alpha1/register.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
  testing/resource.go
  testing/resource_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#278 Add status matchers to help unify test code.
  test/request.go
Labels: approved, cla: yes, lgtm, size/S

#281 Helper to call Hijack on a http.ResponseWriter if possible.
  websocket/hijack.go
  websocket/hijack_test.go
Labels: approved, cla: yes, lgtm, size/L

#279 Metrics logging fix in pkg/test: Issue-3150
  test/README.md
  test/kube_checks.go
  test/logging/logging.go
  test/request.go
Labels: approved, cla: yes, lgtm, size/M

#283 Fix range expression in 'IsOneOfStatusCodes' to actually match the codes.
  test/request.go
Labels: approved, cla: yes, lgtm, size/XS

#282 Simplify and comment AppenRandomString
  test/helpers/data.go
  test/helpers/data_test.go
Labels: approved, cla: yes, lgtm, size/M

#284 Add 'MatchesAllOf' to make it possible to combine matchers.
  test/request.go
Labels: approved, cla: yes, lgtm, size/S

#285 Adapt the spoofing client to take a "FormatLogger" instead of a BaseLogger
  test/clients.go
  test/request.go
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/S

#288 Format markdown
  test/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#287 golang format tools
  test/logging/logging.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#289 Remove usage of K8S_CLUSTER_OVERRIDE
  test/README.md
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/S

#280 Update OpenCensus Stackdriver exporter version
  .gitattributes
  Gopkg.lock
  Gopkg.toml
  metrics/exporter.go
  metrics/exporter_test.go
  metrics/gcp_metadata.go
  metrics/metricskey/constants.go
  metrics/monitored_resources.go
  metrics/prometheus_exporter.go
  metrics/prometheus_exporter_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go
  vendor/github.com/census-instrumentation/opencensus-proto/AUTHORS
  vendor/github.com/census-instrumentation/opencensus-proto/LICENSE
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/common/v1/common.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1/metrics.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1/resource.pb.go
Labels: approved, cla: yes, lgtm, size/XXL

#290 Add a variant of wait for status with explicit timeout.
  test/request.go
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/M

#291 Make it possible to use 'IsStatusOK' without parentheses.
  test/request.go
Labels: approved, cla: yes, lgtm, size/XS

#273 Adding support for Zipkin tracing in SpoofClient
  test/spoof/spoof.go
  test/zipkin/doc.go
  test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/L

#296 Remove baselogger and use FormatLogger everywhere
  test/README.md
  test/cleanup.go
  test/clients.go
  test/logging/logging.go
  test/request.go
  test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/L

#297 Use FormatLogger instead of func parameter for zipoking tracing calls
  test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/XS

#298 golang format tools
  test/zipkin/doc.go
Labels: approved, cla: yes, lgtm, size/XS
