Repository knative/pkg, pull requests merged in 2019-07, with the labels that each got.

#500 Auto-update dependencies
  Gopkg.lock
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#502 Auto-update dependencies
  Gopkg.lock
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#501 added limitrange and resourcequota informers
  injection/informers/kubeinformers/corev1/limitrange/fake/fake.go
  injection/informers/kubeinformers/corev1/limitrange/fake/fake_test.go
  injection/informers/kubeinformers/corev1/limitrange/limitrange.go
  injection/informers/kubeinformers/corev1/limitrange/limitrange_test.go
  injection/informers/kubeinformers/corev1/resourcequota/fake/fake.go
  injection/informers/kubeinformers/corev1/resourcequota/fake/fake_test.go
  injection/informers/kubeinformers/corev1/resourcequota/resourcequota.go
  injection/informers/kubeinformers/corev1/resourcequota/resourcequota_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#508 Upgrade kubernetes-1.12.6 -> kubernetes-1.12.9
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/client-go/discovery/cached_discovery.go
  vendor/k8s.io/client-go/discovery/round_tripper.go
  vendor/k8s.io/client-go/rest/transport.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
Labels: approved, cla: yes, lgtm, size/M

#509 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#503 Add metrics to webhook package
  metrics/metricstest/metricstest.go
  metrics/record.go
  metrics/record_test.go
  webhook/stats_reporter.go
  webhook/stats_reporter_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#518 Add check for nil StatsReporter in webhook package
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#512 Change 'updater' to 'lastModifier' in webhook
  webhook/user_info.go
  webhook/user_info_test.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#510 add openapi-gen=true for some structs
  apis/condition_types.go
  apis/duck/v1beta1/status_types.go
  apis/volatile_time.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#525 Remove '-' from suggested component name.
  injection/README.md
  injection/doc.go
Labels: approved, cla: yes, lgtm, size/XS

#531 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#532 Remove Erik and Nikhil from Productivity Reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#533 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#528 Improve kmp.ShortDiff when one object is invalid
  kmp/diff_test.go
  kmp/reporters.go
  kmp/reporters_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#534 Move rogpeppe/go-internal to modern version
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#519 Adding Duration ptr helper.
  ptr/ptr.go
  ptr/ptr_test.go
Labels: approved, cla: yes, lgtm, size/S

#535 Add OwnerRefableAccessor into kmeta
  kmeta/ownerrefable_accessor.go
  kmeta/ownerrefable_accessor_test.go
Labels: approved, cla: yes, lgtm, size/M

#536 Add Time helper as well
  ptr/ptr.go
  ptr/ptr_test.go
Labels: approved, cla: yes, lgtm, size/S

#537 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#541 Fix the issues pointed out by staticcheck
  apis/condition_set.go
  apis/deprecated.go
  apis/duck/podspec_test.go
  apis/duck/scale_test.go
  apis/duck/typed.go
  apis/duck/v1alpha1/condition_set.go
  apis/duck/verify_test.go
  cloudevents/event.go
  configmap/manual_watcher.go
  configmap/store_test.go
  controller/controller.go
  controller/helper_test.go
  kmeta/accessor.go
  kmeta/names.go
  kmp/reporters.go
  metrics/exporter.go
  signals/signal.go
  test/clients.go
  test/ingress/ingress.go
  test/monitoring/monitoring.go
  tracing/config/tracing.go
  tracing/opencensus.go
  tracker/enqueue.go
  webhook/helper_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  websocket/connection_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#538 Implement ClearCondition for ConditionManager
  apis/condition_set.go
  apis/condition_set_impl_test.go
Labels: approved, cla: yes, lgtm, size/M

#543 Create reusable ResolveEndpoint function
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#545 Test for FieldError.Also(nil)
  apis/field_error_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#546 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#539 Add validation for creator and lastModifier annotation
  apis/metadata_validation.go
  apis/metadata_validation_test.go
  webhook/user_info.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#548 This prints better log when CM is loaded.
  configmap/store.go
Labels: approved, cla: yes, lgtm, size/XS

#549 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#551 apis: fix typo in ConditionSet.Manage comment
  apis/condition_set.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#552 Use knative.dev/test-infra
  Gopkg.lock
  Gopkg.toml
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/tools/dep-collector/README.md
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
  vendor/knative.dev/test-infra/tools/dep-collector/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#554 Derive the config for our controller setup like kubectl etc.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/M
