Repository knative/pkg, pull requests merged in 2020-07, with the labels that each got.

#1459 Update OWNERS_ALIASES to match new TOC members
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1465 make it so codegen owners can approve PRs that change codegen
  client/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1460 Remove yt3liu from OWNERS file
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1457 Update generated reconciler code with a switch
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#1466 Propagate SkipStatusUpdates to reconciler from NewReconciler
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1467 Propagate SkipStatusUpdates to reconciler from NewReconciler (#1466)
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1469 Move the hashing from the serving
  hash/OWNERS
  hash/doc.go
  hash/hash.go
  hash/hash_test.go
Labels: approved, cla: yes, lgtm, size/L

#1473 Add example to the docs of stable selection
  hash/hash_test.go
Labels: approved, cla: yes, lgtm, size/S

#1471 Update release instruction.
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/M

#1472 Use quotation marks for generated checksums
  configmap/hash-gen/main.go
  configmap/hash-gen/testdata/add_want.yaml
  configmap/hash-gen/testdata/update.yaml
  configmap/hash-gen/testdata/update_want.yaml
Labels: approved, cla: yes, lgtm, size/S

#1447 Use TraceContextB3Egress for spoof client
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1474 Make HA test helpers deal with sets.
  test/ha/ha.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1475 Fun with lambdas etc
  test/ha/ha.go
  test/ha/ha_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1388 Avoid importing apis/duck from apis/duck/<<version>>
  apis/duck/ducktypes/ducktypes.go
  apis/duck/register.go
  apis/duck/v1/addressable_types.go
  apis/duck/v1/implements_test.go
  apis/duck/v1/podspec_types.go
  apis/duck/v1/register.go
  apis/duck/v1/source_types.go
  apis/duck/v1/status_types.go
  apis/duck/v1_tests.go
  apis/duck/v1beta1/addressable_types.go
  apis/duck/v1beta1/implements_test.go
  apis/duck/v1beta1/register.go
  apis/duck/v1beta1/source_types.go
  apis/duck/v1beta1/status_types.go
  apis/duck/v1beta1_tests.go
  apis/duck/verify.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1477 Add BucketSet type which implements consistent bucketing
  go.mod
  go.sum
  hash/bucketer.go
  hash/bucketer_test.go
  hash/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/google.golang.org/api/container/v1beta1/container-api.json
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/trace.pb.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/tracing.pb.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1479 [master] golang format tools
  apis/duck/v1_tests.go
  apis/duck/v1beta1/addressable_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1480 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1476 Enable leader election by default.
  controller/controller_test.go
  injection/sharedmain/main.go
  leaderelection/config.go
  leaderelection/config_test.go
  leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/L

#1333 Add a new "chaosduck" e2e test tool for leaderelection.
  leaderelection/chaosduck/main.go
  test/ha/ha.go
  test/ha/ha_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1484 Remove ha.ExtractDeployment dependency.
  leaderelection/chaosduck/main.go
  test/ha/ha.go
  test/ha/ha_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1485 Preallocate sets in pkg
  hash/hash.go
  leaderelection/chaosduck/main.go
  webhook/psbinding/psbinding.go
Labels: approved, cla: yes, lgtm, size/XS

#1482 Remove the ResourceLock field from the pkg/LE
  controller/controller_test.go
  leaderelection/config.go
  leaderelection/config_test.go
  leaderelection/context.go
  leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/M

#1487 Add flags to disable chaos per-component and configure period.
  OWNERS_ALIASES
  kflag/OWNERS
  kflag/doc.go
  kflag/set.go
  kflag/set_test.go
  leaderelection/chaosduck/main.go
Labels: approved, cla: yes, lgtm, size/L

#1486 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1481 Use hash.BucketSet for StatefulSet mode
  hash/bucketer.go
  hash/bucketer_test.go
  leaderelection/config_test.go
  leaderelection/context.go
  leaderelection/context_test.go
  leaderelection/ordinal.go
  leaderelection/ordinal_test.go
Labels: approved, cla: yes, lgtm, size/L

#1491 Read from all meters instead of just he default one
  metrics/metricstest/metricstest.go
Labels: approved, cla: yes, lgtm, size/M

#1492 make the rt error message clearer
  apis/duck/v1/source_types.go
  apis/testing/roundtrip/roundtrip.go
Labels: approved, cla: yes, lgtm, size/XS

#1494 Remove key in tags to reduce metrics count
  controller/controller.go
  controller/stats_reporter.go
  controller/stats_reporter_test.go
  controller/testing/fake_stats_reporter.go
  controller/testing/fake_stats_reporter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1495 Update Stackdriver custom exporter to support RecordBatch where some records are special and others are not.
  metrics/resource_view_test.go
  metrics/stackdriver_exporter.go
Labels: approved, cla: yes, lgtm, size/L

#1497 Remove delay-based flakiness from workqueue_test.go
  metrics/workqueue_test.go
Labels: approved, cla: yes, lgtm, size/S

#1499 Remove unused connTimeout parameter
  network/transports.go
Labels: approved, cla: yes, lgtm, size/XS

#1496 Make logstream watch the pods as they change.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1501 Bump the drain timeout
  network/network.go
Labels: approved, cla: yes, lgtm, size/XS

#1500 Add a new method to permit creation of buckets from the bucketset
  hash/bucketer.go
  hash/bucketer_test.go
Labels: approved, cla: yes, lgtm, size/M

#1490 Use hash.BucketSet for standard leader election mode
  leaderelection/context.go
Labels: approved, cla: yes, lgtm, size/M

#1502 Generating reconciler for Deployments
  client/injection/kube/reconciler/apps/v1/deployment/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/stub/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/stub/reconciler.go
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1507 Assorted linting fixes.
  metrics/exporter_test.go
  metrics/resource_view_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
  tracing/http_test.go
Labels: approved, cla: yes, lgtm, size/M

#1506 Remove logging from pod watcher to avoid race conditions.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1508 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1510 micro-Nit in the test: don't make a private type public
  metrics/workqueue_test.go
Labels: approved, cla: yes, lgtm, size/S

#1511 Disable keep-alives on shutdown.
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XS

#1512 Implement Slowlane/FastLane queues
  controller/two_lane_queue.go
  controller/two_lane_queue_test.go
Labels: approved, cla: yes, lgtm, size/L

#1513 Make MainWithConfig respect user-provided overrides.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#1515 Enable components to get debug logging from our rest transports.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/M

#1516 Add more time for the checks
  controller/two_lane_queue_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1518 Revert "Use hash.BucketSet for standard leader election mode (#1490)"
  leaderelection/context.go
Labels: approved, cla: yes, lgtm, size/M

#1517 Implement a new shared "Drainer" handler.
  network/error_handler.go
  network/handlers/doc.go
  network/handlers/drain.go
  network/handlers/drain_test.go
  network/handlers/error.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/L

#1514 Use two lane queue instead of the regular workqueue
  controller/controller.go
  webhook/certificates/certificates_test.go
  webhook/configmaps/table_test.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit_test.go
Labels: approved, cla: yes, lgtm, size/M

#1521 Harden and reaarange the test for drain handler
  network/handlers/drain.go
  network/handlers/drain_test.go
Labels: approved, cla: yes, lgtm, size/M

#1522 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1493 Add component name as the metric prefix for opencensus exporter
  go.mod
  go.sum
  metrics/opencensus_exporter.go
  metrics/resource_view_test.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1525 Harden the drain tests more
  network/handlers/drain.go
  network/handlers/drain_test.go
Labels: approved, cla: yes, lgtm, size/L

#1529 Promised golang code streamlining
  injection/sharedmain/main.go
  metrics/metricskey/constants_test.go
  test/webhook-apicoverage/resourcetree/test_util.go
  test/webhook-apicoverage/webhook/webhook.go
  webhook/psbinding/table_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1531 Added logging of port forwarding stdout/stderr
  test/logging/logger_writer.go
  test/logging/logger_writer_test.go
  test/monitoring/monitoring.go
  test/prometheus/prometheus.go
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1527 Make the chaosduck jitter
  leaderelection/chaosduck/main.go
Labels: approved, cla: yes, lgtm, size/M

#1528 Use slow lane to do global resync
  controller/controller.go
  controller/controller_test.go
  controller/two_lane_queue.go
  webhook/certificates/certificates_test.go
  webhook/configmaps/table_test.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit_test.go
Labels: approved, cla: yes, lgtm, size/L

#1530 Another try to use hash.BucketSet for standard leader election mode
  hash/bucketer.go
  hash/bucketer_test.go
  leaderelection/context.go
  leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/L

#1534 Reorder statements for more precise behavior
  controller/two_lane_queue.go
  controller/two_lane_queue_test.go
Labels: approved, cla: yes, lgtm, size/S

#1533 Fix #1531 error with stdout/stderr pipes
  test/logging/logger_writer.go
  test/logging/logger_writer_test.go
  test/monitoring/monitoring.go
  test/prometheus/prometheus.go
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1537 Revert port forward logging
  test/monitoring/monitoring.go
  test/prometheus/prometheus.go
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1540 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1542 kube already gives us this, do not double log http
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#1545 Fix the race in the test
  leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/M

#1526 Add utilities for accessing metrics via metricproducer
  metrics/metricstest/resource_metrics.go
  metrics/metricstest/resource_metrics_test.go
  metrics/workqueue_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1544 Refactor the genreconciler code to pull state out
  apis/test/pub/v1alpha1/bar_types.go
  client/OWNERS
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/state.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/stub/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/stub/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/state.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/stub/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/stub/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/state.go
  client/injection/kube/reconciler/apps/v1/deployment/stub/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/stub/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/state.go
  client/injection/kube/reconciler/core/v1/namespace/stub/controller.go
  client/injection/kube/reconciler/core/v1/namespace/stub/reconciler.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  codegen/cmd/injection-gen/generators/reconciler_state.go
  injection/README.md
Labels: approved, cla: yes, lgtm, size/L

#1547 [master] Format markdown
  injection/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1549 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1548 [master] Fix spelling errors
  codegen/cmd/injection-gen/generators/reconciler_state.go
Labels: approved, cla: yes, lgtm, size/XS

#1550 Add pod name to the list of things we log.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1551 Add vagababov as productivity approver
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1552 Allow passing custom cmp.Options to TableTest.
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/S

#1553 Some nits in the tests in effort to fix race
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/M

#1555 Wait longer for metrics collection to settle for OpenCensus
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1556 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm64.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1557 Add a method to set possible maxidle params on the transport.
  network/prober/prober_test.go
  network/transports.go
  network/transports_test.go
Labels: approved, cla: yes, lgtm, size/M

#1558 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1559 Add helpers for float pointers.
  ptr/ptr.go
  ptr/ptr_test.go
Labels: approved, cla: yes, lgtm, size/M

#1554 Make EnsureRecorded part of metricstest
  metrics/metricstest/resource_metrics.go
  metrics/metricstest/resource_metrics_test.go
  metrics/resource_view_test.go
  metrics/workqueue_test.go
Labels: approved, cla: yes, lgtm, size/L

#1562 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1560 Remove our copy of the proxy watcher.
  apis/duck/proxy.go
  apis/duck/typed.go
  apis/duck/typed_test.go
Labels: approved, cla: yes, lgtm, size/M

#1561 Avoid copying object if TypeMeta is already correct.
  controller/helper.go
  controller/helper_test.go
Labels: approved, cla: yes, lgtm, size/M

#1565 A few optimizations in the code found by linter
  test/clients.go
  test/kube_checks.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1566 Make sure metrics tests are re-entrant
  metrics/memstats_test.go
  metrics/metricstest/metricstest.go
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/M

#1564 Add helper functions for metric tests in serving
  metrics/metricstest/resource_metrics.go
  metrics/metricstest/resource_metrics_test.go
  metrics/workqueue_test.go
Labels: approved, cla: yes, lgtm, size/L

#1567 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1569 Fix typo in the comment
  apis/contexts.go
Labels: approved, cla: yes, lgtm, size/XS

#1568 use const when gen reconciler
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/state.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/state.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/state.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/state.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_state.go
  reconciler/reconcile_common.go
  vendor/k8s.io/code-generator/generate-groups.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1571 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1573 Give table test some love it sorely misses
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/M

#1572 add a json tag to volatile_time
  apis/volatile_time.go
Labels: approved, cla: yes, lgtm, size/XS

#1574 Fix the test for go 1.15
  leaderelection/config_test.go
Labels: approved, cla: yes, lgtm, size/S
