Repository knative/pkg, pull requests merged in 2020-06, with the labels that each got.

#1367 Don't swallow errors from stackdriver init.
  metrics/stackdriver_exporter.go
Labels: approved, cla: yes, lgtm, size/S

#1347 Gcs mock
  test/gcs/client.go
  test/gcs/gcs.go
  test/gcs/helpers.go
  test/gcs/helpers_test.go
  test/gcs/mock/errors.go
  test/gcs/mock/mock.go
  test/gcs/mock/mock_example_test.go
  test/gcs/mock/mock_storage.go
  test/gcs/mock/mock_test.go
  test/gcs/mock/test/upload
  test/prow/prow.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1366 Check example-checksum label for consistency in ConfigMap webhook.
  configmap/example.go
  configmap/example_test.go
  configmap/hash-gen/main.go
  configmap/hash-gen/main_test.go
  configmap/hash-gen/testdata/add.yaml
  configmap/hash-gen/testdata/add_want.yaml
  configmap/hash-gen/testdata/nothing.yaml
  configmap/hash-gen/testdata/update.yaml
  configmap/hash-gen/testdata/update_want.yaml
  configmap/store.go
  configmap/testing/configmap.go
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
  webhook/configmaps/configmaps.go
  webhook/configmaps/configmaps_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1363 Implement Unwrap() and Is() for permanentErrors
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#1370 Junithelper refactor into a function that can be re-used.
  test/junit/junit.go
  test/junit/junit_test.go
  testutils/junithelper/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1372 Initialize conditions in preprocess
  reconciler/reconcile_common.go
  reconciler/reconcile_common_test.go
Labels: approved, cla: yes, lgtm, size/M

#1374 Use a hexadecimal representation for the example checksum.
  configmap/example.go
  configmap/example_test.go
  configmap/hash-gen/main.go
  configmap/hash-gen/testdata/add_want.yaml
  configmap/hash-gen/testdata/update_want.yaml
  configmap/testing/configmap.go
  webhook/configmaps/configmaps.go
Labels: approved, cla: yes, lgtm, size/S

#1376 [master] Fix spelling errors
  test/junit/junit_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1375 Assorted linting fixes.
  reconciler/reconcile_common_test.go
  test/gcs/gcs.go
  test/gcs/mock/mock.go
  test/gcs/mock/mock_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1377 Making mock.method public mock.Method
  test/gcs/mock/mock.go
  test/gcs/mock/mock_example_test.go
  test/gcs/mock/mock_storage.go
  test/gcs/mock/mock_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1380 Use annotation rather than label for configmap checksum
  configmap/example.go
  configmap/hash-gen/main.go
  configmap/hash-gen/testdata/add_want.yaml
  configmap/hash-gen/testdata/update.yaml
  configmap/hash-gen/testdata/update_want.yaml
  configmap/testing/configmap.go
  webhook/configmaps/configmaps.go
  webhook/configmaps/configmaps_test.go
Labels: approved, cla: yes, lgtm, size/M

#1383 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1381 Remove the trailing \n
  configmap/example.go
  configmap/example_test.go
  configmap/hash-gen/testdata/add_want.yaml
  configmap/hash-gen/testdata/update_want.yaml
Labels: approved, cla: yes, lgtm, size/S

#1386 Prevent nil access when resource is nil
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1384 Added common name to cert tmpl
  webhook/certificates/resources/certs.go
  webhook/certificates/resources/certs_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1390 [master] Auto-update dependencies
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1396 Add SendRaw to websocket client
  websocket/connection.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/S

#1369 Update release process for go.mod and add more details.
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/L

#1395 Only validate ConfigMaps the webhook knows about.
  webhook/configmaps/configmaps.go
  webhook/configmaps/configmaps_test.go
Labels: approved, cla: yes, lgtm, size/M

#1378 Update boskos dependency to sigs.k8s.io/boskos
  go.mod
  go.sum
  testutils/clustermanager/e2e-tests/boskos/boskos.go
  testutils/clustermanager/e2e-tests/boskos/fake/fake.go
  testutils/clustermanager/e2e-tests/gke_test.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/k8s.io/test-infra/boskos/client/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/common/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/storage/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/secret/agent.go
  vendor/modules.txt
  vendor/sigs.k8s.io/boskos/LICENSE
  vendor/sigs.k8s.io/boskos/client/README.md
  vendor/sigs.k8s.io/boskos/client/client.go
  vendor/sigs.k8s.io/boskos/common/common.go
  vendor/sigs.k8s.io/boskos/common/config.go
  vendor/sigs.k8s.io/boskos/common/mason_config.go
  vendor/sigs.k8s.io/boskos/storage/storage.go
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: approved, cla: yes, lgtm, size/XXL

#1393 Unexport some constants
  leaderelection/config.go
  logging/config.go
  metrics/config_observability.go
Labels: approved, cla: yes, lgtm, size/S

#1400 Add list branch function for github util package
  test/ghutil/client.go
  test/ghutil/fakeghutil/fakeghutil.go
  test/ghutil/repo.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1398 Allow hashgen to process multiple files
  configmap/hash-gen/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1406 Avoid string conversion and surface scanner error.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1404 Normalize newlines in webhook example checksum.
  configmap/example.go
  configmap/example_test.go
  configmap/hash-gen/testdata/add_want.yaml
  configmap/hash-gen/testdata/update_want.yaml
Labels: approved, cla: yes, lgtm, size/S

#1399 Allows for webhooks to exclude certain namespaces
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1413 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1410 Add a passthrough method RegisterResourceView
  metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/S

#1412 Clean metrics config tests
  metrics/config.go
  metrics/config_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1411 Make Prometheus exporter port configurable via env
  metrics/config.go
  metrics/config_test.go
Labels: approved, cla: yes, lgtm, size/L

#1385 Drop k8s.io/kube-openapi from the tools.go
  go.mod
  hack/tools.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1417 Make things private that should be so
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  metrics/exporter_test.go
  metrics/opencensus_exporter_test.go
  metrics/prometheus_exporter.go
  metrics/prometheus_exporter_test.go
  metrics/stackdriver_exporter.go
  metrics/stackdriver_exporter_test.go
  metrics/testing.go
Labels: approved, cla: yes, lgtm, size/L

#1419 Reconcile the settings with net/http
  network/transports.go
Labels: approved, cla: yes, lgtm, size/S

#1402 Always initialize conditions and set defaults when reconciling
  reconciler/reconcile_common.go
  reconciler/reconcile_common_test.go
Labels: approved, cla: yes, lgtm, size/M

#1420 Fix the logging in spoof
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1421 Update config_test.go and metricstest to support multiple Meters.
  go.mod
  go.sum
  metrics/config_test.go
  metrics/metricstest/metricstest.go
  vendor/go.opencensus.io/Makefile
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/b3/b3.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/view/export.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/trace/lrumap.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1403 Groom conditions LastTransitionTime in postprocess
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  injection/README.md
  reconciler/reconcile_common.go
  reconciler/reconcile_common_test.go
Labels: approved, cla: yes, lgtm, size/M

#1418 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1301 Implement the first wave of per-reconciler leaderelection.
  configmap/parse.go
  configmap/parse_test.go
  controller/controller.go
  controller/controller_test.go
  injection/sharedmain/main.go
  leaderelection/config.go
  leaderelection/config_test.go
  leaderelection/context.go
  leaderelection/context_test.go
  reconciler/leader.go
  reconciler/leader_test.go
  test/presubmit-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1423 Abort reconcilation on finalizer patch errors.
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1391 Use CRD & Webhook v1 APIs
  client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/fake/fake.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/stub/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/stub/reconciler.go
  client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/fake/fake.go
  client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/fake/fake.go
  client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  go.sum
  hack/update-codegen.sh
  test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/modules.txt
  webhook/admission.go
  webhook/admission_integration_test.go
  webhook/configmaps/configmaps.go
  webhook/configmaps/configmaps_test.go
  webhook/configmaps/controller.go
  webhook/configmaps/table_test.go
  webhook/conversion.go
  webhook/conversion_integration_test.go
  webhook/psbinding/controller.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/conversion/conversion.go
  webhook/resourcesemantics/conversion/conversion_test.go
  webhook/resourcesemantics/conversion/reconciler.go
  webhook/resourcesemantics/conversion/table_test.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/resourcesemantics/validation/validation_admit_test.go
  webhook/resourcesemantics/validation/validation_deprecated_test.go
  webhook/stats_reporter.go
  webhook/stats_reporter_test.go
  webhook/testing/listers.go
  webhook/testing/testing.go
  webhook/webhook.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1302 Implement the second wave of per-reconciler leaderelection
  webhook/certificates/certificates.go
  webhook/certificates/certificates_test.go
  webhook/certificates/controller.go
  webhook/configmaps/configmaps.go
  webhook/configmaps/controller.go
  webhook/configmaps/table_test.go
  webhook/psbinding/controller.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/reconciler.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/conversion/reconciler.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit_test.go
  webhook/testing/factory.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1303 Implement the third wave of per-reconciler leaderelection
  injection/sharedmain/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1425 Fix gen-reconciler stub - remove TODOs
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
Labels: approved, cla: yes, lgtm, size/XS

#1304 Implement the fourth wave of per-reconciler leaderelection
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/stub/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/stub/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/stub/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1424 adding constant for annotation
  apis/duck/register.go
Labels: approved, cla: yes, lgtm, size/XS

#1432 Add --delete option for the perf-tests tool
  testutils/clustermanager/perf-tests/main.go
  testutils/clustermanager/perf-tests/pkg/cluster.go
  testutils/clustermanager/perf-tests/pkg/cluster_test.go
Labels: approved, cla: yes, lgtm, size/L

#1433 Return TypeMeta as part of the conversion response
  webhook/conversion.go
  webhook/conversion_integration_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1409 add self to aliases and add reviewers to OWNERS
  OWNERS_ALIASES
  apis/OWNERS
  apis/duck/OWNERS
  codegen/OWNERS
  controller/OWNERS
  pool/OWNERS
  reconciler/OWNERS
  webhook/OWNERS
Labels: approved, area/API, cla: yes, lgtm, size/M

#1435 Improve manual watcher a bit
  configmap/manual_watcher.go
  configmap/manual_watcher_test.go
Labels: approved, cla: yes, lgtm, size/M

#1431 Fix gcs ListChildrenFiles and ListDirectChildren
  test/gcs/gcs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1436 fix typo
  testutils/clustermanager/prow-cluster-operation/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1430 Expect resources are krshaped by default
  codegen/cmd/injection-gen/generators/packages.go
Labels: approved, cla: yes, lgtm, size/XS

#1429 Add tracecontextb3 HTTPFormats
  test/spoof/spoof.go
  tracing/http.go
  tracing/propagation/http_format_sequence.go
  tracing/propagation/http_format_sequence_test.go
  tracing/propagation/tracecontextb3/http_format.go
  tracing/propagation/tracecontextb3/http_format_test.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1441 Ingore files under benchmark folder
  testutils/clustermanager/perf-tests/pkg/benchmark.go
  testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark
Labels: approved, cla: yes, lgtm, size/XS

#1444 Return TypeMeta as part of the admission response
  webhook/admission.go
  webhook/admission_integration_test.go
Labels: approved, cla: yes, lgtm, size/S

#1445 use apiextensions v1 apis for migrator
  apiextensions/storageversion/migrator.go
  apiextensions/storageversion/migrator_test.go
Labels: approved, cla: yes, lgtm, size/S

#1443 Assorted linting fixes.
  apis/duck/typed_test.go
  apis/field_error.go
  controller/controller_test.go
  reconciler/leader.go
  test/ghutil/fakeghutil/fakeghutil.go
  test/webhook-apicoverage/view/html_template.go
  test/webhook-apicoverage/view/xml_template.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1446 Various cleanups
  apis/condition_set.go
  apis/deprecated.go
  apis/field_error.go
  metrics/record.go
  reconciler/testing/hooks_test.go
  test/gcs/mock/mock.go
  test/interactive/docker_test.go
  tracing/config/tracing.go
  tracing/http_test.go
  webhook/resourcesemantics/defaulting/user_info_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1449 [release-0.15] Have the webhook responses return TypeMeta
  webhook/admission.go
  webhook/admission_integration_test.go
  webhook/conversion.go
  webhook/conversion_integration_test.go
Labels: approved, cla: yes, lgtm, size/S

#1438 Introduce a StatefulSet type elector builder
  leaderelection/config.go
  leaderelection/context.go
  leaderelection/context_test.go
  leaderelection/ordinal.go
  leaderelection/ordinal_test.go
Labels: approved, cla: yes, lgtm, size/L

#1442 remove krshapedlogic tag, this is default now
  apis/test/example/v1alpha1/foo_types.go
  apis/test/pub/v1alpha1/bar_types.go
  injection/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1451 Enable use of StatefulSet in sharedmain.
  injection/sharedmain/main.go
  leaderelection/config.go
  leaderelection/context.go
  leaderelection/context_test.go
  leaderelection/ordinal.go
  leaderelection/ordinal_test.go
Labels: approved, cla: yes, lgtm, size/L

#1452 Some cleanups around LE
  leaderelection/config.go
  leaderelection/context.go
  leaderelection/context_test.go
  leaderelection/ordinal.go
  leaderelection/ordinal_test.go
Labels: approved, cla: yes, lgtm, size/L

#1448 Removed zipkin hardcoded values
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1439 use coordination.Leases exclusively for leader election
  leaderelection/config.go
  leaderelection/config_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1454 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1455 bump k8s min version to 1.16.0
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/S

#1456 Add an option to skip automated status updates in a reconciler.
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  controller/options.go
Labels: approved, cla: yes, lgtm, size/M

#1458 Pin knative.dev/test-infra to release-0.16
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S
