Repository knative/pkg, pull requests merged in 2020-02, with the labels that each got.

#1032 ignore emacs tmp files
  .gitignore
Labels: approved, cla: yes, lgtm, size/XS

#1031 add SetDefaults from parent (using context), change Destination to us…
  apis/duck/v1/destination.go
  apis/duck/v1/destination_test.go
  apis/duck/v1/knative_reference.go
  apis/duck/v1/knative_reference_test.go
  apis/duck/v1/zz_generated.deepcopy.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/L

#1034 make namespace optional so existing objects keep working and we have flexibility for cluster level objects.
  apis/duck/v1/destination_test.go
  apis/duck/v1/knative_reference.go
  apis/duck/v1/knative_reference_test.go
Labels: approved, cla: yes, lgtm, size/M

#1033 Add extra flags for cluster creation in test
  test/gke/request.go
  test/gke/request_test.go
  testutils/clustermanager/e2e-tests/gke.go
  testutils/clustermanager/perf-tests/pkg/cluster.go
  testutils/clustermanager/prow-cluster-operation/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#993 Conversion Webhook Framework
  Gopkg.lock
  hack/update-codegen.sh
  injection/sharedmain/main.go
  webhook/conversion.go
  webhook/conversion_integration_test.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/conversion/conversion.go
  webhook/resourcesemantics/conversion/conversion_test.go
  webhook/resourcesemantics/conversion/internal/types.go
  webhook/resourcesemantics/conversion/internal/zz_generated.deepcopy.go
  webhook/resourcesemantics/conversion/reconciler.go
  webhook/resourcesemantics/conversion/table_test.go
  webhook/testing/factory.go
  webhook/testing/listers.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1037 Update OWNERS of the webhook package
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1039 Rename KnativeReference to KReference
  apis/duck/v1/destination.go
  apis/duck/v1/destination_test.go
  apis/duck/v1/knative_reference.go
  apis/duck/v1/knative_reference_test.go
  apis/duck/v1/zz_generated.deepcopy.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/M

#1029 Use new RecordBatch method to join metric reporting
  controller/stats_reporter.go
  webhook/stats_reporter.go
Labels: approved, cla: yes, lgtm, size/S

#1040 Some nit cleanups in the tests mostly, but also code :)
  apis/duck/v1/destination_test.go
  apis/duck/v1/knative_reference.go
  apis/duck/v1/knative_reference_test.go
Labels: approved, cla: yes, lgtm, size/L

#1041 Make sure we actually check the last value.
  metrics/metricstest/metricstest.go
Labels: approved, cla: yes, lgtm, size/S

#1035 Fix TestInformedWatcher sporadically failing on testgrid
  configmap/informed_watcher_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1042 golang format tools
  metrics/record_test.go
Labels: approved, cla: yes, lgtm, size/XS

#947 Generate Base Reconciler Code for Injection Based Controllers.
  Gopkg.lock
  codegen/cmd/injection-gen/args/args.go
  codegen/cmd/injection-gen/generators/client.go
  codegen/cmd/injection-gen/generators/fakeclient.go
  codegen/cmd/injection-gen/generators/fakeduck.go
  codegen/cmd/injection-gen/generators/fakefactory.go
  codegen/cmd/injection-gen/generators/fakeinformer.go
  codegen/cmd/injection-gen/generators/namesystems.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  hack/generate-knative.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1049 BugFix: Returning errors and adding scheme.
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#1051 golang format tools
  codegen/cmd/injection-gen/generators/reconciler_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#1052 check KReference namespace matches parent. Allow escape hatch.
  apis/contexts.go
  apis/contexts_test.go
  apis/duck/v1/destination.go
  apis/duck/v1/knative_reference.go
  apis/duck/v1/knative_reference_test.go
Labels: approved, cla: yes, lgtm, size/M

#1054 adding matt and scott to owners for codegen
  OWNERS_ALIASES
  codegen/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1053 [Gen Reconciler] Fix issue found with controllers without reconciler.Base
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#1050 Add support for KUBECONFIG env var in the tests
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1055 No reason to get parent NS if we're not gonna use it.
  apis/duck/v1/knative_reference.go
Labels: approved, cla: yes, lgtm, size/XS

#1058 Fix the go version tag
  test/mako/sidecar.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1059 add vagababov as approver to the mako directory
  test/mako/OWNERS
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1056 golang format tools
  codegen/cmd/injection-gen/generators/reconciler_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#1062 Fix defaulting bug in the converter for empty addressables.
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/addressable_types_test.go
  apis/duck/v1beta1/addressable_types_test.go
Labels: approved, cla: yes, lgtm, size/S

#1063 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#1064 Fix a upconvert with empty url
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/addressable_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#1068 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#1070 bump the minimum version to 1.15.1
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1069 Generate Managed Finalizers for Reconcilers
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
Labels: approved, cla: yes, lgtm, size/L

#1071 fix filtering for reconcilers gen.
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
Labels: approved, cla: yes, lgtm, size/M

#1067 Handle wrong apiVersion/kind in SinkBinding subject
  webhook/psbinding/reconciler.go
  webhook/psbinding/table_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1072 golang format tools
  codegen/cmd/injection-gen/generators/reconciler_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#1075 set the import for sets
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#1073 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1066 Document genreconciler.
  injection/README.md
Labels: approved, cla: yes, lgtm, size/L

#1083 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1078 Update jsonpatch lib that correctly handle object removal
  Gopkg.lock
  apis/duck/patch.go
  apis/duck/patch_test.go
  vendor/gomodules.xyz/jsonpatch/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  webhook/admission_integration_test.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/testing/testing.go
Labels: approved, cla: yes, lgtm, size/L

#1080 allow filtering on schema.GroupKind
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#1085 [Reconciler Generators] Adding support for configStore.ToContext
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  controller/options.go
  injection/README.md
  reconciler/configstore.go
Labels: approved, cla: yes, lgtm, size/L

#1086 [GenRec] Keep resource in sync when setting and removing finalizers.
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#1087 golang format tools
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
Labels: approved, cla: yes, lgtm, size/XS

#1089 I screwed up the return for clearFinalizer.
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1090 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#862 Avoid callback calls while lock is held.
  tracker/enqueue.go
Labels: approved, cla: yes, lgtm, size/S

#1092 Add a new tester for distribution
  metrics/metricstest/metricstest.go
Labels: approved, cla: yes, lgtm, size/S

#1094 Updating comment on Destination
  apis/duck/v1/source_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1095 Default occupy Boskos for long enough time so we don't need to do hea…
  testutils/clustermanager/e2e-tests/boskos/boskos.go
Labels: approved, cla: yes, lgtm, size/XS

#1093 Upstreaming Serving filter functions
  reconciler/filter.go
  reconciler/filter_test.go
  reconciler/retry.go
  reconciler/retry_test.go
Labels: approved, cla: yes, lgtm, size/L

#1096 adding recorder to context.
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1074 Modify TestLogger util function to support for Benchmark testing
  logging/testing/util.go
Labels: approved, cla: yes, lgtm, size/XS

#1100 Updating README for genreconciler
  injection/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1099 golang format tools
  reconciler/filter_test.go
  testutils/clustermanager/e2e-tests/boskos/boskos.go
Labels: approved, cla: yes, lgtm, size/XS

#1102 golang format tools
  logging/testing/util.go
Labels: approved, cla: yes, lgtm, size/XS

#1045 Add support for client TLS to pkg/metrics
  Gopkg.lock
  injection/sharedmain/main.go
  metrics/README.md
  metrics/config.go
  metrics/exporter.go
  metrics/opencensus_exporter.go
  metrics/opencensus_exporter_test.go
  metrics/testdata/README.md
  metrics/testdata/client-cert.pem
  metrics/testdata/client-key.pem
  metrics/testdata/server-cert.pem
  metrics/testdata/server-key.pem
Labels: approved, cla: yes, lgtm, size/L

#1097 [Genreconciler] Fix group names when client groups differ than their directory name.
  .gitignore
  Gopkg.lock
  apis/test/example/register.go
  apis/test/example/v1alpha1/doc.go
  apis/test/example/v1alpha1/foo_types.go
  apis/test/example/v1alpha1/register.go
  apis/test/example/v1alpha1/zz_generated.deepcopy.go
  apis/test/pub/register.go
  apis/test/pub/v1alpha1/bar_types.go
  apis/test/pub/v1alpha1/doc.go
  apis/test/pub/v1alpha1/register.go
  apis/test/pub/v1alpha1/zz_generated.deepcopy.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  hack/update-codegen.sh
  injection/README.md
  test/presubmit-tests.sh
  test/update-test-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1106 Revert #1045, causes sharedmain to need global secrets list
  Gopkg.lock
  injection/sharedmain/main.go
  metrics/README.md
  metrics/config.go
  metrics/exporter.go
  metrics/opencensus_exporter.go
  metrics/opencensus_exporter_test.go
  metrics/testdata/README.md
  metrics/testdata/client-cert.pem
  metrics/testdata/client-key.pem
  metrics/testdata/server-cert.pem
  metrics/testdata/server-key.pem
Labels: approved, cla: yes, lgtm, size/L

#1103 Implement strongly typed class reconcilers
  apis/test/pub/v1alpha1/bar_types.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  injection/README.md
Labels: approved, cla: yes, lgtm, size/L

#1022 Backend for improving test logging
  Gopkg.lock
  Gopkg.toml
  test/e2e_flags.go
  test/e2e_flags_test.go
  test/logging/.gitattributes
  test/logging/doc.go
  test/logging/error.go
  test/logging/example_tlogger_test.go
  test/logging/logger.go
  test/logging/logging.go
  test/logging/logging_test.go
  test/logging/memory_encoder.go
  test/logging/spew_encoder.go
  test/logging/spew_encoder_test.go
  test/logging/sugar.go
  test/logging/tlogger.go
  test/logging/zapr.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/zapr/LICENSE
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/k8s.io/klog/klog.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1108 Clear unhappy propagation status of the top level condition if cleared.
  apis/condition_set.go
  apis/condition_set_impl_test.go
Labels: approved, cla: yes, lgtm, size/M

#1110 Realized a corner case on ordering and False > Unknown states.
  apis/condition_set.go
  apis/condition_set_impl_test.go
Labels: approved, cla: yes, lgtm, size/L

#1112 Nil check conditions
  apis/condition_set.go
  apis/condition_set_impl_test.go
  apis/condition_types.go
  apis/condition_types_test.go
  apis/duck/v1alpha1/condition_set.go
  apis/duck/v1alpha1/condition_set_impl_test.go
  apis/duck/v1alpha1/condition_set_test.go
  apis/duck/v1alpha1/condition_type_test.go
  apis/duck/v1alpha1/conditions_types.go
  apis/duck/v1alpha1/implements_test.go
  apis/duck/v1alpha1/register.go
  apis/duck/v1alpha1/register_test.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
  client/injection/ducks/duck/v1alpha1/conditions/conditions.go
  client/injection/ducks/duck/v1alpha1/conditions/fake/fake.go
Labels: approved, cla: yes, lgtm, size/XXL

#1084 Introduce sharedmain.WebhookMain*
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/L

#1114 Drops the Serving-specific stats reporter logic from knative/pkg
  reconciler/testing/stats.go
  reconciler/testing/table.go
  webhook/testing/factory.go
Labels: approved, cla: yes, lgtm, size/M

#1101 Renews a webhook cert before it expires
  test/webhook-apicoverage/webhook/webhook.go
  webhook/certificates/certificates.go
  webhook/certificates/certificates_test.go
  webhook/certificates/resources/certs.go
  webhook/certificates/resources/certs_test.go
  webhook/certificates/resources/secret.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#1121 Delete ./test/testgenclient after presubmit is finished.
  Gopkg.lock
  test/presubmit-tests.sh
  test/test-reconciler-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1120 Use interfaces when testing conditions so we don't need versioned methods
  apis/condition_set.go
  apis/testing/conditions.go
  apis/testing/v1/conditions.go
  apis/testing/v1beta1/conditions.go
Labels: approved, cla: yes, lgtm, size/L

#1122 Fixed #1057 - Rename ConvertUp/Down to ConvertTo/From
  apis/convert.go
  apis/convert_test.go
  apis/duck/v1/addressable_types.go
  apis/duck/v1/addressable_types_test.go
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/addressable_types_test.go
  apis/duck/v1beta1/addressable_types.go
  apis/duck/v1beta1/addressable_types_test.go
  apis/interfaces.go
  apis/testing/roundtrip/roundtrip.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/conversion/conversion.go
  webhook/resourcesemantics/conversion/conversion_test.go
  webhook/resourcesemantics/conversion/internal/types.go
Labels: approved, cla: yes, lgtm, size/L

#1123 Add an option to specify the selector for psbinding webhook.
  webhook/psbinding/contexts.go
  webhook/psbinding/contexts_test.go
  webhook/psbinding/controller.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/table_test.go
Labels: approved, cla: yes, lgtm, size/L

#1118 Pass verbosity level on to klog
  test/logging/logging.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1124 Fix the nits leftover from #1118 review
  test/logging/logging.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1125 Add an option to specify the selector for psbinding webhook.
  webhook/psbinding/contexts.go
  webhook/psbinding/contexts_test.go
  webhook/psbinding/controller.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/table_test.go
Labels: approved, cla: yes, lgtm, size/L

#1126 Move map functions to PKG
  kmeta/map.go
  kmeta/map_test.go
Labels: approved, cla: yes, lgtm, size/L

#1127 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1109 Roll forward #1045
  Gopkg.lock
  injection/sharedmain/main.go
  metrics/README.md
  metrics/config.go
  metrics/exporter.go
  metrics/opencensus_exporter.go
  metrics/opencensus_exporter_test.go
  metrics/testdata/README.md
  metrics/testdata/client-cert.pem
  metrics/testdata/client-key.pem
  metrics/testdata/server-cert.pem
  metrics/testdata/server-key.pem
Labels: approved, cla: yes, lgtm, size/L

#1128 Format markdown
  metrics/README.md
  metrics/testdata/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1019 add leader election support to sharedmain
  Gopkg.lock
  injection/sharedmain/main.go
  leaderelection/config.go
  leaderelection/config_test.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1132 release-0.13: add leader election support to sharedmain (#1019)
  Gopkg.lock
  injection/sharedmain/main.go
  leaderelection/config.go
  leaderelection/config_test.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
Labels: approved, cla: yes, lgtm, size/XXL

#1135 Add standard pod and container name keys
  metrics/metricskey/constants.go
Labels: approved, cla: yes, lgtm, size/XS
