Repository knative/pkg, pull requests merged in 2020-10, with the labels that each got.

#1758 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1763 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1766 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1765 Add IsWithinParent
  apis/contexts.go
  apis/contexts_test.go
Labels: approved, cla: yes, lgtm, size/S

#1767 Delay start of informers in sharedmain
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#1769 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1741 Add TTL expiry for items in allMeters.meters map
  metrics/resource_view.go
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/L

#1776 Apply the cleanup to the pkg
  apiextensions/storageversion/cmd/migrate/main.go
  apis/field_error.go
  apis/field_error_test.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/main.go
  injection/sharedmain/main.go
  leaderelection/chaosduck/main.go
  metrics/prometheus_exporter.go
  profiling/server.go
  test/helpers/dryrun.go
  test/interactive/docker.go
  test/kube_checks.go
  test/mako/config/benchmark.go
  test/mako/config/environment.go
  test/mako/sidecar.go
  testutils/clustermanager/e2e-tests/example_test.go
  testutils/clustermanager/e2e-tests/util.go
  testutils/clustermanager/perf-tests/main.go
  testutils/metahelper/main.go
  webhook/admission_integration_test.go
  webhook/resourcesemantics/conversion/internal/types.go
  webhook/webhook.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1760 Explicitly exclude cutting release for client repo in the release instruction
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/XS

#1774 move binding duck to v1
  apis/duck/v1/binding_types.go
  apis/duck/v1/register.go
  apis/duck/v1/zz_generated.deepcopy.go
  client/injection/ducks/duck/v1/binding/binding.go
  client/injection/ducks/duck/v1/binding/fake/fake.go
Labels: approved, cla: yes, lgtm, size/M

#1780 Include REST and reorder items to be sorted
  test/helpers/name.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1772 Put EnableInjectionOrDie back on the main path
  injection/config.go
  injection/injection.go
  injection/sharedmain/main.go
  leaderelection/chaosduck/main.go
Labels: approved, cla: yes, lgtm, size/L

#1784 add codecov badge
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1770 add fuzzers
  apis/duck/v1/fuzzer.go
  apis/duck/v1/roundtrip_test.go
  apis/duck/v1alpha1/roundtrip_test.go
  apis/duck/v1beta1/fuzzer.go
  apis/duck/v1beta1/roundtrip_test.go
Labels: approved, cla: yes, lgtm, size/L

#1781 Scott to owners on pkg
  .codecov.yaml
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1778 Allow override QPS and Burst via flag
  injection/config.go
Labels: approved, cla: yes, lgtm, size/S

#1783 Enable golint and exclude some other generated or additional dirs
  .golangci.yaml
  controller/controller.go
  hash/hash.go
  kvstore/kvstore_cm_test.go
  logging/config.go
  metrics/config.go
  metrics/stackdriver_exporter.go
  reconciler/events.go
  reconciler/retry_test.go
  test/gcs/gcs.go
  test/gcs/mock/errors.go
  test/gcs/mock/mock.go
  test/gcs/mock/mock_example_test.go
  test/gcs/mock/mock_test.go
  test/logging/error.go
  test/logging/tlogger.go
  test/mako/analyzer.go
  test/mako/config/benchmark.go
  test/mako/stub-sidecar/main.go
  testutils/clustermanager/e2e-tests/boskos/fake/fake.go
  testutils/clustermanager/e2e-tests/gke_test.go
  testutils/clustermanager/perf-tests/pkg/cluster.go
  testutils/clustermanager/perf-tests/pkg/cluster_test.go
  tracing/config/tracing.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/resourcesemantics/validation/validation_admit_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1787 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#1771 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1789 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1790 BucketList cleanup
  hash/bucketer.go
  hash/bucketer_test.go
  leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/S

#1794 Final sync/atomic removals
  pool/pool_test.go
Labels: approved, area/API, cla: yes, lgtm, size/S

#1795 feat: get cluster domain use utility
  webhook/certificates/resources/certs.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1798 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/mako/go/quickstore/BUILD
  vendor/github.com/google/mako/internal/go/common/BUILD
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/secret/BUILD.bazel
  vendor/k8s.io/test-infra/prow/logrusutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/version/BUILD.bazel
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1793 logstream v2
  test/logstream/interface.go
  test/logstream/v2/interface.go
  test/logstream/v2/stream.go
  test/logstream/v2/stream_test.go
  vendor/k8s.io/client-go/rest/fake/fake.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1799 Step I: move memstats to metrics
  injection/sharedmain/main.go
  metrics/memstats.go
Labels: approved, cla: yes, lgtm, size/S

#1801 Use default no-op logger for maxprocs
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1802 Updating to later test-infra
  go.mod
  go.sum
  vendor/github.com/alecthomas/units/bytes.go
  vendor/github.com/alecthomas/units/go.mod
  vendor/github.com/alecthomas/units/go.sum
  vendor/github.com/alecthomas/units/si.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1808 use k8s.interface
  injection/sharedmain/main.go
  metrics/stackdriver_exporter.go
  test/clients.go
  test/ha/ha.go
  test/ingress/ingress.go
  test/kube_checks.go
  test/logstream/interface.go
  test/monitoring/doc.go
  test/monitoring/monitoring.go
  test/prometheus/prometheus.go
  test/spoof/spoof.go
  test/zipkin/doc.go
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1806 Add EnableProbeReqLogKey constant
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, size/S

#1807 Port tracing setup code to pkg
  configmap/store.go
  tracing/config/tracing.go
  tracing/config/tracing_test.go
  tracing/setup.go
Labels: approved, cla: yes, lgtm, size/M

#1812 Add suggested fix when checksums dont match
  configmap/testing/configmap.go
Labels: approved, cla: yes, lgtm, size/XS

#1811 Update vegeta to a version supporting go modules
  go.mod
  go.sum
  test/vegeta/pacers/combined_pacer.go
  test/vegeta/pacers/combined_pacer_test.go
  test/vegeta/pacers/steady_up_pacer.go
  test/vegeta/pacers/steady_up_pacer_test.go
  third_party/VENDOR-LICENSE/github.com/tsenart/vegeta/v12/lib/LICENSE
  vendor/github.com/mailru/easyjson/.gitignore
  vendor/github.com/mailru/easyjson/.travis.yml
  vendor/github.com/mailru/easyjson/Makefile
  vendor/github.com/mailru/easyjson/README.md
  vendor/github.com/mailru/easyjson/go.mod
  vendor/github.com/mailru/easyjson/helpers.go
  vendor/github.com/mailru/easyjson/raw.go
  vendor/github.com/tsenart/vegeta/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/LICENSE
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/github.com/tsenart/vegeta/v12/lib/attack_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/histogram.go
  vendor/github.com/tsenart/vegeta/v12/lib/metrics.go
  vendor/github.com/tsenart/vegeta/v12/lib/pacer.go
  vendor/github.com/tsenart/vegeta/v12/lib/reporters.go
  vendor/github.com/tsenart/vegeta/v12/lib/results.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/target.schema.json
  vendor/github.com/tsenart/vegeta/v12/lib/targets.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/util_fuzz.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1809 test all downstreams.
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/L

#1804 drop the default log url template
  metrics/config_observability.go
Labels: approved, cla: yes, lgtm, size/XS

#1814 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1797 Spelling
  apis/duck/README.md
  apis/duck/verify_test.go
  apis/field_error.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  controller/controller.go
  controller/two_lane_queue.go
  hash/doc.go
  hash/hash_test.go
  injection/sharedmain/main.go
  kmeta/ownerrefable_accessor.go
  kmeta/ownerrefable_accessor_test.go
  leaderelection/context.go
  logging/config.go
  metrics/exporter.go
  metrics/exporter_test.go
  metrics/metricstest/resource_metrics.go
  network/network.go
  reconciler/testing/generate_name_reactor_test.go
  source/source_labels_test.go
  test/gcs/gcs.go
  test/gcs/mock/mock.go
  test/mako/alerter/github/issue.go
  test/mako/config/configmap.go
  test/mako/sidecar.go
  test/mako/stub-sidecar/main.go
  test/monitoring/doc.go
  test/spoof/spoof.go
  test/tinterface.go
  testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark4/noop.yaml
  tracing/opencensus.go
  tracker/enqueue_test.go
  webhook/admission_integration_test.go
  webhook/psbinding/reconciler.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/resourcesemantics/validation/validation_admit_test.go
  webhook/stats_reporter.go
  webhook/webhook.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#1815 Simplify test helpers for prometheus API
  test/prometheus/prometheus_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1816 Remove unnecessary override for dependencies
  go.mod
  go.sum
  test/prometheus/prometheus.go
  test/prometheus/prometheus_test.go
  third_party/VENDOR-LICENSE/github.com/cespare/xxhash/v2/LICENSE.txt
  vendor/github.com/alecthomas/units/bytes.go
  vendor/github.com/alecthomas/units/go.mod
  vendor/github.com/alecthomas/units/go.sum
  vendor/github.com/alecthomas/units/si.go
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/LICENSE.txt
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/client_golang/prometheus/build_info.go
  vendor/github.com/prometheus/client_golang/prometheus/build_info_pre_1.12.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_windows.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1819 Wait for prometheus server to start serving before fetching metrics
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/S

#1818 Make sure all controllers finish before ending test
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#1817 Get rid of the interface
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/S

#1820 Remove re-definition of kubeconfig from pkg/test
  apis/testing/conditions.go
  injection/config.go
  metrics/metricstest/metricstest.go
  test/clients.go
  test/e2e_flags.go
  test/flags/e2e_flags.go
  test/logstream/interface.go
  test/logstream/null.go
  test/request.go
  test/tinterface.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1821 Various stuff around the logstream
  test/logstream/v2/stream.go
  test/logstream/v2/stream_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1822 Simplify defaulting and force-default kubeconfig location in tests
  injection/config.go
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1824 Harden logstream test, make it quicker and repeatable
  test/logstream/v2/stream_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1825 use kubernetes.Interface for some test helpers
  test/clients.go
  test/request.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1823 Fix nolint warnings and adhere to best practices
  configmap/hash-gen/main.go
  controller/controller.go
  kmeta/names.go
  metrics/config.go
  reconciler/events.go
  test/gcs/gcs.go
  test/logging/example_tlogger_test.go
  test/logging/tlogger.go
  test/mako/config/benchmark.go
  test/mako/stub-sidecar/main.go
  testutils/clustermanager/perf-tests/pkg/benchmark.go
  tracing/config/tracing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1826 More test coverage for logstream
  test/logstream/v2/stream.go
  test/logstream/v2/stream_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1828 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1830 Improve readability with backtics
  test/gcs/helpers_test.go
  test/upgrade/asserts_test.go
  testutils/clustermanager/e2e-tests/boskos/boskos_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1832 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1834 Some cleanups arounds the metrics code
  metrics/config.go
  metrics/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1838 Cherry-pick informer fix
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#1837 Fix API stutter in metric option functions
  metrics/config.go
  metrics/config_test.go
Labels: approved, cla: yes, lgtm, size/S

#1836 Remove NamespacedName logging helper
  logging/object_encoders.go
Labels: approved, cla: yes, lgtm, size/S

#1833 Restrict defaulting and validation webhook to resource and resource/status
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
Labels: approved, cla: yes, lgtm, size/S

#1839 Fix the error/warn log usage
  webhook/certificates/certificates.go
  webhook/configmaps/configmaps.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/reconciler.go
  webhook/resourcesemantics/conversion/conversion.go
  webhook/resourcesemantics/conversion/reconciler.go
  webhook/resourcesemantics/defaulting/defaulting.go
Labels: approved, cla: yes, lgtm, size/S

#1841 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1842 [0.17] Backport 1687
  webhook/resourcesemantics/conversion/conversion.go
Labels: approved, cla: yes, lgtm, size/XS

#1843 Fix produced events if patching a finalizer fails
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1840 Support short suffix in zipkin config
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1844 Use the network.GetServiceHostname helper
  resolver/addressable_resolver.go
Labels: approved, cla: yes, lgtm, size/XS

#1845 [RELEASE-0.18] Fix produced events if patching a finalizer fails (#1843)
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1846 Eventing no longer needs this constant
  leaderelection/config.go
  leaderelection/context.go
Labels: approved, cla: yes, lgtm, size/XS

#1847 Remove deprecated methods now that downstream has been updated
  metrics/config.go
Labels: approved, cla: yes, lgtm, size/S

#1848 Add proper cased function to deprecate the old one
  logging/config.go
  logging/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1849 Final Json -> JSON process
  apis/url_test.go
  tracing/config/tracing.go
  tracing/config/tracing_test.go
Labels: approved, cla: yes, lgtm, size/L

#1850 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1852 move fuzzers
  apis/duck/v1/test/fuzzer.go
  apis/duck/v1/test/roundtrip_test.go
  apis/duck/v1beta1/test/fuzzer.go
  apis/duck/v1beta1/test/roundtrip_test.go
Labels: approved, cla: yes, lgtm, size/S

#1803 Update release schedule by moving 2 weeks for end of year holidays
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/S

#1853 Add a test package for making assertions about dependencies.
  depcheck/depcheck.go
  depcheck/depcheck_test.go
  go.mod
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1856 Downstream is updated, to remove outdated methods
  logging/config.go
  tracing/config/tracing.go
Labels: approved, cla: yes, lgtm, size/S

#1858 use new hack repo
  go.mod
  go.sum
  hack/tools.go
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
  test/test-reconciler-codegen.sh
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/hack/LICENSE
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/hack/shellcheck-presubmit.sh
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1860 Add a list of known-heavy things, check a few places.
  apis/depcheck_test.go
  depcheck/heavy.go
  logging/depcheck_test.go
  network/depcheck_test.go
Labels: approved, cla: yes, lgtm, size/L

#1859 Add AssertOnlyDeps variant
  depcheck/depcheck.go
  depcheck/depcheck_test.go
Labels: approved, cla: yes, lgtm, size/M

#1861 Add check variants that return errors for more extensive testing.
  depcheck/depcheck.go
  depcheck/depcheck_test.go
Labels: approved, cla: yes, lgtm, size/M

#1862 [Automated] Format markdown
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1864 race was fixed in k8s 1.18
  leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1865 Fix nits in depchecker
  depcheck/depcheck.go
  depcheck/depcheck_test.go
Labels: approved, cla: yes, lgtm, size/S

#1727 Upgrade to semver v4
  go.mod
  go.sum
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/v4/LICENSE
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/blang/semver/v4/json.go
  vendor/github.com/blang/semver/v4/range.go
  vendor/github.com/blang/semver/v4/semver.go
  vendor/github.com/blang/semver/v4/sort.go
  vendor/github.com/blang/semver/v4/sql.go
  vendor/modules.txt
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#1868 Use the correct module import for 'gopkg.in/evanphx/json-patch.v4'
  apis/duck/patch.go
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blang/semver/v4/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/gopkg.in/evanphx/json-patch.v4/errors.go
  vendor/gopkg.in/evanphx/json-patch.v4/merge.go
  vendor/gopkg.in/evanphx/json-patch.v4/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1857 Return context.Canceled error in pkg/signals
  signals/signal.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1777 configmap parse int
  configmap/parse.go
  configmap/parse_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1870 Skip flaky OpenCensus exporter test until fixed
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1863 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1871 use the default unit test runner
  test/presubmit-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1874 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1873 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1855 Add errorlint and fix all existing issues
  .golangci.yaml
  apis/duck/enqueue_test.go
  apis/duck/typed_test.go
  apis/duck/unstructured_test.go
  apis/duck/verify.go
  configmap/store_test.go
  controller/controller.go
  depcheck/depcheck.go
  injection/sharedmain/main.go
  kvstore/kvstore_cm.go
  logging/config.go
  metrics/opencensus_exporter.go
  metrics/resource_view_test.go
  metrics/stackdriver_exporter.go
  network/prober/prober_test.go
  network/transports.go
  pool/pool_test.go
  reconciler/events.go
  reconciler/retry_test.go
  test/cmd/command.go
  test/cmd/command_test.go
  test/gcs/gcs.go
  test/gcs/mock/mock_test.go
  test/ghutil/client.go
  test/gke/client.go
  test/interactive/docker.go
  test/logging/logging_test.go
  test/mako/config/benchmark.go
  test/mako/stub-sidecar/main.go
  test/spoof/error_checks.go
  test/spoof/spoof.go
  testutils/clustermanager/e2e-tests/common/common.go
  testutils/clustermanager/e2e-tests/common/common_test.go
  testutils/clustermanager/e2e-tests/gke.go
  testutils/clustermanager/e2e-tests/util.go
  testutils/clustermanager/prow-cluster-operation/actions/create.go
  testutils/clustermanager/prow-cluster-operation/actions/delete.go
  tracing/opencensus_test.go
  webhook/webhook.go
  websocket/connection_test.go
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#1373 Throw the exception of loggingconfig
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, lifecycle/stale, needs-ok-to-test, size/XS

#1877 Fix issue 1876
  reconciler/testing/reactions.go
  reconciler/testing/reactions_test.go
Labels: approved, cla: yes, lgtm, size/L

#1878 Nits in the test
  reconciler/testing/reactions_test.go
Labels: approved, cla: yes, lgtm, size/M
