Repository knative/pkg, pull requests merged in 2020-01, with the labels that each got.

#968 Added GKE release channel support in cluster creation in cluster manager lib
  Gopkg.lock
  test/gke/request.go
  test/gke/request_test.go
  testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/google.golang.org/api/AUTHORS
  vendor/google.golang.org/api/CONTRIBUTORS
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/google.golang.org/api/gensupport/backoff.go
  vendor/google.golang.org/api/gensupport/header.go
  vendor/google.golang.org/api/gensupport/retry.go
  vendor/google.golang.org/api/googleapi/googleapi.go
  vendor/google.golang.org/api/googleapi/internal/uritemplates/LICENSE
  vendor/google.golang.org/api/googleapi/transport/apikey.go
  vendor/google.golang.org/api/googleapi/types.go
  vendor/google.golang.org/api/internal/creds.go
  vendor/google.golang.org/api/internal/gensupport/buffer.go
  vendor/google.golang.org/api/internal/gensupport/doc.go
  vendor/google.golang.org/api/internal/gensupport/json.go
  vendor/google.golang.org/api/internal/gensupport/jsonfloat.go
  vendor/google.golang.org/api/internal/gensupport/media.go
  vendor/google.golang.org/api/internal/gensupport/params.go
  vendor/google.golang.org/api/internal/gensupport/resumable.go
  vendor/google.golang.org/api/internal/gensupport/send.go
  vendor/google.golang.org/api/internal/pool.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/third_party/uritemplates/LICENSE
  vendor/google.golang.org/api/internal/third_party/uritemplates/uritemplates.go
  vendor/google.golang.org/api/internal/third_party/uritemplates/utils.go
  vendor/google.golang.org/api/iterator/iterator.go
  vendor/google.golang.org/api/option/credentials_go19.go
  vendor/google.golang.org/api/option/credentials_notgo19.go
  vendor/google.golang.org/api/option/option.go
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/support/bundler/bundler.go
  vendor/google.golang.org/api/transport/dial.go
  vendor/google.golang.org/api/transport/doc.go
  vendor/google.golang.org/api/transport/go19.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/grpc/dial_appengine.go
  vendor/google.golang.org/api/transport/grpc/dial_socketopt.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/api/transport/http/dial_appengine.go
  vendor/google.golang.org/api/transport/http/internal/propagation/http.go
  vendor/google.golang.org/api/transport/not_go19.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#974 Fix sharedmain log messages format
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#965 Add helper methods in conditon_set
  apis/condition_set.go
Labels: approved, cla: yes, lgtm, size/S

#971 bump the default minimum version to 1.15
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/S

#975 Return GKECluster info in PCO
  testutils/clustermanager/prow-cluster-operation/actions/create.go
  testutils/clustermanager/prow-cluster-operation/actions/get.go
  testutils/clustermanager/prow-cluster-operation/main.go
Labels: approved, cla: yes, lgtm, size/S

#944 Adding back Broker Metrics
  metrics/config.go
Labels: approved, cla: yes, lgtm, size/XS

#976 Add metrics for Knative Certificate creation count
  metrics/metricskey/constants_serving.go
Labels: approved, cla: yes, lgtm, size/XS

#970 add ability to opt-out of bindings
  apis/duck/const.go
  webhook/psbinding/contexts.go
  webhook/psbinding/contexts_test.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/table_test.go
Labels: approved, cla: yes, lgtm, size/L

#952 Creating an Event interface and ReconcilerEvent type to be used in ReconcileKind
  reconciler/events.go
  reconciler/events_test.go
Labels: approved, cla: yes, lgtm, size/L

#953 Document the plan for metrics
  metrics/README.md
Labels: approved, cla: yes, lgtm, size/L

#981 Format markdown
  metrics/README.md
Labels: approved, cla: yes, lgtm, size/XS

#980 Optimize locking behavior of the profiling handler.
  profiling/server.go
  profiling/server_test.go
Labels: approved, cla: yes, lgtm, size/M

#983 Add chizhg as productivity-approvers in pkg
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#984 Add WithPath option to set the probe path.
  network/prober/prober.go
  network/prober/prober_test.go
Labels: approved, cla: yes, lgtm, size/M

#986 Clean up other test to use suggestions of #984
  network/prober/prober_test.go
Labels: approved, cla: yes, lgtm, size/S

#696 Ban importing aliased domains.
  test/imports/banned_deps_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#987 Provide an semantic equality func for apis.URL
  apis/url.go
Labels: approved, cla: yes, lgtm, size/S

#982 perf-tests cluster manager supports creating clusters in other environment
  test/gke/endpoint.go
  test/gke/endpoint_test.go
  testutils/clustermanager/perf-tests/main.go
  testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#978 Add support for OpenCensus Agent as a destination for Knative metrics.
  Gopkg.lock
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  metrics/opencensus_exporter.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/LICENSE
  vendor/contrib.go.opencensus.io/exporter/ocagent/common.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/connection.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/nodeinfo.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_spans.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/version.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1/metrics_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.gw.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace.pb.go
  vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1/trace_config.pb.go
  vendor/github.com/golang/protobuf/descriptor/descriptor.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_json.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler_registry.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto2_convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/trie.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
Labels: approved, cla: yes, lgtm, size/XXL

#988 unit test to ensure semantic equality func is registered for apis.URL
  apis/url_test.go
Labels: approved, cla: yes, lgtm, size/S

#973 Filter tracked sharedmain ConfigMaps based on optional label selector
  Gopkg.lock
  configmap/informed_watcher.go
  configmap/informed_watcher_test.go
  configmap/manual_watcher.go
  injection/sharedmain/main.go
  system/env.go
Labels: approved, cla: yes, lgtm, size/L

#990 golang format tools
  metrics/config_test.go
  test/gke/endpoint.go
  test/gke/endpoint_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#991 Update the deps for repos the pkg release process.
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/XS

#994 Add default metrics backend to observability config
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, size/XS

#992 Fix several mishandled errors.Wrap conversions.
  test/webhook-apicoverage/tools/tools.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#995 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#926 Add a junithelper for creating a junit result from command
  test/junit/junit.go
  testutils/junithelper/README.md
  testutils/junithelper/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#989 Refactor webhook to allow adding conversion support
  webhook/admission.go
  webhook/admission_integration_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
Labels: approved, cla: yes, lgtm, size/XL

#997 Format markdown
  testutils/junithelper/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1002 add helpers to convert objects through Convertible proxies
  apis/convert.go
  apis/convert_test.go
Labels: approved, cla: yes, lgtm, size/L

#1003 status.ConvertTo can optionally accept predicates
  apis/duck/v1/status_types.go
  apis/duck/v1/status_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#1004 Only intercept types that appear in Bindings.
  webhook/psbinding/psbinding.go
  webhook/psbinding/table_test.go
Labels: approved, cla: yes, lgtm, size/L

#1006 Allow to specify default exporter option when updating from ConfigMap
  metrics/config_test.go
  metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/M

#1009 conditions were being duplicated since we broke vs. continuing
  apis/duck/v1/status_types.go
  apis/duck/v1/status_types_test.go
Labels: approved, cla: yes, lgtm, size/S

#1008 add retry func for reconciler
  Gopkg.lock
  reconciler/retry.go
  reconciler/retry_test.go
Labels: approved, cla: yes, lgtm, size/L

#1014 Do not enable workload identity for perf tests GKE clusters
  testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, cla: yes, lgtm, size/XS

#1011 Escape test name before matching slack message history
  test/mako/alerter/alerter.go
  test/mako/alerter/slack/message_test.go
  test/slackutil/message_read.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1015 Give cloud-platform scope by default in creating GKE clusters
  test/gke/request.go
  testutils/clustermanager/e2e-tests/gke_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1010 include testing helpers to fuzz our API types and perform some roundtrip testing
  Gopkg.lock
  Gopkg.toml
  apis/testing/fuzzer/fuzzer.go
  apis/testing/roundtrip/roundtrip.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
Labels: approved, cla: yes, lgtm, size/XXL

#1016 golang format tools
  test/mako/alerter/slack/message_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1013 Use another semver library to support build tags properly.
  Gopkg.lock
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1017 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#1018 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1024 Use e2 VMs instead of n1 for test clusters
  test/gke/request.go
  testutils/clustermanager/e2e-tests/example_test.go
  testutils/clustermanager/e2e-tests/gke.go
  testutils/clustermanager/e2e-tests/gke_test.go
  testutils/clustermanager/perf-tests/pkg/benchmark.go
  testutils/clustermanager/perf-tests/pkg/benchmark_test.go
  testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark1/cluster.yaml
  testutils/clustermanager/prow-cluster-operation/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1026 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#1027 Fix the URL errors for go1.14
  apis/url_test.go
Labels: approved, cla: yes, lgtm, size/S

#1021 Allow Custom `dep ensure` args in hack/update-deps.sh
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1025 Add RecordN method to permit recording of N measurements simultaneously.
  metrics/config.go
  metrics/record.go
  metrics/record_test.go
Labels: approved, cla: yes, lgtm, size/L

#1030 add KnativeReference
  apis/duck/v1/destination_test.go
  apis/duck/v1/knative_reference.go
  apis/duck/v1/knative_reference_test.go
  apis/duck/v1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L
