Repository knative/pkg, pull requests merged in 2020-12, with the labels that each got.

#1933 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1935 Remove the unused file
  network/handlers/error.go
Labels: approved, cla: yes, lgtm, size/S

#1936 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1773 Use zapdriver config as base zap config
  go.mod
  go.sum
  logging/config.go
  logging/config_test.go
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1938 Fix the logstream since it's paniciiiiing
  test/logstream/v2/stream.go
  test/logstream/v2/stream_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1939 Log if the deserialized line is semi-normal.
  test/logstream/v2/stream.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1941 Remove the pkg/network/prober since it's moved to networking
  network/depcheck_test.go
  network/prober/doc.go
  network/prober/prober.go
  network/prober/prober_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1944 Default to the lowest pre-release version to be the minimum
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1946 Fix some nits around logging
  logging/config.go
  test/logstream/v2/stream_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1950 Make the profiling port configurable via envvar.
  profiling/server.go
Labels: approved, cla: yes, lgtm, size/S

#1952 Fix missing 'to'.
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1949 Add smart handling of selectors in webhooks
  webhook/helper.go
  webhook/helper_test.go
  webhook/psbinding/psbinding.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
Labels: approved, cla: yes, lgtm, size/L

#1953 Expose the statefulset constructor
  leaderelection/context.go
Labels: approved, cla: yes, lgtm, size/XS

#1954 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#1961 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1955 Update wrong year for pkg cut
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/XS

#1962 Format copyright headers to match boilerplate
  apis/testing/conditions.go
  source/source_labels.go
  source/source_labels_test.go
  source/source_stats_reporter.go
  test/upgrade/asserts_test.go
  test/upgrade/execute_failures_test.go
  test/upgrade/functions.go
  test/upgrade/functions_test.go
  test/upgrade/private_types.go
  test/upgrade/steps.go
  test/upgrade/suite_examples_test.go
  test/upgrade/suite_execution.go
  test/upgrade/testing_operations_test.go
  test/upgrade/testing_types_test.go
  test/upgrade/types.go
  test/upgrade/vars.go
  test/upgrade/zaptest_buffer_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1963 [0.19] Backport "Add host config option to the prometheus exporter (#1882)"
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  metrics/prometheus_exporter.go
  metrics/prometheus_exporter_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#1964 Fix excessive allocation in the resource metrics
  metrics/resource_view.go
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/M

#1966 Remove useless logger creation
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1959 Enable multi namespace log collection in e2e test
  test/logstream/README.md
  test/logstream/interface.go
  test/logstream/v2/stream.go
  test/logstream/v2/stream_test.go
Labels: approved, area/test-and-release, cla: yes, kind/enhancement, lgtm, size/L

#1967 [Automated] Format markdown
  test/logstream/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1969 Remove unnecessary intermediate loggers
  controller/controller.go
  logging/config.go
  websocket/connection.go
Labels: approved, cla: yes, lgtm, size/M

#1970 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#1971 Unify usage of YAML libraries
  configmap/testing/configmap.go
  go.mod
  test/mako/config/slack.go
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1957 Refactor and fix metrics export tests.
  metrics/config.go
  metrics/e2e_test.go
  metrics/exporter.go
  metrics/exporter_test.go
  metrics/resource_view_test.go
Labels: approved, cla: yes, kind/bug, kind/cleanup, lgtm, size/XXL

#1851 Splitting configmap package to avoid heavy dependencies
  configmap/informer/informed_watcher.go
  configmap/informer/informed_watcher_test.go
  configmap/manual_watcher.go
  configmap/manual_watcher_test.go
  configmap/nodep_test.go
  injection/sharedmain/main.go
  tracing/setup.go
Labels: approved, cla: yes, lgtm, size/L

#1973 Fix comment on constant
  metrics/config_observability.go
Labels: approved, cla: yes, lgtm, size/XS

#1974 Introduce a nostackdriver build tag
  .github/workflows/nostackdriver.yaml
  depcheck/depcheck.go
  tracing/depcheck_test.go
  tracing/nostackdriver.go
  tracing/opencensus.go
  tracing/stackdriver.go
Labels: approved, cla: yes, lgtm, size/L

#1976 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1978 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
