Repository knative/pkg, pull requests merged in 2020-03, with the labels that each got.

#1136 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1134 Generalize SetupFakeContext to be able to serve tests and benchmarks.
  reconciler/testing/context.go
Labels: approved, cla: yes, lgtm, size/XS

#1138 Fix typos
  injection/README.md
Labels: approved, cla: yes, lgtm, size/S

#1133 Add filtering to class based controller stubs.
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#1139 Format markdown
  injection/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1141 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#1142 Fix crash looping when leader election config doesn't exist
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1144 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#1145 Mutate `-` to `_` in component names for metrics
  metrics/exporter.go
  metrics/exporter_test.go
Labels: approved, cla: yes, lgtm, size/S

#1146 Mutate `-` to `_` in component names for metrics (#1145)
  metrics/exporter.go
  metrics/exporter_test.go
Labels: approved, cla: yes, lgtm, size/S

#942 Configurable SpoofRequestInterval and SpoofRequestTimeout
  test/clients.go
  test/e2e_flags.go
  test/request.go
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1150 Fix some nits in the webhook code
  webhook/admission.go
  webhook/conversion.go
  webhook/resourcesemantics/conversion/conversion.go
Labels: approved, cla: yes, lgtm, size/S

#1151 Remove named returns, since they look icky :)
  webhook/certificates/certificates.go
  webhook/resourcesemantics/conversion/conversion.go
Labels: approved, cla: yes, lgtm, size/M

#1153 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/S

#1158 Scope the webhook secret informers to the system namespace.
  injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go
  injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  injection/clients/namespacedkube/informers/factory/factory.go
  injection/clients/namespacedkube/informers/factory/fake/fake.go
  webhook/certificates/certificates_test.go
  webhook/certificates/controller.go
  webhook/configmaps/configmaps_test.go
  webhook/configmaps/controller.go
  webhook/configmaps/table_test.go
  webhook/psbinding/controller.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/conversion/conversion_test.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/table_test.go
  webhook/resourcesemantics/validation/validation_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
Labels: approved, cla: yes, lgtm, size/L

#1160 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/S

#1147 Add a function to parse all env config set by Prow
  Gopkg.lock
  test/prow/env.go
  test/prow/env_test.go
  test/prow/prow.go
  test/prow/prow_test.go
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/usage.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1157 Add JSONTracePred
  test/zipkin/util.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1154 Drop the logic to create missing secrets.
  webhook/certificates/certificates.go
  webhook/certificates/certificates_test.go
Labels: approved, cla: yes, lgtm, size/M

#1164 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1166 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#1148 Add MarkTrueWithReason function to ConditionManager
  apis/condition_set.go
  apis/condition_set_impl_test.go
  apis/condition_set_test.go
Labels: approved, cla: yes, lgtm, size/M

#1165 Updating duckv1.SourceStatus to include CloudEventAttributes
  apis/duck/v1/source_types.go
  apis/duck/v1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#1167 update go-cmpt to work with 1.14.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
Labels: approved, cla: yes, lgtm, size/XXL

#1169 Use boskos to fetch a project if only a project is not specified
  testutils/clustermanager/e2e-tests/gke.go
  testutils/clustermanager/e2e-tests/gke_test.go
Labels: approved, cla: yes, lgtm, size/S

#1170 Add options for cmd library
  test/cmd/command.go
  test/cmd/command_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1173 Introduce key/value store interface + cm backed version of it.
  kvstore/kvstore.go
  kvstore/kvstore_cm.go
  kvstore/kvstore_cm_test.go
Labels: approved, cla: yes, lgtm, size/L

#1174 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#1175 Generate reconcilers for resources out of tree.
  Gopkg.lock
  apis/test/example/v1alpha1/fiz_types.go
  apis/test/example/v1alpha1/zz_generated.deepcopy.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/stub/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/stub/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/stub/controller.go
  client/injection/kube/reconciler/core/v1/namespace/stub/reconciler.go
  codegen/cmd/injection-gen/args/args.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  hack/update-codegen.sh
  test/test-reconciler-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1180 Start the webhook before informers sync.
  injection/sharedmain/main.go
  webhook/admission.go
  webhook/admission_integration_test.go
  webhook/configmaps/configmaps.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/validation/validation.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
Labels: approved, cla: yes, lgtm, size/L

#1182 Fix the defaulting for the leader election config map
  leaderelection/config.go
  leaderelection/config_test.go
Labels: approved, cla: yes, lgtm, size/L

#1183 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS
