Repository knative/pkg, pull requests merged in 2020-09, with the labels that each got.

#1676 Add a helper for checking for all expected responses.
  test/request.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1677 Fix some nits in the test helpers
  test/request.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1678 Permit table test deletions to arrive in arbitrary order.
  reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/M

#1675 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#1684 Add IsEstablished method to ManagedConnection to expose whether the connection has been established
  websocket/connection.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/S

#1685 Fix some comments in main.go
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1687 Remove spammy log line
  webhook/resourcesemantics/conversion/conversion.go
Labels: approved, cla: yes, lgtm, size/XS

#1690 Use the constant in the unit tests that we already have
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, size/M

#1691 Add linting config and fix issues.
  .golangci.yaml
  leaderelection/chaosduck/main.go
  metrics/exporter_test.go
  metrics/prometheus_exporter_test.go
  test/ghutil/fakeghutil/fakeghutil.go
  test/logging/example_tlogger_test.go
  testutils/clustermanager/perf-tests/pkg/benchmark.go
  testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1693 Deprecate --master flag in favor of --server.
  apiextensions/storageversion/cmd/migrate/config.go
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#1688 Alter URIFromObjectReference to return apierrs
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, lgtm, size/M

#1694 Remove branch examples referencing master.
  test/ghutil/fakeghutil/fakeghutil.go
  test/ghutil/pullrequest.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1695 Create a dedicated helper for retrying API calls during tests.
  reconciler/retry.go
  reconciler/retry_test.go
Labels: approved, cla: yes, lgtm, size/M

#1696 Exclude the control-plane from our webhooks for psbinding webhook.
  webhook/psbinding/psbinding.go
Labels: approved, cla: yes, lgtm, size/S

#1697 Fix vestigial argument in signature
  reconciler/retry.go
Labels: approved, cla: yes, lgtm, size/XS

#1698 Enhance error message on failure to update _example.
  webhook/configmaps/configmaps.go
  webhook/configmaps/configmaps_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1699 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1653 Adding github action to test downstream repos.
  .github/workflows/knative-downstream.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1703 Make Do have consistent retry semantics to Poll.
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1704 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#1705 Fix a nit in the spoof
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1706 Teach the spoofing client to support NodePort.
  test/ingress/ingress.go
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1707 Remove the interface that is no longer required
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1701 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1709 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#1710 Fix flakes in EnqueueAfter tests
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/S

#1713 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1714 Inject the pod name into logger when provided in the envvars
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#1715 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1702 Remove patch detail for webhook being logged on info
  webhook/admission.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1716 Remove now unused test helpers
  test/junit/junit.go
  test/junit/junit_test.go
  test/performance/performance.go
  test/testgrid/testgrid.go
  test/testgrid/testgrid_test.go
  testutils/junithelper/README.md
  testutils/junithelper/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1717 Add codecov for pkg
  .codecov.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1652 Suite for running upgrade tests in Knative components
  test/upgrade/asserts_test.go
  test/upgrade/execute_failures_test.go
  test/upgrade/functions.go
  test/upgrade/functions_test.go
  test/upgrade/private_types.go
  test/upgrade/steps.go
  test/upgrade/suite_examples_test.go
  test/upgrade/suite_execution.go
  test/upgrade/testing_operations_test.go
  test/upgrade/testing_types_test.go
  test/upgrade/types.go
  test/upgrade/vars.go
  test/upgrade/zaptest_buffer_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1718 We don't really expect high test coverage for test helpers
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1712 add subresource reconciler for bindings BaseReconciler
  webhook/psbinding/README.md
  webhook/psbinding/reconciler.go
  webhook/psbinding/table_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1719 Various nits around the code
  apis/field_error.go
  metrics/utils.go
  network/transports.go
  reconciler/filter.go
  test/crd.go
  test/monitoring/monitoring.go
  test/prometheus/prometheus_test.go
  test/vegeta/pacers/steady_up_pacer.go
  test/webhook-apicoverage/coveragecalculator/ignorefields.go
  test/webhook-apicoverage/resourcetree/structkindnode.go
  test/webhook-apicoverage/tools/tools.go
  testutils/clustermanager/e2e-tests/boskos/boskos.go
  testutils/clustermanager/perf-tests/pkg/cluster_test.go
  webhook/certificates/resources/certs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1721 Various nits around the pkg
  network/domain.go
  test/clients.go
  test/request.go
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1724 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1723 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#1464 Remove resource_name tag from webhook stats
  webhook/stats_reporter.go
  webhook/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1720 Deep copy views to avoid races
  metrics/resource_view.go
Labels: approved, cla: yes, lgtm, size/S

#1722 Use http.Transport.Clone in preference to copy-pasting defaults
  network/transports.go
Labels: approved, cla: yes, lgtm, size/S

#1730 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#1725 Apply gosec checks to the codebase, except tests.
  .golangci.yaml
  configmap/hash-gen/main.go
  kmeta/names.go
  metrics/opencensus_exporter.go
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/S

#1731 Enable unparam linter to catch unused parameters
  .golangci.yaml
  codegen/cmd/injection-gen/generators/packages.go
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  test/logstream/kubelogs.go
  webhook/conversion.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1732 [release-0.18] point to test-infra release-0.18
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1729 Add a func to return a connection which has been established
  websocket/connection.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/M

#1728 Remove apicoverage from pkg
  test/webhook-apicoverage/coveragecalculator/README.md
  test/webhook-apicoverage/coveragecalculator/calculator.go
  test/webhook-apicoverage/coveragecalculator/coveragedata.go
  test/webhook-apicoverage/coveragecalculator/ignorefields.go
  test/webhook-apicoverage/resourcetree/README.md
  test/webhook-apicoverage/resourcetree/arraykindnode.go
  test/webhook-apicoverage/resourcetree/basictypekindnode.go
  test/webhook-apicoverage/resourcetree/buildChildNodes_test.go
  test/webhook-apicoverage/resourcetree/node.go
  test/webhook-apicoverage/resourcetree/otherkindnode.go
  test/webhook-apicoverage/resourcetree/ptrkindnode.go
  test/webhook-apicoverage/resourcetree/resourceforest.go
  test/webhook-apicoverage/resourcetree/resourcetree.go
  test/webhook-apicoverage/resourcetree/rule.go
  test/webhook-apicoverage/resourcetree/structkindnode.go
  test/webhook-apicoverage/resourcetree/test_util.go
  test/webhook-apicoverage/resourcetree/timetypenode.go
  test/webhook-apicoverage/resourcetree/updateCoverage_test.go
  test/webhook-apicoverage/tools/README.md
  test/webhook-apicoverage/tools/tools.go
  test/webhook-apicoverage/view/README.md
  test/webhook-apicoverage/view/html_display.go
  test/webhook-apicoverage/view/html_template.go
  test/webhook-apicoverage/view/rule.go
  test/webhook-apicoverage/view/xml_display.go
  test/webhook-apicoverage/view/xml_template.go
  test/webhook-apicoverage/webhook/README.md
  test/webhook-apicoverage/webhook/apicoverage_recorder.go
  test/webhook-apicoverage/webhook/webhook.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#1738 Align linters with serving (enables stylecheck and asciicheck)
  .golangci.yaml
  apis/condition_set.go
  apis/deprecated_test.go
  apis/duck/patch_test.go
  apis/duck/scale_test.go
  apis/duck/v1/destination.go
  apis/duck/v1/status_types.go
  apis/duck/v1beta1/status_types.go
  apis/duck/verify_test.go
  controller/controller.go
  kvstore/kvstore_cm.go
  logging/config.go
  logging/logkey/constants.go
  metrics/config.go
  metrics/stackdriver_exporter.go
  reconciler/events.go
  test/ghutil/fakeghutil/fakeghutil.go
  test/logging/spew_encoder.go
  test/logging/tlogger.go
  test/prometheus/prometheus.go
  test/prometheus/prometheus_test.go
  test/zipkin/util.go
  testing/inner_default_resource.go
  testing/resource.go
  testutils/clustermanager/e2e-tests/boskos/fake/fake.go
  tracing/config/tracing.go
  webhook/testing/factory.go
  webhook/testing/listers.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1733 Updates to release leads workflow from 0.18 learnings
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/M

#1742 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#1739 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1743 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1744 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1745 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1747 Some more replacements to atomic.* types
  apis/duck/cached_test.go
  metrics/metrics.go
  metrics/workqueue.go
  reconciler/testing/hooks.go
Labels: approved, cla: yes, lgtm, size/M

#1748 Match pkg codecov settings with serving
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/S

#1749 Make codecov post only a single email
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1750 Improve the logging messages in the reconciler generator.
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#1752 Fix CONTRIBUTING.md link
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1746 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1753 Fix the racy test.
  configmap/informed_watcher_test.go
Labels: approved, cla: yes, lgtm, size/M

#1755 Fix fmt and logger formatting
  apiextensions/storageversion/cmd/migrate/config.go
  apiextensions/storageversion/cmd/migrate/main.go
  apis/metadata_validation_test.go
  codegen/cmd/injection-gen/generators/client.go
  codegen/cmd/injection-gen/generators/duck.go
  codegen/cmd/injection-gen/generators/factory.go
  codegen/cmd/injection-gen/generators/fakeclient.go
  codegen/cmd/injection-gen/generators/fakeduck.go
  codegen/cmd/injection-gen/generators/fakefactory.go
  codegen/cmd/injection-gen/generators/fakeinformer.go
  codegen/cmd/injection-gen/generators/informer.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  codegen/cmd/injection-gen/generators/reconciler_state.go
  injection/sharedmain/main.go
  metrics/stackdriver_exporter.go
  profiling/server.go
  test/request.go
  test/zipkin/util.go
  webhook/admission.go
  webhook/certificates/certificates.go
  webhook/configmaps/configmaps.go
  webhook/conversion.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/reconciler.go
  webhook/resourcesemantics/conversion/conversion.go
  webhook/resourcesemantics/conversion/reconciler.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/webhook.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1759 scott trades release lead role with nacho
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/XS

#1761 Fix the resource naming for known terms
  test/helpers/name.go
  test/helpers/name_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M
