Repository knative/pkg, pull requests merged in 2020-04, with the labels that each got.

#1185 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1171 Move libs from test-infra to pkg
  test/helpers/dir.go
  test/performance/performance.go
  test/testgrid/testgrid.go
  test/testgrid/testgrid_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1188 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1186 Retry cluster creation if there's an error
  testutils/clustermanager/e2e-tests/config.go
  testutils/clustermanager/e2e-tests/gke.go
  testutils/clustermanager/e2e-tests/gke_test.go
  testutils/clustermanager/e2e-tests/util.go
  testutils/clustermanager/prow-cluster-operation/actions/create.go
  testutils/clustermanager/prow-cluster-operation/actions/delete.go
  testutils/metahelper/client/client.go
  testutils/metahelper/client/client_test.go
  testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/L

#1187 Do not set to unknown status when all dependents passed happy check
  apis/condition_set.go
  apis/condition_set_impl_test.go
Labels: approved, cla: yes, lgtm, size/M

#1189 Retry to get logging configmap when failed
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/S

#1190 Allow a 'None' metrics backend, to basically do nothing.
  metrics/config.go
  metrics/config_observability.go
  metrics/exporter.go
  metrics/exporter_test.go
Labels: approved, cla: yes, lgtm, size/S

#1193 Actually use the subtest names in recorder test.
  metrics/record_test.go
Labels: approved, cla: yes, lgtm, size/S

#1198 Replace deprecated 'Track' with 'TrackReference'.
  resolver/addressable_resolver.go
  tracker/enqueue.go
Labels: approved, cla: yes, lgtm, size/S

#1191 Fix a few simple linter warnings: unused code, govet warnings etc.
  codegen/cmd/injection-gen/generators/packages.go
  leaderelection/config.go
  metrics/exporter_test.go
  metrics/monitored_resources.go
  test/e2e_flags.go
  test/logging/logging_test.go
  test/logging/sugar.go
  test/logging/tlogger.go
  test/testgrid/testgrid.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1192 Add augmented logger to the context to pass it down.
  webhook/resourcesemantics/conversion/conversion.go
Labels: approved, cla: yes, lgtm, size/XS

#1194 t.Fatal must not be called in a goroutine.
  webhook/admission_integration_test.go
Labels: approved, cla: yes, lgtm, size/S

#1172 Allow Unstructured callback from Validating Webhook
  apis/contexts.go
  apis/contexts_test.go
  testing/resource.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/resourcesemantics/validation/validation_admit_test.go
  webhook/testing/testing.go
  webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XL

#1197 Include utility to migrate a CRD's storage version
  Gopkg.lock
  apiextensions/OWNERS
  apiextensions/storageversion/cmd/migrate/config.go
  apiextensions/storageversion/cmd/migrate/main.go
  apiextensions/storageversion/migrator.go
  apiextensions/storageversion/migrator_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1201 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/L

#1184 Move duck typing document to markdown
  apis/duck/ABOUT.md
  apis/duck/images/Knative-Duck0.png
Labels: approved, cla: yes, lgtm, size/L

#1204 Brush up the observability config
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, size/M

#1205 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/S

#1206 Make a proper check when checking for spaces.
  configmap/testing/configmap.go
Labels: approved, cla: yes, lgtm, size/XS

#1210 Normalize CM owners across CM directories
  OWNERS_ALIASES
  logging/config
  tracing/config/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1209 Properly productionize tracing config map
  tracing/config/tracing.go
  tracing/config/tracing_test.go
Labels: approved, cla: yes, lgtm, size/L

#1213 Pin the test-infra to release-0.14 for pkg 0.14
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/S

#1215 update the run book for releases in pkg to include the test-infra lock
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/M

#1217 add EnqueueNamespaceOf
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/S

#1220 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1202 use https style vs. ssh
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#1223 Cleanup the logging CM handling.
  logging/config.go
  logging/config_test.go
Labels: approved, cla: yes, lgtm, size/L

#1224 Shorten object name to avoid DNS issue defined (RFC 1035)
  test/helpers/name.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1219 Allow Delete verb on validation callbacks
  apis/contexts.go
  apis/contexts_test.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/resourcesemantics/validation/validation_admit_test.go
Labels: approved, cla: yes, lgtm, size/L

#1221 Allow retry of informer cache init upon error
  apis/duck/cached.go
  apis/duck/cached_test.go
Labels: approved, cla: yes, lgtm, size/L

#1231 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1208 Sinkbinding Webhook should label namespace for inclusion
  reconciler/testing/table.go
  webhook/psbinding/reconciler.go
  webhook/psbinding/table_test.go
Labels: approved, cla: yes, lgtm, size/L

#1229 Release leader election lock as soon as we exit.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1234 Drop 'no longer exist' line to DEBUG.
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1228 Tracing configuration json marshal/unmarshal
  tracing/config/tracing.go
  tracing/config/tracing_test.go
Labels: approved, cla: yes, lgtm, size/L

#1230 Add a controller option to specify a custom finalizer name.
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  controller/options.go
Labels: approved, cla: yes, lgtm, size/M

#1237 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/gobuffalo/envy/LICENSE
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/version.go
Labels: approved, cla: yes, lgtm, size/M

#1238 Add finalizer option and default to test code too.
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1236 Fix the logging to be a sentence
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1241 Make webhook print human readable patch
  webhook/admission.go
Labels: approved, cla: yes, lgtm, size/S

#1235 Add specific callback for the tracker to delete items eagerly.
  reconciler/testing/tracker.go
  reconciler/testing/tracker_test.go
  tracker/enqueue.go
  tracker/enqueue_test.go
  tracker/interface.go
Labels: approved, cla: yes, lgtm, size/L

#1243 [master] Auto-update dependencies
  Gopkg.lock
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#1242 Change default port in webhook test to 8443.
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1239 Use loggers when emitting count messages
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#1244 Some fixes we did in server upstream to pkg
  apis/duck/scale_test.go
  apis/duck/v1/status_types_test.go
  apis/duck/v1beta1/status_types_test.go
  ptr/ptr_test.go
  test/mako/sidecar.go
  test/mako/stub-sidecar/main.go
  test/webhook-apicoverage/resourcetree/basictypekindnode.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1245 Fix the webhook workqueue names
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/validation/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#1246 Incorporate component name into ComponentConfig.
  injection/sharedmain/main.go
  leaderelection/config.go
  leaderelection/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1248 Revert "Use loggers when emitting count messages"
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/M

#1247 Change StartAll to take context.
  controller/controller.go
  controller/controller_test.go
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/M

#1250 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1252 Change %v to %w in errors and other nits
  metrics/opencensus_exporter_test.go
  metrics/stackdriver_exporter.go
  network/prober/prober.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
  test/ghutil/client.go
  test/helpers/dir.go
  test/mako/alerter/github/issue.go
  test/mako/alerter/slack/message.go
  test/monitoring/monitoring.go
  test/spoof/spoof.go
  test/webhook-apicoverage/coveragecalculator/ignorefields.go
  test/webhook-apicoverage/tools/tools.go
  test/webhook-apicoverage/webhook/webhook.go
  test/zipkin/util.go
  testutils/clustermanager/e2e-tests/boskos/boskos.go
  testutils/clustermanager/e2e-tests/gke.go
  testutils/clustermanager/e2e-tests/gke_test.go
  testutils/clustermanager/perf-tests/pkg/benchmark.go
  testutils/clustermanager/perf-tests/pkg/cluster.go
  tracing/config/tracing.go
  tracing/opencensus.go
  webhook/certificates/resources/certs_test.go
  webhook/configmaps/configmaps.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/reconciler.go
  webhook/resourcesemantics/conversion/reconciler.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/webhook.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1253 Inject config into controller context.
  injection/context.go
  injection/context_test.go
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/M

#1255 Generate unique workqueue names.
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
Labels: approved, cla: yes, lgtm, size/S

#1249 Assorted linting fixes.
  apiextensions/storageversion/migrator_test.go
  apis/condition_set.go
  apis/condition_set_impl_test.go
  controller/stats_reporter_test.go
  test/cmd/command.go
  test/gcs/gcs.go
  test/ghutil/fakeghutil/fakeghutil.go
  test/logging/spew_encoder.go
  test/prow/prow.go
  test/webhook-apicoverage/webhook/webhook.go
  testutils/clustermanager/e2e-tests/common/common_test.go
  testutils/clustermanager/e2e-tests/config.go
  webhook/psbinding/psbinding.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/webhook_integration_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1254 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#1256 Skip doing any work if `Also` receives no errors
  apis/field_error.go
  apis/field_error_test.go
Labels: approved, cla: yes, lgtm, size/M

#1258 Fix malformed license headers.
  configmap/testing/configmap.go
  metrics/doc.go
  metrics/exporter.go
  metrics/metricstest/metricstest.go
  metrics/opencensus_exporter.go
  metrics/prometheus_exporter.go
  network/h2c.go
  network/transports.go
  network/transports_test.go
  websocket/hijack.go
Labels: approved, cla: yes, lgtm, size/S

#1260 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1257 Explicitly name controller filters.
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1264 populate the v1alpha1.Hostname from the URI as per the spec
  apis/duck/v1alpha1/addressable_types.go
  apis/duck/v1alpha1/addressable_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#1265 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1267 Expose the `dialWithBackOff` utility
  network/transports.go
  network/transports_test.go
Labels: approved, cla: yes, lgtm, size/S
