Repository knative/pkg, pull requests merged in 2020-08, with the labels that each got.

#1578 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/CONTRIBUTING.md
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/base/base.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/credentials/alts/alts.go
  vendor/google.golang.org/grpc/credentials/alts/internal/authinfo/authinfo.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/service/service.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/grpclog/component.go
  vendor/google.golang.org/grpc/grpclog/loggerv2.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/env_config.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/binarylog/sink.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/logging.go
  vendor/google.golang.org/grpc/internal/channelz/types.go
  vendor/google.golang.org/grpc/internal/channelz/types_nonlinux.go
  vendor/google.golang.org/grpc/internal/credentials/go110.go
  vendor/google.golang.org/grpc/internal/credentials/gobefore110.go
  vendor/google.golang.org/grpc/internal/grpclog/grpclog.go
  vendor/google.golang.org/grpc/internal/grpclog/prefixLogger.go
  vendor/google.golang.org/grpc/internal/grpcutil/encode_duration.go
  vendor/google.golang.org/grpc/internal/grpcutil/metadata.go
  vendor/google.golang.org/grpc/internal/grpcutil/method.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/log.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1576 Print loglines from chaosduck to all tests.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1353 Allow to specify service name and endpoint IP respectively for zipkin tracing
  tracing/opencensus.go
Labels: approved, cla: yes, lgtm, size/S

#1546 Allow creating controller with custom RateLimiter.
  controller/controller.go
  controller/controller_test.go
  controller/two_lane_queue.go
  controller/two_lane_queue_test.go
Labels: approved, cla: yes, lgtm, size/L

#1579 Remove resourceToKey map
  metrics/resource_view.go
Labels: approved, cla: yes, lgtm, size/S

#1580 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/any_str.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_optional.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/reflect_struct_encoder.go
  vendor/github.com/json-iterator/go/stream.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/config.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/increase_level.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/utils/pointer/README.md
  vendor/k8s.io/utils/trace/README.md
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1581 Disable GC to reduce test flakiness
  metrics/memstats_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1575 Set reporting period for all meters
  metrics/config.go
  metrics/config_test.go
  metrics/exporter.go
  metrics/resource_view.go
Labels: approved, cla: yes, lgtm, size/M

#1582 Add Cleanup to our weird test interface.
  test/logging/tlogger.go
  test/tinterface.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1577 Add field to observability config for enabling request logging
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#1586 Fixes a race in the logstream.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1587 Replace init with sync.Once
  test/logstream/interface.go
  test/logstream/null.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1588 Remove ErrGroup from kubelogs altogether
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1593 Use the same timeout value for Stackdriver API
  metrics/stackdriver_exporter.go
Labels: approved, cla: yes, lgtm, size/XS

#1594 Also log the key we're enqueueing when printing debug info
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1589 Delete deprecated NewDefaultWatcher func
  configmap/informed_watcher.go
Labels: approved, cla: yes, lgtm, size/XS

#1591 Use real synchronization to make sure we get four exports in the OpenCensus test
  metrics/opencensus_exporter.go
  metrics/resource_view.go
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/M

#1592 filter "control-plane" labeled namespaces out of our webhooks
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
Labels: approved, cla: yes, lgtm, size/S

#1595 Switch to the atomic bool from uber package for the profiling flag
  go.mod
  go.sum
  profiling/server.go
  profiling/server_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1598 Have codegen log status diffs at debug level
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/S

#1599 Completely skip metric reporting if backend is 'none'.
  metrics/config.go
  metrics/record_test.go
Labels: approved, cla: yes, lgtm, size/S

#1600 add helper to parse namespaced names
  configmap/parse.go
  configmap/parse_test.go
Labels: approved, cla: yes, lgtm, size/M

#1601 Fix comment to ensure we tell the truth to the world
  apis/duck/v1/status_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1605 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1604 fix nil pointer
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1607 [RELEASE] Pin test-infra to release-0.17 branch.
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1584 Add a release leads rotation.
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/L

#1608 fix nil pointer (#1604)
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1609 Fix the debug->debugf
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#1610 Inject the config into the context.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1611 Inject the config into the context.
  injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1616 Replace error return with logging to all tests in an error case.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1613 [master] Format markdown
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/M

#1614 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1617 [release 0.17] Merge kubelogs and controller logging fixes
  controller/controller.go
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#1618 Add a helper func for BucketSet
  hash/bucketer.go
  hash/bucketer_test.go
Labels: approved, cla: yes, lgtm, size/S

#1619 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1620 Write a little guide on using logstream.
  test/logstream/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1612 Add eventing-kafka-broker to released repositories
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/XS

#1621 adding build, unit test, style and verify github actions
  .github/workflows/go-pr-build.yaml
  .github/workflows/go-pr-style.yaml
  .github/workflows/go-pr-test.yaml
  .github/workflows/go-pr-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1622 found another way to get repo name in gh actions
  .github/workflows/go-pr-build.yaml
  .github/workflows/go-pr-style.yaml
  .github/workflows/go-pr-test.yaml
  .github/workflows/go-pr-verify.yaml
  hash/hash_test.go
  metrics/metricstest/resource_metrics_test.go
  test/gcs/mock/mock_example_test.go
  test/logging/example_tlogger_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1623 Assorted tweaks to actions.
  .github/workflows/go-build.yaml
  .github/workflows/go-style.yaml
  .github/workflows/go-test.yaml
  .github/workflows/go-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#1625 don't pre/post process if skipstatusupdate
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1627 Fix the logkey.Key tagging in Enqueue.
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#1624 Make the match about smarter about filtering its own tests.
  test/logstream/kubelogs.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1629 [master] Format markdown
  test/logstream/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1630 Various cleanups around the codebase
  apis/duck/v1beta1/destination.go
  kmp/diff.go
  kmp/reporters.go
  kmp/reporters_test.go
  test/logging/error.go
  test/logging/tlogger.go
  test/webhook-apicoverage/view/xml_display.go
  test/webhook-apicoverage/view/xml_template.go
  testutils/clustermanager/e2e-tests/boskos/fake/fake.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/user_info.go
  webhook/resourcesemantics/defaulting/user_info_test.go
  webhook/resourcesemantics/validation/validation_admit_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1631 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1633 Update release leader document
  RELEASE-LEADS.md
Labels: approved, cla: yes, lgtm, size/S

#1632 Fix the flaky test.
  controller/stats_reporter_test.go
  controller/two_lane_queue_test.go
Labels: approved, cla: yes, lgtm, size/M

#1635 Add collector address to be used by queue-proxy
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, size/S

#1634 Add duck type in README.md
  apis/duck/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1636 Generate Informer injection for coordination/v1
  client/injection/kube/informers/coordination/v1/lease/fake/fake.go
  client/injection/kube/informers/coordination/v1/lease/lease.go
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1643 [release-0.17] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1642 [master] Update GitHub Actions
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1644 Remove the extraneous templates from pkg
  .github/workflows/knative-go-style.yaml
  .github/workflows/knative-go-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#1646 Add a test to verify #542 is not an issue
  apis/duck/patch_test.go
Labels: approved, cla: yes, lgtm, size/S

#1203 Wait for Processes to Exit During Cleanup
  test/monitoring/monitoring.go
Labels: approved, area/test-and-release, cla: yes, lgtm, lifecycle/stale, size/S

#1649 Some minor test coverage improvements and code flow improvements
  logging/config.go
  logging/config_test.go
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, size/M

#1648 Fix the the request logging boolean toggle
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, cla: yes, lgtm, size/M

#1650 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1651 Switch bool parsing to the real parser
  configmap/parse.go
  configmap/parse_test.go
Labels: approved, cla: yes, lgtm, size/M

#1603 Reduce delays in controller tests
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#1602 Support customizing lease name and identity
  leaderelection/config.go
  leaderelection/context.go
  leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/M

#1654 Remove all ClearAll calls from pkg UTs
  configmap/store_test.go
  controller/controller_test.go
  metrics/config_test.go
  webhook/resourcesemantics/validation/validation_deprecated_test.go
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/M

#1655 only hardcode SYSTEM_NAMESPACE if not set
  system/testing/names.go
Labels: approved, cla: yes, lgtm, size/XS

#1656 Make knativeResourceLock exported
  leaderelection/config.go
  leaderelection/context.go
Labels: approved, cla: yes, lgtm, size/XS

#1657 Remove ClearAll from the codebase
  logging/testing/util.go
Labels: approved, cla: yes, lgtm, size/XS

#1659 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1658 Allows utilities easy mode for Knative Injection
  injection/sharedmain/main.go
  leaderelection/chaosduck/main.go
Labels: approved, cla: yes, lgtm, size/M

#1662 Ignore func filed for json marshaling
  leaderelection/config.go
Labels: approved, cla: yes, lgtm, size/XS

#1661 Modernize the controller tests
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#1665 Make test override pongTimeout correctly.
  websocket/connection_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1669 Remove code duplication by reusing funcs
  controller/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#1670 Fix the error messages which are misleading at least
  metrics/metricstest/metricstest.go
Labels: approved, cla: yes, lgtm, size/XS

#1671 Make controller tests reentrant
  controller/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/S

#1673 Skip flaky tests
  metrics/resource_view_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1666 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1674 Fix the reentrance of the github issue tests
  test/ghutil/fakeghutil/fakeghutil.go
  test/mako/alerter/github/issue.go
  test/mako/alerter/github/issue_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M
