Repository knative/pkg, pull requests merged in 2021-05, with the labels that each got.

#2112 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#2095 Allow URIs to be resolved without reconciler context
  resolver/addressable_resolver.go
Labels: approved, cla: yes, kind/enhancement, lgtm, ok-to-test, size/S

#2118 Remove grantr from approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2119 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2117 Allow disable via regex in chaosduck
  leaderelection/chaosduck/main.go
Labels: approved, cla: yes, lgtm, size/S

#2121 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#2123 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2125 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2126 Replace golint with revive
  .golangci.yaml
  apis/duck/v1beta1/destination.go
  leaderelection/chaosduck/main.go
Labels: approved, cla: yes, lgtm, size/S

#2129 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2120 update the multiple label selector implemention to avoid clobber in filtered factory
  client/injection/apiextensions/informers/factory/filtered/fake/fake_filtered_factory.go
  client/injection/apiextensions/informers/factory/filtered/filtered_factory.go
  client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  client/injection/kube/informers/factory/filtered/filtered_factory.go
  codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  codegen/cmd/injection-gen/generators/filtered_factory.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2131 Fix revive related linting issues
  apis/condition_set.go
  apis/condition_types.go
  apis/deprecated.go
  apis/duck/register.go
  apis/duck/v1/register.go
  apis/duck/v1alpha1/register.go
  apis/duck/v1beta1/register.go
  apis/test/example/register.go
  apis/test/example/v1alpha1/register.go
  apis/test/pub/register.go
  apis/test/pub/v1alpha1/register.go
  configmap/manual_watcher.go
  controller/controller.go
  controller/stats_reporter.go
  depcheck/heavy.go
  metrics/metricstest/metricstest.go
  reconciler/events.go
  reconciler/reconcile_common.go
  system/env.go
  test/e2e_flags.go
  test/gcs/mock/mock.go
  test/gcs/mock/mock_storage.go
  test/ha/ha.go
  test/interactive/docker.go
  test/kube_checks.go
  test/tinterface.go
  testing/duck/register.go
  testing/inner_default_resource.go
  testing/register.go
  tracing/testing/zipkin.go
  tracing/zipkin.go
  webhook/admission.go
  webhook/psbinding/psbinding.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2132 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2133 consolidate k8s flags to an environment package
  .github/workflows/knative-downstream.yaml
  apiextensions/storageversion/cmd/migrate/config.go
  apiextensions/storageversion/cmd/migrate/main.go
  environment/client_config.go
  injection/config.go
  injection/sharedmain/main.go
  test/clients.go
  test/e2e_flags.go
  test/environment/config.go
  test/logstream/interface.go
  test/request.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2135 replace KubeClient instances with kubernetes.Interface
  test/README.md
  test/ha/ha.go
  test/kube_checks.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2137 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S
