Repository knative/pkg, pull requests merged in 2021-07, with the labels that each got.

#2177 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/S

#2181 Retry 'no route to host' errors by default
  test/spoof/error_checks.go
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2182 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2185 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2186 Bump a few assorted dependencies
  go.mod
  go.sum
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#2166 Add CheckEndpointState method to SpoofingClient
  test/request.go
  test/spoof/spoof.go
  test/spoof/spoof_test.go
Labels: approved, area/test-and-release, cla: yes, kind/api-change, lgtm, size/L

#2180 Add ability to filter objects on injection controller promotion
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/controller.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/secret/controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  controller/options.go
  injection/README.md
Labels: approved, cla: yes, lgtm, size/M

#2189 include OpenCensus in the list of metric backends
  metrics/config_observability.go
Labels: approved, cla: yes, lgtm, size/XS

#2191 Removing default for KUBECONFIG to enable incluster e2e tests
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#2192 drop unused stackdriver unit test workflow
  .github/workflows/nostackdriver.yaml
Labels: approved, cla: yes, lgtm, size/M

#2193 remove source stats reporter it's been moved to knative.dev/eventing/pkg/metrics/source
  source/source_stats_reporter.go
  source/source_stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/L

#2194 minor bug when passing spoof options
  test/request.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2197 Use default Kubeconfig loading rules
  environment/client_config.go
  test/clients.go
Labels: approved, area/test-and-release, cla: yes, kind/bug, lgtm, size/M

#2196 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2199 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2201 Add a new mechanism for requeuing a key.
  controller/controller.go
  controller/controller_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#2202 Ignore special errors in codegen for events
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#2203 Drop Client as it is only used in tests
  webhook/admission_integration_test.go
  webhook/conversion_integration_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/S

#2178 K8s Service trailing-slash fix in URI resolver
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, kind/bug, lgtm, ok-to-test, size/XS
