Repository knative/pkg, pull requests merged in 2021-03, with the labels that each got.

#2036 Fix race: Make informed watcher start wait for Add event 🏎️
  configmap/informer/informed_watcher.go
  configmap/informer/informed_watcher_test.go
  configmap/informer/synced_callback.go
  configmap/informer/synced_callback_test.go
Labels: approved, cla: yes, kind/bug, lgtm, size/L

#2041 Fix comment for skipKeyError
  controller/controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2042 Redo the comment a bit further
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#2045 Add WaitForCacheSyncQuick and use it in tests
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1983 Add kn-plugin-admin to downstream tests
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2046 Slash off 5s from TestAdmissionValidResponseForResource
  webhook/admission_integration_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2047 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2049 Run downstream action on master branch too
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2051 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2053 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2052 Add benchmark for metrics recording
  metrics/record_test.go
Labels: approved, cla: yes, lgtm, size/M

#2054 Implement getter machinery to generically fetch all injected clients
  client/injection/apiextensions/client/client.go
  client/injection/apiextensions/client/fake/fake.go
  client/injection/kube/client/client.go
  client/injection/kube/client/fake/fake.go
  codegen/cmd/injection-gen/generators/client.go
  codegen/cmd/injection-gen/generators/fake_client.go
  injection/clients.go
  injection/clients_test.go
  injection/interface.go
Labels: approved, cla: yes, lgtm, size/M

#2056 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2055 Add RunAndSyncInformers helper that makes sure informers are synced in tests
  reconciler/testing/context.go
  webhook/webhook_test.go
Labels: approved, cla: yes, lgtm, size/M

#2050 Drop master references to knative repos
  README.md
  apis/duck/ABOUT.md
  metrics/config.go
  metrics/exporter.go
  test/README.md
  test/logstream/README.md
  test/mako/sidecar.go
  test/zipkin/util.go
  version/version.go
  webhook/psbinding/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2058 Upgrade a few assorted dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2060 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2059 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2065 rename downstream-test-go to actions-downstream-test
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2064 Use TB interface, rather than T pointer when doing test stuff
  configmap/testing/configmap.go
  reconciler/testing/context.go
  tracing/zipkin.go
Labels: approved, cla: yes, lgtm, size/S

#2070 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2066 Update reconciler_controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/controller.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/secret/controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#2062 Update webhook/README.md to reflect current packages
  webhook/README.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#2074 Fix int conversion in statefulset ordinals
  leaderelection/config.go
  leaderelection/config_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2076 Bump k8s min version to v1.18.0
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/S

#2069 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#2077 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
