Repository knative/pkg, pull requests merged in 2021-11, with the labels that each got.

#2336 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm, cla: yes

#2342 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm, cla: yes

#2343 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#2341 Build downstream tests with go 1.17
  .github/workflows/knative-downstream.yaml
Labels: size/XS, approved, lgtm, cla: yes

#2344 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm, cla: yes

#2345 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm, cla: yes

#2346 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/M, approved, lgtm, cla: yes

#2347 Remove unclear comment for `makeSpoofClient()` arg
  test/request.go
Labels: size/XS, approved, lgtm, area/test-and-release, cla: yes

#2349 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#2339 Disable controllers using a command-line flag
  injection/interface.go
  injection/sharedmain/main.go
  injection/sharedmain/main_test.go
Labels: approved, lgtm, size/L, kind/feature, cla: yes

#2351 Add retry checker for DNS failure from Ingress
  test/spoof/error_checks.go
  test/spoof/spoof.go
Labels: approved, lgtm, size/S, area/test-and-release, cla: yes

#2352 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#2350 codegen - support multiple annotation keys
  codegen/cmd/injection-gen/generators/comment_parser.go
  codegen/cmd/injection-gen/generators/comment_parser_test.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  reconciler/filter.go
Labels: approved, lgtm, size/L, cla: yes

#2354 kmap
  apis/duck/v1/status_types.go
  apis/duck/v1beta1/status_types.go
  kmap/lookup.go
  kmap/lookup_test.go
  kmap/map.go
  kmap/map_test.go
  kmeta/map.go
  leaderelection/config_test.go
Labels: approved, lgtm, size/L, cla: yes

#2355 kmap changes
  kmap/lookup.go
  kmap/lookup_test.go
  kmap/map.go
  kmap/map_test.go
Labels: approved, lgtm, size/L, cla: yes

#2353 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#2357 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#2358 Remove unused recorder field
  metrics/config.go
  metrics/config_test.go
Labels: approved, lgtm, size/S, cla: yes

#2360 Drop unnecessary list creation from bucketer
  hash/bucketer.go
  hash/hash_test.go
Labels: approved, lgtm, size/S, cla: yes

#2361 Revert "Drop unnecessary list creation from bucketer (#2360)"
  hash/bucketer.go
  hash/hash_test.go
Labels: approved, lgtm, size/S, cla: yes

#2365 Add ConfigMap field parsing for int16 and uint16 types
  configmap/parse.go
  configmap/parse_test.go
Labels: size/M, approved, lgtm, cla: yes

#2359 Drop indirect dependencies from go.mod
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/josharian/intern/license.md
  vendor/github.com/go-openapi/jsonpointer/.travis.yml
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/.travis.yml
  vendor/github.com/go-openapi/jsonreference/README.md
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/.travis.yml
  vendor/github.com/go-openapi/swag/README.md
  vendor/github.com/go-openapi/swag/convert.go
  vendor/github.com/go-openapi/swag/convert_types.go
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/influxdata/tdigest/README.md
  vendor/github.com/influxdata/tdigest/go.mod
  vendor/github.com/influxdata/tdigest/go.sum
  vendor/github.com/josharian/intern/README.md
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/josharian/intern/intern.go
  vendor/github.com/josharian/intern/license.md
  vendor/github.com/mailru/easyjson/.gitignore
  vendor/github.com/mailru/easyjson/.travis.yml
  vendor/github.com/mailru/easyjson/Makefile
  vendor/github.com/mailru/easyjson/README.md
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/go.mod
  vendor/github.com/mailru/easyjson/go.sum
  vendor/github.com/mailru/easyjson/helpers.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/github.com/mailru/easyjson/unknown_fields.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, cla: yes

#2366 Drop unused test/cmd package
  go.mod
  go.sum
  test/cmd/command.go
  test/cmd/command_test.go
  test/cmd/error.go
  third_party/VENDOR-LICENSE/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/README
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/modules.txt
Labels: approved, lgtm, area/test-and-release, size/XL, cla: yes
