Repository knative/pkg, pull requests merged in 2021-01, with the labels that each got.

#1980 Comment k8s version to update docs when changed
  version/version.go
Labels: approved, cla: yes, lgtm, size/XS

#1981 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1977 Drainer supports customized kubelet probe check
  network/handlers/drain.go
  network/handlers/drain_test.go
Labels: approved, cla: yes, lgtm, size/M

#1984 Harden logstream against non-object events
  test/logstream/v2/stream.go
Labels: approved, area/test-and-release, cla: yes, kind/bug, lgtm, size/XS

#1988 Use special error type to designate skips.
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  controller/controller.go
  webhook/certificates/certificates.go
  webhook/configmaps/configmaps.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/reconciler.go
  webhook/resourcesemantics/conversion/reconciler.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/validation/reconcile_config.go
Labels: approved, cla: yes, lgtm, size/M

#1991 Use structured logging to augment our logger vs. naming
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/controller.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  controller/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1990 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1994 preserve the stable webhook logger names we had before
  apis/duck/ABOUT.md
  injection/README.md
  webhook/certificates/controller.go
  webhook/configmaps/controller.go
  webhook/psbinding/README.md
  webhook/psbinding/controller.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/validation/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1993 drop excess and duplicate logger properties
  logging/config.go
Labels: approved, cla: yes, lgtm, size/S

#1996 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#1997 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1998 Switch Webhook to ed25519 and expiration of the certificate to seven days
  webhook/certificates/certificates.go
  webhook/certificates/certificates_test.go
  webhook/certificates/resources/certs.go
  webhook/certificates/resources/certs_test.go
  webhook/certificates/resources/secret.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#1999 allow the addressable ducktype to act as an ownerref
  apis/duck/v1/addressable_types.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#2000 Improve client error message when our webhook doesn't have a certificate
  webhook/webhook.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/S

#2002 Fix nil pointer panic in kvstore
  kvstore/kvstore_cm.go
  kvstore/kvstore_cm_test.go
Labels: approved, cla: yes, kind/bug, lgtm, needs-ok-to-test, size/M

#2004 Genreconciler properly generates reconciler for Resources with Status
  client/injection/kube/reconciler/core/v1/secret/controller.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/state.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M
