Repository knative/pkg, pull requests merged in 2021-08, with the labels that each got.

#2204 Support the webhook serving over non-TLS.
  webhook/admission_integration_test.go
  webhook/helper_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#2206 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2208 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#2209 Sink two codegen passes below loop.
  codegen/cmd/injection-gen/generators/packages.go
Labels: approved, lgtm, size/S, kind/cleanup, cla: yes

#2211 Drop redundant pointers and decoders
  webhook/configmaps/configmaps.go
  webhook/psbinding/psbinding.go
  webhook/resourcesemantics/validation/validation_admit.go
Labels: approved, lgtm, size/S, kind/cleanup, cla: yes

#2216 Use consistent case for "Deprecated" comments
  apis/interfaces.go
  controller/controller.go
  metrics/exporter.go
  test/ha/ha.go
  tracing/testing/zipkin.go
  tracing/zipkin.go
  tracker/interface.go
Labels: approved, lgtm, size/S, area/test-and-release, kind/cleanup, cla: yes

#2213 Revert "Remove the unused file (#1935)"
  network/error_handler.go
  network/handlers/error.go
Labels: approved, lgtm, size/S, cla: yes

#2218 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/XS, approved, lgtm, cla: yes

#2219 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#2212 Deprecate ReadOnlyFinalizer interface over OnDeletionInterface
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
Labels: approved, lgtm, size/S, cla: yes, kind/deprecation

#2221 Run codegen
  client/injection/kube/reconciler/apps/v1beta1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1beta2/deployment/reconciler.go
  client/injection/kube/reconciler/extensions/v1beta1/deployment/reconciler.go
Labels: kind/bug, size/XS, approved, lgtm, cla: yes

#2220 Have the addressable resolver take a tracker.
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, lgtm, size/S, kind/cleanup, cla: yes

#2222 Introduce `NewContext`, deprecate `NewImplFull`.
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/controller.go
  client/injection/kube/reconciler/apps/v1beta1/deployment/controller.go
  client/injection/kube/reconciler/apps/v1beta2/deployment/controller.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/secret/controller.go
  client/injection/kube/reconciler/extensions/v1beta1/deployment/controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  controller/controller.go
  injection/README.md
  webhook/certificates/controller.go
  webhook/configmaps/controller.go
  webhook/psbinding/README.md
  webhook/psbinding/controller.go
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/validation/controller.go
Labels: size/M, approved, lgtm, kind/cleanup, cla: yes

#2223 Remove long deprecated NewImplWithStats
  controller/controller.go
  controller/controller_test.go
Labels: size/M, approved, lgtm, kind/cleanup, cla: yes

#2224 This implements the EventExpansion needed to emit K8s events.
  client/injection/kube/client/client_expansion.go
Labels: size/XS, approved, lgtm, cla: yes, kind/enhancement

#2226 Make the configmap update logging Debugf
  configmap/store.go
Labels: size/XS, approved, lgtm, kind/cleanup, cla: yes

#2231 Trim the space in configmap/registriesSkippingTagResolving's url.
  configmap/parse.go
  configmap/parse_test.go
Labels: approved, lgtm, size/S, cla: yes, ok-to-test

#2234 Update version check comment
  version/version.go
Labels: size/XS, approved, lgtm, kind/cleanup, cla: yes

#2217 Add length limit for the generated names used in tests
  test/helpers/name.go
  test/helpers/name_test.go
Labels: size/M, approved, lgtm, area/test-and-release, cla: yes

#2228 Drop several deprecated APIs
  controller/controller.go
  controller/controller_test.go
  resolver/addressable_resolver.go
Labels: size/M, approved, lgtm, kind/cleanup, cla: yes

#2236 Add triggers to the downstream test
  .github/workflows/tekton-downstream.yaml
Labels: size/XS, approved, lgtm, cla: yes, kind/enhancement
