Repository knative/pkg, pull requests merged in 2021-10, with the labels that each got.

#2272 Check Knative CustomResourceDefinitions stored version
  test/migrate/checks.go
Labels: size/M, approved, lgtm, area/test-and-release, cla: yes

#2304 Allow tracking Cluster-scoped resources.
  tracker/enqueue.go
  tracker/enqueue_test.go
Labels: approved, lgtm, size/S, cla: yes, kind/enhancement

#2306 Add unit test coverage of cluster-scoped tracker.
  tracker/enqueue_test.go
Labels: size/XS, approved, lgtm, kind/cleanup, cla: yes

#2302 introduce new case convention for leader election config map
  leaderelection/config.go
  leaderelection/config_test.go
Labels: size/M, approved, lgtm, cla: yes

#2315 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#2318 Bump assorted dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/README.md
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/acl.go
  vendor/cloud.google.com/go/storage/bucket.go
  vendor/cloud.google.com/go/storage/doc.go
  vendor/cloud.google.com/go/storage/go.mod
  vendor/cloud.google.com/go/storage/go.sum
  vendor/cloud.google.com/go/storage/hmac.go
  vendor/cloud.google.com/go/storage/internal/apiv2/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storage_client.go
  vendor/cloud.google.com/go/storage/invoke.go
  vendor/cloud.google.com/go/storage/notifications.go
  vendor/cloud.google.com/go/storage/reader.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/cloud.google.com/go/storage/writer.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/google.golang.org/api/iamcredentials/v1/iamcredentials-api.json
  vendor/google.golang.org/api/iamcredentials/v1/iamcredentials-gen.go
  vendor/google.golang.org/api/transport/dial.go
  vendor/google.golang.org/api/transport/doc.go
  vendor/google.golang.org/api/transport/go19.go
  vendor/google.golang.org/api/transport/not_go19.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/routing.pb.go
  vendor/google.golang.org/genproto/googleapis/storage/v2/storage.pb.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/namer/namer.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/k8s.io/gengo/types/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, cla: yes
