Repository knative/pkg, pull requests merged in 2021-04, with the labels that each got.

#2057 add filter label selector for serving fake pod informer factory setup
  reconciler/testing/context.go
Labels: approved, cla: yes, kind/bug, lgtm, needs-ok-to-test, size/S

#2079 Simplify loading of local kubeconfig in sharedmain
  injection/config.go
Labels: approved, cla: yes, lgtm, size/XS

#2061 Add skonto to metrics reviewers
  OWNERS_ALIASES
  metrics/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2080 Add benchmarking for the http tracing handler
  tracing/http_test.go
Labels: approved, cla: yes, lgtm, size/M

#2078 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
  apis/OWNERS
  apis/duck/OWNERS
  codegen/OWNERS
  configmap/OWNERS
  controller/OWNERS
  hack/OWNERS
  hash/OWNERS
  kflag/OWNERS
  kmeta/OWNERS
  logging/OWNERS
  metrics/OWNERS
  pool/OWNERS
  reconciler/OWNERS
  source/OWNERS
  test/OWNERS
  tracing/config/OWNERS
  webhook/OWNERS
  websocket/OWNERS
Labels: approved, area/API, area/test-and-release, cla: yes, lgtm, size/L

#2091 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#2092 resolve cluster domain using env CLUSTER_DOMAIN as a fallback
  network/domain.go
  network/domain_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#2090 Fix a few comments in reconciler-gen
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/state.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/state.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/state.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/state.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/state.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_state.go
Labels: approved, cla: yes, lgtm, size/S

#2082 Improve state reporting in kube checks
  test/kube_checks.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2089 Add possibility to implement a deletion handler in a reconciler.
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  reconciler/configstore.go
  reconciler/deletion.go
Labels: approved, cla: yes, lgtm, size/M

#2088 Try fix TestMetricsExport
  metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/XS

#2097 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2100 Allow errors.As to work with reconciler.Events
  reconciler/events.go
  reconciler/events_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S

#2103 Use semantic equality for status update retries
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#2104 Make VolatileTime compatible with controller-gen
  apis/volatile_time.go
Labels: approved, cla: yes, lgtm, size/XS

#2106 Better support for error wrapping with ReconcilerEvents
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  go.sum
  hack/update-codegen.sh
  reconciler/events.go
  reconciler/events_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2105 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2108 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
