Repository knative/pkg, pull requests merged in 2021-06, with the labels that each got.

#2136 Auto-generate webhook certs with ECDSA for FIPS compliance
  webhook/certificates/resources/certs.go
  webhook/certificates/resources/certs_test.go
Labels: approved, cla: yes, lgtm, size/S

#2138 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2140 Bump assorted dependencies
  apis/duck/patch.go
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/multierr/.travis.yml
  vendor/go.uber.org/multierr/CHANGELOG.md
  vendor/go.uber.org/multierr/Makefile
  vendor/go.uber.org/multierr/error.go
  vendor/go.uber.org/multierr/go.mod
  vendor/go.uber.org/multierr/go.sum
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2148 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2150 drop camel as downstream test as it's being archived
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2141 support multiple cleanup functions
  test/cleanup.go
  test/cleanup_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2151 drop kubeclient struct
  test/clients.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2098 set webhooks ownerReferences to namespace
  webhook/configmaps/configmaps.go
  webhook/configmaps/table_test.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#2154 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2149 Lookup k8s services to ensure they exist
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, cla: yes, kind/bug, lgtm, size/M

#2152 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#2155 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, cla: yes, lgtm, size/XS

#2156 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2127 Add KReference.Group field and ResolveGroup function
  apis/duck/v1/knative_reference.go
  apis/duck/v1/knative_reference_test.go
  kref/knative_reference.go
  kref/knative_reference_resolve_group_test.go
Labels: approved, cla: yes, lgtm, size/L

#2157 Bump k8s min k8s version to 1.19
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/S

#2159 fix package name
  test/environment/config.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2161 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2162 drop deprecated enabledComponents field
  leaderelection/config.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2163 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2165 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2167 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, cla: yes, lgtm, size/XS

#2168 Print proper warning logs from API warnings
  injection/sharedmain/main.go
  logging/warning_handler.go
Labels: approved, cla: yes, lgtm, size/M

#2169 Replace reference to obsolete xip.io service
  test/spoof/spoof.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2160 Allow customize DefaultThreadsPerController value
  controller/controller.go
  controller/options.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2171 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2172 Added inverse functions for the ptr package
  ptr/value.go
  ptr/value_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, ok-to-test, size/L
