Repository knative/pkg, pull requests merged in 2022-09, with the labels that each got.

#2588 Updates boilerplate action to use go v1.18
  .github/workflows/knative-boilerplate.yaml
Labels: size/XS, approved, lgtm

#2587 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2589 fix lint warnings
  configmap/hash-gen/main.go
  configmap/hash-gen/main_test.go
  configmap/load.go
  configmap/load_test.go
  configmap/testing/configmap.go
  go.mod
  metrics/client_test.go
  metrics/e2e_test.go
  metrics/opencensus_exporter_test.go
  metrics/resource_view.go
  metrics/resource_view_test.go
  network/error_handler.go
  test/cleanup_test.go
  test/gcs/gcs.go
  test/gcs/mock/mock.go
  test/gcs/mock/mock_test.go
  test/ghutil/client.go
  test/interactive/docker.go
  test/logstream/v2/stream_test.go
  test/mako/config/benchmark.go
  test/slackutil/http.go
  test/slackutil/message_read.go
  test/slackutil/message_write.go
  test/spoof/spoof.go
  test/upgrade/execute_failures_test.go
  test/zipkin/util.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/modules.txt
  webhook/admission_integration_test.go
  webhook/conversion_integration_test.go
  webhook/webhook_integration_test.go
  websocket/connection.go
Labels: approved, lgtm, size/L, area/test-and-release

#2592 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#2590 Register webhook GVKs for validating callbacks
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit_test.go
Labels: kind/bug, size/M, approved, lgtm

#2567 Allow configuration of threads-per-controller
  injection/sharedmain/main.go
Labels: size/XS, approved, lgtm, needs-ok-to-test, kind/enhancement

#2596 Avoid second lister fetch during finalizer reconciliation.
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1/mutatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1/validatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1beta1/mutatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1beta1/validatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1beta1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1beta2/deployment/reconciler.go
  client/injection/kube/reconciler/batch/v1/cronjob/reconciler.go
  client/injection/kube/reconciler/batch/v1beta1/cronjob/reconciler.go
  client/injection/kube/reconciler/core/v1/configmap/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/node/reconciler.go
  client/injection/kube/reconciler/core/v1/pod/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  client/injection/kube/reconciler/extensions/v1beta1/deployment/reconciler.go
  client/injection/kube/reconciler/extensions/v1beta1/networkpolicy/reconciler.go
  client/injection/kube/reconciler/networking/v1/networkpolicy/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, lgtm, size/S, kind/cleanup

#2597 Define a global for `reconciler.DefaultTimeout`.
  reconciler/reconcile_common.go
Labels: size/XS, approved, lgtm

#2600 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2602 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2593 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
