Repository knative/pkg, pull requests merged in 2022-12, with the labels that each got.

#2654 :wastebasket: Removal of Tekton downstream tests
  .github/workflows/tekton-downstream.yaml
Labels: size/M, approved, lgtm, kind/removal

#2658 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2661 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2660 make sure ChildName produces a valid dns subdomain
  kmeta/names.go
  kmeta/names_test.go
Labels: kind/bug, size/M, approved, lgtm
