Repository knative/pkg, pull requests merged in 2022-05, with the labels that each got.

#2506 Fix linting
  network/transports_test.go
Labels: kind/bug, size/XS, approved, lgtm

#2498 Add support for admission webhook warnings.
  apis/deprecated.go
  apis/field_error.go
  apis/field_error_test.go
  testing/inner_default_resource.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/resourcesemantics/validation/validation_deprecated_test.go
  webhook/testing/testing.go
Labels: approved, lgtm, size/L, kind/enhancement

#2507 Use knative/action/go/downstream-test
  .github/workflows/knative-downstream.yaml
  .github/workflows/tekton-downstream.yaml
Labels: size/M, approved, lgtm

#2510 Fix timeout test on darwin and log dial destination on timeout.
  network/transports.go
  network/transports_test.go
Labels: approved, lgtm, size/S

#2511 Switch to iota/fmt.Stringer-based diagnostic levels.
  apis/field_error.go
Labels: size/M, approved, lgtm, kind/cleanup

#2512 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2515 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2517 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2520 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2523 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#2524 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2522 Log metrics/logging init messages at debug level
  logging/config.go
  metrics/metrics_worker.go
  metrics/prometheus_exporter.go
Labels: approved, lgtm, size/S, kind/enhancement
