Repository knative/pkg, pull requests merged in 2022-04, with the labels that each got.

#2476 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#2477 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/XL

#2478 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/L

#2480 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, approved, lgtm

#2481 bump go version of tekton downstream workflow
  .github/workflows/knative-downstream.yaml
  .github/workflows/tekton-downstream.yaml
Labels: size/XS, approved, lgtm

#2484 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2485 bump our min k8s version to 1.22
  version/version.go
  version/version_test.go
Labels: approved, lgtm, size/S

#2486 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2479 Add `NewProxyAutoTLSTransport` and `DialTLSWithBackOff` to support TLS proxy
  network/h2c.go
  network/transports.go
  network/transports_test.go
Labels: approved, lgtm, size/L

#2487 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2488 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, approved, lgtm

#2489 Add genreconcile for ConfigMap
  client/injection/kube/reconciler/core/v1/configmap/controller.go
  client/injection/kube/reconciler/core/v1/configmap/reconciler.go
  client/injection/kube/reconciler/core/v1/configmap/state.go
  hack/update-codegen.sh
Labels: size/XS, approved, lgtm, area/test-and-release, ok-to-test

#2490 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#2492 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, approved, lgtm

#2402 :bug: `TestDialWithBackoff` work without special environment
  network/transports.go
  network/transports_test.go
Labels: kind/bug, approved, lgtm, size/L

#2501 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
