Repository knative/pkg, pull requests merged in 2022-01, with the labels that each got.

#2381 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#2382 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm

#2384 Validate Sink in SourceSpec
  apis/duck/v1/source_types.go
  apis/duck/v1/source_types_test.go
Labels: size/M, approved, lgtm

#2386 switch to klog/v2
  codegen/cmd/injection-gen/generators/client.go
  codegen/cmd/injection-gen/generators/duck.go
  codegen/cmd/injection-gen/generators/factory.go
  codegen/cmd/injection-gen/generators/fake_client.go
  codegen/cmd/injection-gen/generators/fake_duck.go
  codegen/cmd/injection-gen/generators/fake_factory.go
  codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  codegen/cmd/injection-gen/generators/fake_informer.go
  codegen/cmd/injection-gen/generators/filtered_factory.go
  codegen/cmd/injection-gen/generators/filtered_informer.go
  codegen/cmd/injection-gen/generators/informer.go
  codegen/cmd/injection-gen/generators/packages.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  codegen/cmd/injection-gen/generators/reconciler_state.go
  codegen/cmd/injection-gen/main.go
  go.mod
  go.sum
  injection/config.go
  test/logging/logging.go
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, area/test-and-release

#2388 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#2387 Fixes #2308 TestSpoofingClient_WaitForEndpointState flake
  test/spoof/spoof_test.go
Labels: approved, lgtm, size/S, area/test-and-release

#2389 Simplify URI creation in source validation tests
  apis/duck/v1/source_types_test.go
Labels: approved, lgtm, size/S

#2391 Adjust leaderelection defaults
  leaderelection/config.go
  leaderelection/doc.go
Labels: size/M, approved, lgtm

#2392 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, approved, lgtm

#2363 Allow Unstructured callback from Defaulting Webhook
  testing/resource.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/defaulting/defaulting_test.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/defaulting/user_info.go
Labels: approved, lgtm, size/XL, cla: yes

#2393 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2395 Don't discard addressable resolver original errors
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: kind/bug, approved, lgtm, size/S

#2403 Do not block NotFound error during patching resources
  apiextensions/storageversion/migrator.go
  apiextensions/storageversion/migrator_test.go
Labels: approved, lgtm, size/S

#2404 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2406 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm
