Repository knative/pkg, pull requests merged in 2022-02, with the labels that each got.

#2293 Continual tests logging within test scope
  test/upgrade/asserts_test.go
  test/upgrade/background_verification_test.go
  test/upgrade/execute_failures_test.go
  test/upgrade/functions.go
  test/upgrade/functions_test.go
  test/upgrade/logger.go
  test/upgrade/private_types.go
  test/upgrade/skip_at_verification_test.go
  test/upgrade/steps.go
  test/upgrade/suite_examples_test.go
  test/upgrade/suite_execution.go
  test/upgrade/testing_operations_test.go
  test/upgrade/types.go
  test/upgrade/zaptest_buffer_test.go
Labels: kind/bug, approved, lgtm, area/test-and-release, size/XL, cla: yes

#2412 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2414 Using flags instead of pflag
  injection/sharedmain/main.go
Labels: size/XS, approved, lgtm

#2413 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, approved, lgtm

#2417 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/M, approved, lgtm

#2419 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2431 Make URL compatible with controller-gen
  apis/url.go
Labels: size/XS, approved, lgtm, kind/enhancement

#2429 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2430 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm

#2428 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2437 Wait for reconciler/controllers to return prior to exiting the sharedmain process
  controller/controller.go
  injection/sharedmain/main.go
Labels: size/M, approved, lgtm

#2442 [release-0.26] include go1.17 build tags & bump workflows
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  apis/duck/v1/zz_generated.deepcopy.go
  apis/duck/v1alpha1/zz_generated.deepcopy.go
  apis/duck/v1beta1/zz_generated.deepcopy.go
  apis/test/example/v1alpha1/zz_generated.deepcopy.go
  apis/test/pub/v1alpha1/zz_generated.deepcopy.go
  apis/zz_generated.deepcopy.go
  hack/tools.go
  logging/zz_generated.deepcopy.go
  metrics/zz_generated.deepcopy.go
  signals/signal_posix.go
  testing/duck/zz_generated.deepcopy.go
  testing/zz_generated.deepcopy.go
  tracing/config/zz_generated.deepcopy.go
  tracker/zz_generated.deepcopy.go
  webhook/resourcesemantics/conversion/internal/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L, area/test-and-release

#2434 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm

#2433 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2443 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2423 allow overriding the default grace period of 45 seconds
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/S, ok-to-test, kind/enhancement

#2435 Allow overriding lease name prefix for a reconciler
  configmap/parse.go
  configmap/parse_test.go
  leaderelection/config.go
  leaderelection/context.go
  leaderelection/context_test.go
Labels: approved, lgtm, size/L
