Repository knative/pkg, pull requests merged in 2022-06, with the labels that each got.

#2525 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2527 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2528 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2529 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2530 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2531 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2532 Add fix for CVE-2022-28948
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: size/M, approved, lgtm, kind/cleanup, ok-to-test

#2534 Bump k8s deps to v0.23.8
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#2536 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#2535 Drop `UserInfo` from logger tagging in webhook.
  webhook/admission.go
Labels: size/XS, approved, lgtm, kind/cleanup

#2538 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2540 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
