Repository knative/pkg, pull requests merged in 2022-08, with the labels that each got.

#2565 bump to latest k8s patch (0.23.9)
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2558 Fix issue of tracing.SetupDynamicPublishing
  tracing/setup.go
Labels: size/M, approved, lgtm

#2569 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2570 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2571 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#2568 Remove pkg/pool
  pool/OWNERS
  pool/doc.go
  pool/interface.go
  pool/pool.go
  pool/pool_test.go
Labels: approved, lgtm, size/L, area/API, kind/cleanup

#2566 SetupStaticPublishing and SetupDynamicPublishing returns Tracer with Shutdown function
  tracing/http_test.go
  tracing/opencensus.go
  tracing/opencensus_test.go
  tracing/setup.go
  tracing/zipkin_test.go
Labels: approved, lgtm, size/L

#2572 allow drainer to be reset
  network/handlers/drain.go
  network/handlers/drain_test.go
Labels: approved, lgtm, size/L

#2573 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#2574 fix double close of channel
  network/handlers/drain.go
  network/handlers/drain_test.go
Labels: size/M, approved, lgtm

#2576 WaitForServiceEndpoints doesn't take into account not found endpoints
  test/kube_checks.go
Labels: size/XS, approved, lgtm, area/test-and-release

#2578 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2579 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2580 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2582 split warnings. Fix issue: 2581
  webhook/admission.go
  webhook/admission_integration_test.go
Labels: approved, lgtm, size/L

#2547 Fix #2115, allow selective verbs / subresources for webhooks.
  webhook/resourcesemantics/interface.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/reconcile_config.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/resourcesemantics/validation/validation_admit_test.go
Labels: approved, lgtm, size/L

#2583 Make request body available in admission context
  webhook/admission.go
  webhook/admission_integration_test.go
Labels: approved, lgtm, size/L, ok-to-test

#2584 Update: report stats for request
  webhook/admission.go
  webhook/conversion.go
  webhook/stats_reporter.go
  webhook/stats_reporter_test.go
Labels: size/M, approved, lgtm, kind/cleanup
