Repository knative/pkg, pull requests merged in 2022-10, with the labels that each got.

#2603 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#2595 Bump min kubernetes to v1.23
  version/version.go
  version/version_test.go
Labels: approved, lgtm, size/S

#2606 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2607 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#2605 Preserve webhook namespaceSelector.matchLabels
  webhook/helper.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
Labels: kind/bug, approved, lgtm, size/L

#2608 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#2609 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#2610 Support fetching observability from ctx.
  injection/sharedmain/main.go
  injection/sharedmain/main_test.go
  metrics/config_observability.go
  metrics/config_observability_test.go
Labels: approved, lgtm, size/L, kind/enhancement

#2615 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2616 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2617 make METRICS_DOMAIN optional when backend is not OpenCensus
  metrics/config.go
  metrics/config_test.go
Labels: approved, lgtm, size/S

#2614 Default ConfigMap if ObservabilityConfig is nil
  injection/sharedmain/main_test.go
  metrics/config_observability.go
Labels: kind/bug, size/XS, approved, lgtm, ok-to-test

#2618 Add FieldError#WrappedErrors to allow dependent code to have access (readonly)
  apis/field_error.go
  apis/field_error_test.go
Labels: size/M, approved, lgtm, kind/enhancement

#2619 Cleanup: Turn multiple warnings into multiple warnings.
  webhook/resourcesemantics/validation/validation_admit.go
Labels: approved, lgtm, size/S, kind/cleanup

#2611 Filter reactor FieldErrors on validation to only error-level alerts.
  reconciler/testing/reactions.go
Labels: size/XS, approved, lgtm

#2624 Feature: Implement `Apply` codegen.
  client/injection/kube/client/client.go
  codegen/cmd/injection-gen/generators/client.go
Labels: size/M, approved, lgtm, kind/feature
