Repository knative/pkg, pull requests merged in 2023-01, with the labels that each got.

#2591 Allow logstream to stream logs from user namespace
  test/logstream/interface.go
  test/logstream/v2/stream.go
  test/logstream/v2/stream_test.go
Labels: approved, lgtm, size/L, area/test-and-release

#2664 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2665 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2663 Simplify the test/upgrade package
  test/upgrade/background_verification_test.go
  test/upgrade/execute_failures_test.go
  test/upgrade/functions.go
  test/upgrade/functions_test.go
  test/upgrade/logger.go
  test/upgrade/private_types.go
  test/upgrade/steps.go
  test/upgrade/suite_examples_test.go
  test/upgrade/suite_execution.go
  test/upgrade/testing_operations_test.go
  test/upgrade/testing_types_test.go
  test/upgrade/types.go
Labels: approved, lgtm, area/test-and-release, size/XL, kind/enhancement

#2666 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2667 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#2668 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#2670 Make SetDefaults of Destination duck type nil safer
  apis/duck/v1/destination.go
  apis/duck/v1/destination_test.go
Labels: approved, lgtm, size/S
