Repository knative/pkg, pull requests merged in 2023-02, with the labels that each got.

#2672 update OWNERS files to use teams with active members
  OWNERS
  apiextensions/OWNERS
  apis/OWNERS
  apis/duck/OWNERS
  codegen/OWNERS
  configmap/OWNERS
  controller/OWNERS
  hash/OWNERS
  injection/OWNERS
  kflag/OWNERS
  kmeta/OWNERS
  logging/OWNERS
  metrics/OWNERS
  network/OWNERS
  reconciler/OWNERS
  resolver/OWNERS
  source/OWNERS
  test/mako/OWNERS
  tracing/config/OWNERS
  webhook/OWNERS
  websocket/OWNERS
Labels: approved, lgtm, size/L, area/test-and-release

#2674 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#2676 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2678 fix: `reconcilerImpl.updateStatus` calculates state difference in debug mode only
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1beta1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1beta2/deployment/reconciler.go
  client/injection/kube/reconciler/batch/v1/cronjob/reconciler.go
  client/injection/kube/reconciler/batch/v1beta1/cronjob/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/node/reconciler.go
  client/injection/kube/reconciler/core/v1/pod/reconciler.go
  client/injection/kube/reconciler/extensions/v1beta1/deployment/reconciler.go
  client/injection/kube/reconciler/extensions/v1beta1/networkpolicy/reconciler.go
  client/injection/kube/reconciler/networking/v1/networkpolicy/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Labels: approved, lgtm, size/S, ok-to-test, kind/performance

#2671 Add health checks
  injection/health_check.go
  injection/health_check_test.go
  injection/sharedmain/main.go
Labels: approved, lgtm, size/L

#2683 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2682 Fix potential slowloris attack
  metrics/prometheus_exporter.go
  network/h2c.go
  profiling/server.go
  webhook/webhook.go
Labels: approved, lgtm, size/S, kind/cleanup

#2684 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2688 Allow reconcilers to listen to leader promotion events
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  client/injection/kube/reconciler/admissionregistration/v1/mutatingwebhookconfiguration/controller.go
  client/injection/kube/reconciler/admissionregistration/v1/validatingwebhookconfiguration/controller.go
  client/injection/kube/reconciler/admissionregistration/v1beta1/mutatingwebhookconfiguration/controller.go
  client/injection/kube/reconciler/admissionregistration/v1beta1/validatingwebhookconfiguration/controller.go
  client/injection/kube/reconciler/apps/v1/deployment/controller.go
  client/injection/kube/reconciler/apps/v1beta1/deployment/controller.go
  client/injection/kube/reconciler/apps/v1beta2/deployment/controller.go
  client/injection/kube/reconciler/batch/v1/cronjob/controller.go
  client/injection/kube/reconciler/batch/v1beta1/cronjob/controller.go
  client/injection/kube/reconciler/core/v1/configmap/controller.go
  client/injection/kube/reconciler/core/v1/namespace/controller.go
  client/injection/kube/reconciler/core/v1/node/controller.go
  client/injection/kube/reconciler/core/v1/pod/controller.go
  client/injection/kube/reconciler/core/v1/secret/controller.go
  client/injection/kube/reconciler/extensions/v1beta1/deployment/controller.go
  client/injection/kube/reconciler/extensions/v1beta1/networkpolicy/controller.go
  client/injection/kube/reconciler/networking/v1/networkpolicy/controller.go
  codegen/cmd/injection-gen/generators/reconciler_controller.go
  controller/options.go
Labels: approved, lgtm, size/S

#2692 bump net and text packages
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/text/width/tables10.0.0.go
  vendor/golang.org/x/text/width/tables11.0.0.go
  vendor/golang.org/x/text/width/tables12.0.0.go
  vendor/golang.org/x/text/width/tables13.0.0.go
  vendor/golang.org/x/text/width/tables9.0.0.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#2696 [release-1.9] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L
