Repository knative/pkg, pull requests merged in 2023-07, with the labels that each got.

#2757 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2762 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2764 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2767 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#2769 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2768 Add dependabot and auto update deps
  .github/dependabot.yml
  .github/workflows/knative-dependabot.yaml
Labels: size/M, approved, lgtm
