Repository knative/pkg, pull requests merged in 2023-11, with the labels that each got.

#2882 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2884 fix closure variable in filtered factory
  client/injection/apiextensions/informers/factory/filtered/fake/fake_filtered_factory.go
  client/injection/apiextensions/informers/factory/filtered/filtered_factory.go
  client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  client/injection/kube/informers/factory/filtered/filtered_factory.go
  codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  codegen/cmd/injection-gen/generators/filtered_factory.go
Labels: kind/bug, approved, lgtm, size/S

#2887 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2892 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2893 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2900 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, approved, lgtm

#2901 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#2903 Add clotributor link to readme
  README.md
Labels: size/XS, approved, lgtm

#2906 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2907 bump go to v1.21
  .github/workflows/knative-dependabot.yaml
  .github/workflows/knative-downstream.yaml
Labels: size/XS, approved, lgtm
