Repository knative/pkg, pull requests merged in 2023-05, with the labels that each got.

#2735 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2743 Eventing TLS: validate that Destination.CACerts is a PEM encoded cert
  apis/duck/v1/destination.go
  apis/duck/v1/destination_test.go
  apis/duck/v1beta1/destination.go
  apis/duck/v1beta1/destination_test.go
Labels: approved, lgtm, size/L, kind/enhancement

#2744 drop dynamic client wrappers in namespaced informers
  injection/clients/namespacedkube/informers/core/v1/configmap/configmap.go
  injection/clients/namespacedkube/informers/core/v1/secret/secret.go
Labels: approved, lgtm, size/L

#2747 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2751 Fix some webhook testing tech debt
  webhook/admission_integration_test.go
  webhook/conversion_integration_test.go
  webhook/helper_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/L

#2750 Drop the unused injection.Dynamic interface
  injection/clients.go
  injection/informers.go
  injection/interface.go
Labels: size/M, approved, lgtm
