Repository knative/pkg, pull requests merged in 2023-08, with the labels that each got.

#2778 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#2779 Rename knative-sandbox to knative-extensions
  .github/workflows/knative-downstream.yaml
Labels: approved, lgtm, size/S

#2777 Use go sync/atomic instead of go.uber.org/atomic
  apis/duck/cached_test.go
  controller/controller_test.go
  go.mod
  metrics/metrics.go
  profiling/server.go
  reconciler/testing/context.go
  reconciler/testing/hooks.go
  test/spoof/spoof_test.go
  test/zipkin/util.go
Labels: size/M, approved, lgtm, area/test-and-release

#2662 Allow overriding webhook secret data keys
  webhook/helper.go
  webhook/helper_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/L, kind/enhancement

#2781 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2788 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2794 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2789 Bump gomodules.xyz/jsonpatch/v2 from 2.2.0 to 2.3.0
  apis/duck/patch_test.go
  go.mod
  go.sum
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/cleanup

#2799 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm
