Repository knative/pkg, pull requests merged in 2023-06, with the labels that each got.

#2752 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2738 Defaulting Controller options for all kind of webhooks
  webhook/resourcesemantics/conversion/controller.go
  webhook/resourcesemantics/conversion/options.go
  webhook/resourcesemantics/conversion/options_test.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/defaulting/options.go
  webhook/resourcesemantics/defaulting/options_test.go
  webhook/resourcesemantics/validation/controller.go
  webhook/resourcesemantics/validation/options.go
  webhook/resourcesemantics/validation/options_test.go
  webhook/webhook.go
Labels: kind/bug, approved, lgtm, size/L, ok-to-test

#2754 Generate kresource duck type injection
  apis/duck/v1/kresource_type.go
  client/injection/ducks/duck/v1/kresource/fake/fake.go
  client/injection/ducks/duck/v1/kresource/kresource.go
Labels: size/XS, approved, lgtm

#2760 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
