Repository knative/pkg, pull requests merged in 2023-04, with the labels that each got.

#2722 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2719 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2724 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2726 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#2721 Make minimum TLS version configurable for webhooks
  metrics/opencensus_exporter.go
  network/transports_test.go
  webhook/env.go
  webhook/env_test.go
  webhook/webhook.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/L, kind/enhancement

#2728 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2717 Eventing TLS: Added AddressableFromDestination method on the resolver
  apis/duck/v1/knative_reference.go
  resolver/addressable_resolver.go
  resolver/addressable_resolver_test.go
Labels: approved, lgtm, kind/feature, size/XL, ok-to-test

#2734 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
