Repository knative/pkg, pull requests merged in 2023-09, with the labels that each got.

#2808 generate serviceaccount reconciler
  client/injection/kube/reconciler/core/v1/serviceaccount/controller.go
  client/injection/kube/reconciler/core/v1/serviceaccount/reconciler.go
  client/injection/kube/reconciler/core/v1/serviceaccount/state.go
  hack/update-codegen.sh
Labels: size/XS, approved, lgtm, area/test-and-release, kind/enhancement

#2798 Added Audience field in duckv1.Addressable
  apis/duck/v1/addressable_types.go
  apis/duck/v1/zz_generated.deepcopy.go
Labels: size/XS, approved, lgtm, ok-to-test

#2797 Added Audience field in duckv1.Destination
  apis/duck/v1/destination.go
  apis/duck/v1/zz_generated.deepcopy.go
Labels: size/XS, approved, lgtm, ok-to-test

#2817 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2810 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#2829 Add AuthStatus type
  apis/duck/v1/auth_types.go
  apis/duck/v1/source_types.go
  apis/duck/v1/zz_generated.deepcopy.go
Labels: size/M, approved, lgtm, ok-to-test, kind/api-change

#2831 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2830 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2833 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2839 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2841 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: size/M, approved, lgtm
