Repository knative/pkg, pull requests merged in 2024-06, with the labels that each got.

#3047 fix: downstream tests assume release branch was cut
  .github/workflows/knative-downstream.yaml
Labels: approved, lgtm, size/S, ok-to-test

#3046 Maybe fix controller ha
  test/ha/ha.go
Labels: size/XS, approved, lgtm, area/test-and-release

#3049 Extra logging for leases
  test/ha/ha.go
Labels: size/XS, approved, lgtm, area/test-and-release

#3050 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3056 Add AuthenticatableType duck type
  apis/duck/v1/auth_types.go
  apis/duck/v1/zz_generated.deepcopy.go
  client/injection/ducks/duck/v1/authstatus/authstatus.go
  client/injection/ducks/duck/v1/authstatus/fake/fake.go
  resolver/authenticatable_resolver.go
  resolver/authenticatable_resolver_test.go
Labels: approved, lgtm, size/L

#3061 drop eventing kafka from downstream tests - repo is archived
  .github/workflows/knative-downstream.yaml
Labels: size/XS, approved, lgtm

#3062 bump go.mod go version to 1.22 and drop unused dependency
  go.mod
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: approved, lgtm, size/XL

#3064 drop unused OWNERS files and update k8s script
  hack/OWNERS
  hack/update-k8s-deps.sh
Labels: size/M, approved, lgtm, area/test-and-release

#3066 [logstream] test polling should use a different context
  test/logstream/v2/stream_test.go
Labels: size/XS, approved, lgtm, area/test-and-release

#3069 Register `AuthenticatableType` in scheme
  apis/duck/v1/register.go
Labels: size/XS, approved, lgtm

#3070 Fix rand source in name
  test/helpers/name.go
Labels: size/XS, approved, lgtm, area/test-and-release
