Repository knative/pkg, pull requests merged in 2024-02, with the labels that each got.

#2950 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2955 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2956 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2957 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2966 drop toolchain directive
  go.mod
Labels: size/XS, approved, lgtm

#2967 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2968 drop http01 from downstream testing
  .github/workflows/knative-downstream.yaml
Labels: size/XS, approved, lgtm

#2969 drop eventing-rabbitmq downstream testing
  .github/workflows/knative-downstream.yaml
Labels: size/XS, approved, lgtm

#2970 use shared setup-go and drop installation of go-licenses
  .github/workflows/knative-dependabot.yaml
  .github/workflows/knative-downstream.yaml
Labels: approved, lgtm, size/S

#2971 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
