Repository knative/pkg, pull requests merged in 2024-01, with the labels that each got.

#2929 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2915 Fixing all deprecated use of sets.String
  client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1/mutatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1/validatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1beta1/mutatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/admissionregistration/v1beta1/validatingwebhookconfiguration/reconciler.go
  client/injection/kube/reconciler/apps/v1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1beta1/deployment/reconciler.go
  client/injection/kube/reconciler/apps/v1beta2/deployment/reconciler.go
  client/injection/kube/reconciler/batch/v1/cronjob/reconciler.go
  client/injection/kube/reconciler/batch/v1beta1/cronjob/reconciler.go
  client/injection/kube/reconciler/core/v1/configmap/reconciler.go
  client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  client/injection/kube/reconciler/core/v1/node/reconciler.go
  client/injection/kube/reconciler/core/v1/pod/reconciler.go
  client/injection/kube/reconciler/core/v1/secret/reconciler.go
  client/injection/kube/reconciler/core/v1/service/reconciler.go
  client/injection/kube/reconciler/core/v1/serviceaccount/reconciler.go
  client/injection/kube/reconciler/extensions/v1beta1/deployment/reconciler.go
  client/injection/kube/reconciler/extensions/v1beta1/networkpolicy/reconciler.go
  client/injection/kube/reconciler/networking/v1/networkpolicy/reconciler.go
  codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  configmap/informer/synced_callback.go
  configmap/parse.go
  configmap/parse_test.go
  hash/bucketer.go
  hash/bucketer_test.go
  hash/hash.go
  hash/hash_test.go
  kflag/set.go
  leaderelection/chaosduck/main.go
  leaderelection/context.go
  leaderelection/context_test.go
  logging/object_encoders.go
  reconciler/testing/table.go
  test/ha/ha.go
  test/spoof/response_checks.go
  webhook/psbinding/psbinding.go
  webhook/psbinding/reconciler.go
Labels: approved, lgtm, size/L, area/test-and-release, kind/cleanup, ok-to-test

#2930 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#2932 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2938 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#2939 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2942 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2943 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2949 Update knative.dev/hack to latest main
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm
