Repository knative/pkg, pull requests merged in 2024-04, with the labels that each got.

#2931 webhook: add options to disable resource_namespace tag in metrics
  injection/sharedmain/main.go
  webhook/stats_reporter.go
  webhook/stats_reporter_test.go
  webhook/webhook.go
Labels: approved, lgtm, size/L, ok-to-test

#3004 Replace all usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout
  controller/two_lane_queue_test.go
  injection/sharedmain/main.go
  metrics/e2e_test.go
  metrics/resource_view_test.go
  reconciler/testing/context.go
  test/cleanup_test.go
  test/ha/ha.go
  test/kube_checks.go
  test/logstream/v2/stream_test.go
  test/spoof/spoof.go
  webhook/certificates/certificates_test.go
  webhook/configmaps/table_test.go
  webhook/helper_test.go
  webhook/psbinding/table_test.go
  webhook/resourcesemantics/defaulting/table_test.go
  webhook/resourcesemantics/validation/reconcile_config_test.go
  webhook/resourcesemantics/validation/validation_admit_test.go
  websocket/connection_test.go
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#3007 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3014 Bump x/net to 0.24
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3008 Revert "drop eventing-rabbitmq downstream testing (#2969)"
  .github/workflows/knative-downstream.yaml
Labels: size/XS, approved, lgtm

#3018 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#3019 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3024 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
