Repository knative/pkg, pull requests merged in 2024-10, with the labels that each got.

#3101 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3104 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#3105 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3103 Add `WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP` env-var
  webhook/env.go
  webhook/webhook.go
Labels: approved, lgtm, size/S, ok-to-test, kind/enhancement

#3107 Fix `WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP` env-var
  webhook/configmaps/controller.go
  webhook/resourcesemantics/defaulting/controller.go
  webhook/resourcesemantics/validation/controller.go
  webhook/webhook.go
Labels: kind/bug, approved, lgtm, size/S, ok-to-test

#3110 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#3111 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
