Repository knative/pkg, pull requests merged in 2024-05, with the labels that each got.

#3031 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3032 Update AuthStatus to have list of ServiceAccountNames
  apis/duck/v1/auth_types.go
  apis/duck/v1/zz_generated.deepcopy.go
Labels: size/XS, approved, lgtm

#3027 Add composite ConfigStore to combine multiple `ConfigStore`
  reconciler/configstore.go
Labels: approved, lgtm, size/S

#3037 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#3042 Skip lease with empty holder
  test/ha/ha.go
Labels: size/XS, approved, lgtm, area/test-and-release

#3044 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2997 drop special logic when handling kubelet probe header for istio mTLS
  network/network.go
  network/network_test.go
Labels: approved, lgtm, size/S
