Repository knative/pkg, pull requests merged in 2025-01, with the labels that each got.

#3127 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3133 run dependabot workflow only on dependabot branches
  .github/workflows/knative-dependabot.yaml
Labels: size/XS, approved, lgtm

#3132 Satisfy linter
  .golangci.yaml
  apis/testing/roundtrip/roundtrip.go
  controller/controller.go
  controller/controller_test.go
  controller/two_lane_queue.go
  controller/two_lane_queue_test.go
  hash/hash.go
  hash/hash_test.go
  kmeta/names_test.go
  metrics/config.go
  metrics/memstats.go
  metrics/record_test.go
  metrics/resource_view_test.go
  test/imports/banned_deps_test.go
  tracing/http_test.go
  webhook/admission_integration_test.go
  webhook/testing/factory.go
Labels: approved, lgtm, size/L, area/test-and-release

#3137 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#3136 drop use of code-generator/generate-groups.sh
  apis/test/example/v1alpha1/doc.go
  apis/test/example/v1alpha1/zz_generated.deepcopy.go
  apis/test/pub/v1alpha1/doc.go
  apis/test/pub/v1alpha1/zz_generated.deepcopy.go
  hack/generate-knative.sh
  hack/update-codegen.sh
  injection/README.md
  test/test-reconciler-codegen.sh
Labels: size/M, approved, lgtm, area/test-and-release

#3140 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
