Repository knative/pkg, pull requests merged in 2025-07, with the labels that each got.

#3205 wire zap into the client-go logger
  go.mod
  go.sum
  injection/sharedmain/main.go
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/go-logr/zapr/.gitignore
  vendor/github.com/go-logr/zapr/.golangci.yaml
  vendor/github.com/go-logr/zapr/LICENSE
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/slogzapr.go
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/github.com/go-logr/zapr/zapr_noslog.go
  vendor/github.com/go-logr/zapr/zapr_slog.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#3202 Drop OpenCensus use in various test packages
  go.mod
  go.sum
  test/logging/logging.go
  test/spoof/spoof.go
  vendor/github.com/felixge/httpsnoop/.gitignore
  vendor/github.com/felixge/httpsnoop/LICENSE.txt
  vendor/github.com/felixge/httpsnoop/Makefile
  vendor/github.com/felixge/httpsnoop/README.md
  vendor/github.com/felixge/httpsnoop/capture_metrics.go
  vendor/github.com/felixge/httpsnoop/docs.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_gteq_1.8.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_lt_1.8.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/LICENSE
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/client.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/common.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/config.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/doc.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request/body_wrapper.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/env.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/util.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/v1.20.0.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/gen.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/labeler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/start_time_context.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/README.md
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/attribute_group.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/doc.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/event.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/exception.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/resource.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/schema.go
  vendor/go.opentelemetry.io/otel/semconv/v1.20.0/trace.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, area/test-and-release

#3189 [webhook] OTel changes
  go.mod
  go.sum
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/config.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request/body_wrapper.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request/gen.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/env.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/gen.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/util.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconv/v1.20.0.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/labeler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/otel/semconv/v1.34.0/httpconv/metric.go
  vendor/modules.txt
  webhook/admission.go
  webhook/admission_integration_test.go
  webhook/conversion.go
  webhook/conversion_integration_test.go
  webhook/metrics.go
  webhook/resourcesemantics/conversion/conversion.go
  webhook/resourcesemantics/defaulting/defaulting.go
  webhook/resourcesemantics/validation/validation_admit.go
  webhook/stats_reporter.go
  webhook/stats_reporter_test.go
  webhook/webhook.go
  webhook/webhook_integration_test.go
  webhook/webhook_test.go
Labels: approved, lgtm, size/XXL

#3207 [observability/trace] allow for stdout exporter for tracing - to allow for debugging
  go.mod
  go.sum
  observability/tracing/config.go
  observability/tracing/provider.go
  vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/LICENSE
  vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/README.md
  vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/config.go
  vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/doc.go
  vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/trace.go
  vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/README.md
  vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/exporter.go
  vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/recorder.go
  vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/span.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#3208 [observability/tracing] pass options to the TracerProvider constructor
  observability/tracing/provider.go
Labels: size/XS, approved, lgtm

#3206 [controller/observability] adjust metrics reporting for the two lane queue
  controller/controller.go
  controller/controller_test.go
  controller/queue_metrics.go
  controller/two_lane_queue.go
  controller/two_lane_queue_test.go
  injection/sharedmain/main.go
  observability/metrics/k8s/noop.go
Labels: approved, lgtm, size/L

#3212 add json struct tags to the observability configs
  observability/metrics/config.go
  observability/runtime/config.go
  observability/tracing/config.go
Labels: approved, lgtm, size/S

#3214 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3215 drop dependency on metrics package
  profiling/server_test.go
Labels: size/XS, approved, lgtm

#3218 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm
