Repository knative/pkg, pull requests merged in 2025-04, with the labels that each got.

#3167 update .golangci.yaml to v2
  .golangci.yaml
Labels: approved, lgtm, size/L

#3170 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#3171 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3174 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
